/*
 * Copyright (c) 2015 - 2016 , Freescale Semiconductor, Inc.
 * Copyright 2016-2017 NXP
 * All rights reserved.
 *
 * THIS SOFTWARE IS PROVIDED BY NXP "AS IS" AND ANY EXPRESSED OR
 * IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES
 * OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
 * IN NO EVENT SHALL NXP OR ITS CONTRIBUTORS BE LIABLE FOR ANY DIRECT,
 * INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
 * (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
 * SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
 * HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT,
 * STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING
 * IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF
 * THE POSSIBILITY OF SUCH DAMAGE.
 */

#ifndef _BOARD_DEFINES_H_
#define _BOARD_DEFINES_H_

#include <stdint.h>
#include <stdbool.h>

/* This file defines the specific ports and pins for Evaluation Board and
 * Validation Board. To use with Validation Board uncomment the following
 * line
 */

#ifdef EVB
    #define LED1            15U
    #define LED2            16U
    #define LED_GPIO        PTD
    #define LED_PORT        PORTD
    #define LED_PORT_PCC    PCC_PORTD_CLOCK
    #define BTN_GPIO        PTC
    #define BTN_PIN         13U
    #define BTN_PORT        PORTC
    #define BTN_PORT_PCC    PCC_PORTC_CLOCK
    #define BTN_PORT_IRQn   PORTC_IRQn
#endif
#define PORT_4G_RST_3V3		PTE
#define PORT_PIN_4G_RST_3V3		16U

#define PORT_4G_PWRKEY_3V3		PTE
#define PORT_PIN_4G_PWRKEY_3V3		15U

#define PORT_4G_DTR_3V3		PTE
#define PORT_PIN_4G_DTR_3V3		11U

#define PORT_4G_RI_3V3		PTE
#define PORT_PIN_4G_RI_3V3		10U

#define PORT_AMP_STB		PTE
#define PORT_PIN_AMP_STB		13U

#define PORT_TEST_PAD1		PTE
#define PORT_PIN_TEST_PAD1		5U

#define PORT_TUNER_CURRENT_DIAG		PTD
#define PORT_PIN_TUNER_CURRENT_DIAG		16U

#define PORT_FM_AM_ON_ANT		PTD
#define PORT_PIN_FM_AM_ON_ANT		15U

#define PORT_UG1V8_ON		PTE
#define PORT_PIN_UG1V8_ON		8U

#define PORT_UG5V_ON		PTB
#define PORT_PIN_UG5V_ON		5U

#define PORT_ILL_IN		PTB
#define PORT_PIN_ILL_IN		4U

#define PORT_TEST_PAD2		PTD
#define PORT_PIN_TEST_PAD2		6U

#define PORT_HW_VERSION		PTC
#define PORT_PIN_HW_VERSION		1U

#define PORT_CAN_STB		PTB
#define PORT_PIN_CAN_STB		22U

#define PORT_VOICE_A1		PTB
#define PORT_PIN_VOICE_A1		23U

#define PORT_PMIC_PWRON		PTC
#define PORT_PIN_PMIC_PWRON		14U

#define PORT_MX8QXP_GPIO0_29		PTB
#define PORT_PIN_MX8QXP_GPIO0_29		25U

#define PORT_MX8QXP_GPIO0_30		PTB
#define PORT_PIN_MX8QXP_GPIO0_30		3U

#define PORT_MX8QXP_GPIO0_31		PTB
#define PORT_PIN_MX8QXP_GPIO0_31		27U

#define PORT_CHARGE_5V_ON		PTB
#define PORT_PIN_CHARGE_5V_ON		28U

#define PORT_IOC_PMIC_WDI		PTB
#define PORT_PIN_IOC_PMIC_WDI		2U

#define PORT_IOC_BOOT_MODE		PTC
#define PORT_PIN_IOC_BOOT_MODE		13U

#define PORT_IOC_AP_ONOFF		PTC
#define PORT_PIN_IOC_AP_ONOFF		12U

#define PORT_CHARGE0_STATUS		PTC
#define PORT_PIN_CHARGE0_STATUS		19U

#define PORT_CHARGE2_EN		PTC
#define PORT_PIN_CHARGE2_EN		23U

#define PORT_CHARGE0_FAULT		PTC
#define PORT_PIN_CHARGE0_FAULT		11U

#define PORT_CHARGE2_STATUS		PTC
#define PORT_PIN_CHARGE2_STATUS		10U

#define PORT_CHARGE2_FAULT		PTC
#define PORT_PIN_CHARGE2_FAULT		27U

#define PORT_LCD_PWR_ON		PTC
#define PORT_PIN_LCD_PWR_ON		28U

#define PORT_BL_PWR_ON		PTC
#define PORT_PIN_BL_PWR_ON		9U

#define PORT_BL_EN		PTC
#define PORT_PIN_BL_EN		8U

#define PORT_IMX_TRACE_RST		PTC
#define PORT_PIN_IMX_TRACE_RST		29U

#define PORT_EE_WP		PTE
#define PORT_PIN_EE_WP		7U

#define PORT_ACC_ONOFF		PTA
#define PORT_PIN_ACC_ONOFF		17U

#define PORT_UG1V2_ON		PTB
#define PORT_PIN_UG1V2_ON		17U

#define PORT_PWR_BT_WLAN_ON		PTB
#define PORT_PIN_PWR_BT_WLAN_ON		16U

#define PORT_PMIC2_FEED_5V0_ON		PTB
#define PORT_PIN_PMIC2_FEED_5V0_ON		15U

#define PORT_MX8QXP_GPIO1_8		PTB
#define PORT_PIN_MX8QXP_GPIO1_8		14U

#define PORT_UDBATT_AD_EN		PTB
#define PORT_PIN_UDBATT_AD_EN		13U

#define PORT_UG3V3_ON		PTB
#define PORT_PIN_UG3V3_ON		12U

#define PORT_LVI_DET		PTD
#define PORT_PIN_LVI_DET		22U

#define PORT_VCC12VOUT_EN		PTD
#define PORT_PIN_VCC12VOUT_EN		4U

#define PORT_CAN_INH		PTB
#define PORT_PIN_CAN_INH		11U

#define PORT_CAN_EN		PTD
#define PORT_PIN_CAN_EN		27U

#define PORT_GPS_FWD		PTD
#define PORT_PIN_GPS_FWD		28U

#define PORT_TEST_PAD3		PTA
#define PORT_PIN_TEST_PAD3		1U

#define PORT_TEST_PAD4		PTA
#define PORT_PIN_TEST_PAD4		0U

#define PORT_TFT_DETECT		PTD
#define PORT_PIN_TFT_DETECT		30U

#define PORT_TEST_PAD5		PTC
#define PORT_PIN_TEST_PAD5		7U

#define PORT_TEST_PAD6		PTC
#define PORT_PIN_TEST_PAD6		6U

#define PORT_CAN_WAKE		PTA
#define PORT_PIN_CAN_WAKE		16U

#define PORT_CAN_ERR		PTA
#define PORT_PIN_CAN_ERR		15U

#define PORT_CHARGE0_EN		PTE
#define PORT_PIN_CHARGE0_EN		6U

#define PORT_CHARGE1_CTL3		PTE
#define PORT_PIN_CHARGE1_CTL3		2U

#define PORT_CHARGE1_CTL2		PTE
#define PORT_PIN_CHARGE1_CTL2		19U

#define PORT_CHARGE1_STATUS		PTE
#define PORT_PIN_CHARGE1_STATUS		20U

#define PORT_MCU_SLEEP_STATUS	PTE
#define PORT_PIN_MCU_SLEEP_STATUS	21U

#define PORT_MCU_WAKEUP_4G		PTE
#define PORT_PIN_MCU_WAKEUP_4G		22U

#define PORT_CHARGE1_FAULT		PTE
#define PORT_PIN_CHARGE1_FAULT		23U

#define PORT_CHARGE1_CTL1		PTE
#define PORT_PIN_CHARGE1_CTL1		24U

#define PORT_CHARGE1_EN		PTE
#define PORT_PIN_CHARGE1_EN		25U

#define PORT_SPI_IPC_REQ           PTB
#define PORT_PIN_SPI_IPC_REQ    14U

#define PORT_SPI_IPC_ACK           PTB
#define PORT_PIN_SPI_IPC_ACK    3U

#include "pins_driver.h"

#endif
