/******************************************************************************
**          Copyright (c) by HASE (Chengdu) Technology Center.
**
**          CONFIDENTIAL and PROPRIETARY
**          UNPUBLISHED SOURCE CODE
**          Disclosure, use or reproduction without authorization of
**          HASE (Chengdu) Technology Center is prohibited.
*******************************************************************************
**
**          File  : Ea_cfg.h
**          Modifly:brown
**			author: weltry wang
**          Date  : 2017-06-20
**          
**          History:
**          1. Date:2018-02-26
**             Author:weltry wang
**             Modification:
**
******************************************************************************/


//#include "Eeprom.h"
#include "MemIf_types.h"
#include "NvM_Cbk.h"

#ifndef Ea_Cfg_H
#define Ea_Cfg_H
#ifdef __cplusplus
}
#endif





/*** Start , DO NOT MODIFY THIS TEXT!!! ***/
/*** Don't write any code pass this line, or it will be deleted during code generation. ***/
/*** ***********************The below lines is generated by tool*********************** ***/
#define EA_BLOCK_NUM_ALL_DF          145U

/*** The above lines is generated by tool ***/
/*** Generation data:2020-02-17 11:10 ***/
/*** End , DO NOT MODIFY THIS TEXT!!! ***/

extern const uint16 EaMarkerAddStart; 
extern const uint16 EA_VERSION;

#ifdef __cplusplus
}
#endif
#endif

