/******************************************************************************
**          Copyright (c) by HASE (Chengdu) Technology Center.
**
**          CONFIDENTIAL and PROPRIETARY
**          UNPUBLISHED SOURCE CODE
**          Disclosure, use or reproduction without authorization of
**          HASE (Chengdu) Technology Center is prohibited.
*******************************************************************************
**
**          File  : Ea_cfg.c
**          Modifly:brown
**			author: weltry wang
**          Date  : 2017-06-20
**          
**          History:
**          1. Date:2018-02-26
**             Author:weltry wang
**             Modification:
**
******************************************************************************/
/*====================[I N C L U D E S]====================*/
#include "Ea_Cfg.h"
#include "Ea.h"



/*====================[V A R I A N T S]====================*/


//32~39 Ea Markers
const uint16 EaMarkerAddStart  =   32u;
const uint16 EaMarkerAddEnd    =   39u;
//const uint8  EaMarkerAddLen    =   8u;

//40~159 BlockIndex,a block index need two bytes
const uint16 BlockIndexAddStart  = 40u;
//const uint16 BlockIndexAddEnd    = 159u;
const uint16 BlockIndexAddEnd    = 639u;

const uint8  A_BlockIndexLen     = 2u;

//160~3159  page1 save diagnostic
//const uint16 PAGEADDSTART_0  = 160;
//const uint16 PAGEADDEND_0    = 3159;

//640~12287  page1 
const uint16 PAGEADDSTART_0  = 640;
const uint16 PAGEADDEND_0    = 12287;


//3160~4095 page2 save others
//const uint16 PAGEADDSTART_1 = 3160;
//const uint16 PAGEADDEND_1   = 4095;

//12288~16383 page2 save others
const uint16 PAGEADDSTART_1 = 12288;
/* 12288-12293 save tdf853x amp flag and kvalues */
const uint16 PAGEADDEND_1   = 16383;

//all pages number
//#define	PAGENUMALL           2

const uint8 EA_CrcLength    = 2;


const uint8  FristWriteCheakTab[4]={0x5A,0xA5,0x9F,0xAF};

EaBlockAdminType      EaBlockAdmin[EA_BLOCK_NUM_ALL_DF+1] = {{0,0,0}};
uint16                PageNextWriteAdd[PAGENUMALL]     = {0u}; //next write address in pagex

/*** Start , DO NOT MODIFY THIS TEXT!!! ***/
/*** Don't write any code pass this line, or it will be deleted during code generation. ***/
/*** ***********************The below lines is generated by tool*********************** ***/
const uint16 EA_VERSION=49;
const EaBlockConfigType EaBlockConfiguration[EA_BLOCK_NUM_ALL_DF+1u]=
{
  {0,0,0,0},
  {/*Block 1*/
    4,/*EaBlockSize*/
    0,/*EaPageNumber*/
    0xff,/*EaNumberOfWriteCycles*/
    EA_BLOCK_NO_MODFIED
  },
  {/*Block 2*/
    4,/*EaBlockSize*/
    0,/*EaPageNumber*/
    0xff,/*EaNumberOfWriteCycles*/
    EA_BLOCK_NO_MODFIED
  },
  {/*Block 3*/
    4,/*EaBlockSize*/
    0,/*EaPageNumber*/
    0xff,/*EaNumberOfWriteCycles*/
    EA_BLOCK_NO_MODFIED
  },
  {/*Block 4*/
    6,/*EaBlockSize*/
    0,/*EaPageNumber*/
    0xff,/*EaNumberOfWriteCycles*/
    EA_BLOCK_NO_MODFIED
  },
  {/*Block 5*/
    6,/*EaBlockSize*/
    0,/*EaPageNumber*/
    0xff,/*EaNumberOfWriteCycles*/
    EA_BLOCK_NO_MODFIED
  },
  {/*Block 6*/
    6,/*EaBlockSize*/
    0,/*EaPageNumber*/
    0xff,/*EaNumberOfWriteCycles*/
    EA_BLOCK_NO_MODFIED
  },
  {/*Block 7*/
    12,/*EaBlockSize*/
    0,/*EaPageNumber*/
    0xff,/*EaNumberOfWriteCycles*/
    EA_BLOCK_NO_MODFIED
  },
  {/*Block 8*/
    6,/*EaBlockSize*/
    0,/*EaPageNumber*/
    0xff,/*EaNumberOfWriteCycles*/
    EA_BLOCK_NO_MODFIED
  },
  {/*Block 9*/
    10,/*EaBlockSize*/
    0,/*EaPageNumber*/
    0xff,/*EaNumberOfWriteCycles*/
    EA_BLOCK_NO_MODFIED
  },
  {/*Block 10*/
    4,/*EaBlockSize*/
    0,/*EaPageNumber*/
    0xff,/*EaNumberOfWriteCycles*/
    EA_BLOCK_NO_MODFIED
  },
  {/*Block 11*/
    32,/*EaBlockSize*/
    0,/*EaPageNumber*/
    0xff,/*EaNumberOfWriteCycles*/
    EA_BLOCK_MODFIED
  },
  {/*Block 12*/
    3,/*EaBlockSize*/
    0,/*EaPageNumber*/
    0xff,/*EaNumberOfWriteCycles*/
    EA_BLOCK_NO_MODFIED
  },
  {/*Block 13*/
    22,/*EaBlockSize*/
    0,/*EaPageNumber*/
    0xff,/*EaNumberOfWriteCycles*/
    EA_BLOCK_NO_MODFIED
  },
  {/*Block 14*/
    19,/*EaBlockSize*/
    0,/*EaPageNumber*/
    0xff,/*EaNumberOfWriteCycles*/
    EA_BLOCK_NO_MODFIED
  },
  {/*Block 15*/
    3,/*EaBlockSize*/
    0,/*EaPageNumber*/
    0xff,/*EaNumberOfWriteCycles*/
    EA_BLOCK_NO_MODFIED
  },
  {/*Block 16*/
    6,/*EaBlockSize*/
    0,/*EaPageNumber*/
    0xff,/*EaNumberOfWriteCycles*/
    EA_BLOCK_NO_MODFIED
  },
  {/*Block 17*/
    32,/*EaBlockSize*/
    0,/*EaPageNumber*/
    0xff,/*EaNumberOfWriteCycles*/
    EA_BLOCK_MODFIED
  },
  {/*Block 18*/
    34,/*EaBlockSize*/
    0,/*EaPageNumber*/
    0xff,/*EaNumberOfWriteCycles*/
    EA_BLOCK_MODFIED
  },
  {/*Block 19*/
    6,/*EaBlockSize*/
    0,/*EaPageNumber*/
    0xff,/*EaNumberOfWriteCycles*/
    EA_BLOCK_MODFIED
  },
  {/*Block 20*/
    6,/*EaBlockSize*/
    0,/*EaPageNumber*/
    0xff,/*EaNumberOfWriteCycles*/
    EA_BLOCK_MODFIED
  },
  {/*Block 21*/
    6,/*EaBlockSize*/
    0,/*EaPageNumber*/
    0xff,/*EaNumberOfWriteCycles*/
    EA_BLOCK_MODFIED
  },
  {/*Block 22*/
    6,/*EaBlockSize*/
    0,/*EaPageNumber*/
    0xff,/*EaNumberOfWriteCycles*/
    EA_BLOCK_MODFIED
  },
  {/*Block 23*/
    6,/*EaBlockSize*/
    0,/*EaPageNumber*/
    0xff,/*EaNumberOfWriteCycles*/
    EA_BLOCK_MODFIED
  },
  {/*Block 24*/
    6,/*EaBlockSize*/
    0,/*EaPageNumber*/
    0xff,/*EaNumberOfWriteCycles*/
    EA_BLOCK_MODFIED
  },
  {/*Block 25*/
    6,/*EaBlockSize*/
    0,/*EaPageNumber*/
    0xff,/*EaNumberOfWriteCycles*/
    EA_BLOCK_MODFIED
  },
  {/*Block 26*/
    6,/*EaBlockSize*/
    0,/*EaPageNumber*/
    0xff,/*EaNumberOfWriteCycles*/
    EA_BLOCK_MODFIED
  },
  {/*Block 27*/
    6,/*EaBlockSize*/
    0,/*EaPageNumber*/
    0xff,/*EaNumberOfWriteCycles*/
    EA_BLOCK_MODFIED
  },
  {/*Block 28*/
    6,/*EaBlockSize*/
    0,/*EaPageNumber*/
    0xff,/*EaNumberOfWriteCycles*/
    EA_BLOCK_MODFIED
  },
  {/*Block 29*/
    6,/*EaBlockSize*/
    0,/*EaPageNumber*/
    0xff,/*EaNumberOfWriteCycles*/
    EA_BLOCK_MODFIED
  },
  {/*Block 30*/
    6,/*EaBlockSize*/
    0,/*EaPageNumber*/
    0xff,/*EaNumberOfWriteCycles*/
    EA_BLOCK_MODFIED
  },
  {/*Block 31*/
    6,/*EaBlockSize*/
    0,/*EaPageNumber*/
    0xff,/*EaNumberOfWriteCycles*/
    EA_BLOCK_MODFIED
  },
  {/*Block 32*/
    6,/*EaBlockSize*/
    0,/*EaPageNumber*/
    0xff,/*EaNumberOfWriteCycles*/
    EA_BLOCK_MODFIED
  },
  {/*Block 33*/
    6,/*EaBlockSize*/
    0,/*EaPageNumber*/
    0xff,/*EaNumberOfWriteCycles*/
    EA_BLOCK_MODFIED
  },
  {/*Block 34*/
    6,/*EaBlockSize*/
    0,/*EaPageNumber*/
    0xff,/*EaNumberOfWriteCycles*/
    EA_BLOCK_MODFIED
  },
  {/*Block 35*/
    8,/*EaBlockSize*/
    0,/*EaPageNumber*/
    0xff,/*EaNumberOfWriteCycles*/
    EA_BLOCK_MODFIED
  },
  {/*Block 36*/
    8,/*EaBlockSize*/
    0,/*EaPageNumber*/
    0xff,/*EaNumberOfWriteCycles*/
    EA_BLOCK_MODFIED
  },
  {/*Block 37*/
    8,/*EaBlockSize*/
    0,/*EaPageNumber*/
    0xff,/*EaNumberOfWriteCycles*/
    EA_BLOCK_MODFIED
  },
  {/*Block 38*/
    8,/*EaBlockSize*/
    0,/*EaPageNumber*/
    0xff,/*EaNumberOfWriteCycles*/
    EA_BLOCK_MODFIED
  },
  {/*Block 39*/
    8,/*EaBlockSize*/
    0,/*EaPageNumber*/
    0xff,/*EaNumberOfWriteCycles*/
    EA_BLOCK_MODFIED
  },
  {/*Block 40*/
    8,/*EaBlockSize*/
    0,/*EaPageNumber*/
    0xff,/*EaNumberOfWriteCycles*/
    EA_BLOCK_MODFIED
  },
  {/*Block 41*/
    8,/*EaBlockSize*/
    0,/*EaPageNumber*/
    0xff,/*EaNumberOfWriteCycles*/
    EA_BLOCK_MODFIED
  },
  {/*Block 42*/
    8,/*EaBlockSize*/
    0,/*EaPageNumber*/
    0xff,/*EaNumberOfWriteCycles*/
    EA_BLOCK_MODFIED
  },
  {/*Block 43*/
    8,/*EaBlockSize*/
    0,/*EaPageNumber*/
    0xff,/*EaNumberOfWriteCycles*/
    EA_BLOCK_MODFIED
  },
  {/*Block 44*/
    8,/*EaBlockSize*/
    0,/*EaPageNumber*/
    0xff,/*EaNumberOfWriteCycles*/
    EA_BLOCK_MODFIED
  },
  {/*Block 45*/
    8,/*EaBlockSize*/
    0,/*EaPageNumber*/
    0xff,/*EaNumberOfWriteCycles*/
    EA_BLOCK_MODFIED
  },
  {/*Block 46*/
    8,/*EaBlockSize*/
    0,/*EaPageNumber*/
    0xff,/*EaNumberOfWriteCycles*/
    EA_BLOCK_MODFIED
  },
  {/*Block 47*/
    8,/*EaBlockSize*/
    0,/*EaPageNumber*/
    0xff,/*EaNumberOfWriteCycles*/
    EA_BLOCK_MODFIED
  },
  {/*Block 48*/
    8,/*EaBlockSize*/
    0,/*EaPageNumber*/
    0xff,/*EaNumberOfWriteCycles*/
    EA_BLOCK_MODFIED
  },
  {/*Block 49*/
    8,/*EaBlockSize*/
    0,/*EaPageNumber*/
    0xff,/*EaNumberOfWriteCycles*/
    EA_BLOCK_MODFIED
  },
  {/*Block 50*/
    8,/*EaBlockSize*/
    0,/*EaPageNumber*/
    0xff,/*EaNumberOfWriteCycles*/
    EA_BLOCK_MODFIED
  },
  {/*Block 51*/
    9,/*EaBlockSize*/
    0,/*EaPageNumber*/
    0xff,/*EaNumberOfWriteCycles*/
    EA_BLOCK_MODFIED
  },
  {/*Block 52*/
    9,/*EaBlockSize*/
    0,/*EaPageNumber*/
    0xff,/*EaNumberOfWriteCycles*/
    EA_BLOCK_MODFIED
  },
  {/*Block 53*/
    9,/*EaBlockSize*/
    0,/*EaPageNumber*/
    0xff,/*EaNumberOfWriteCycles*/
    EA_BLOCK_MODFIED
  },
  {/*Block 54*/
    9,/*EaBlockSize*/
    0,/*EaPageNumber*/
    0xff,/*EaNumberOfWriteCycles*/
    EA_BLOCK_MODFIED
  },
  {/*Block 55*/
    9,/*EaBlockSize*/
    0,/*EaPageNumber*/
    0xff,/*EaNumberOfWriteCycles*/
    EA_BLOCK_MODFIED
  },
  {/*Block 56*/
    9,/*EaBlockSize*/
    0,/*EaPageNumber*/
    0xff,/*EaNumberOfWriteCycles*/
    EA_BLOCK_MODFIED
  },
  {/*Block 57*/
    9,/*EaBlockSize*/
    0,/*EaPageNumber*/
    0xff,/*EaNumberOfWriteCycles*/
    EA_BLOCK_MODFIED
  },
  {/*Block 58*/
    9,/*EaBlockSize*/
    0,/*EaPageNumber*/
    0xff,/*EaNumberOfWriteCycles*/
    EA_BLOCK_MODFIED
  },
  {/*Block 59*/
    9,/*EaBlockSize*/
    0,/*EaPageNumber*/
    0xff,/*EaNumberOfWriteCycles*/
    EA_BLOCK_MODFIED
  },
  {/*Block 60*/
    9,/*EaBlockSize*/
    0,/*EaPageNumber*/
    0xff,/*EaNumberOfWriteCycles*/
    EA_BLOCK_MODFIED
  },
  {/*Block 61*/
    9,/*EaBlockSize*/
    0,/*EaPageNumber*/
    0xff,/*EaNumberOfWriteCycles*/
    EA_BLOCK_MODFIED
  },
  {/*Block 62*/
    9,/*EaBlockSize*/
    0,/*EaPageNumber*/
    0xff,/*EaNumberOfWriteCycles*/
    EA_BLOCK_MODFIED
  },
  {/*Block 63*/
    9,/*EaBlockSize*/
    0,/*EaPageNumber*/
    0xff,/*EaNumberOfWriteCycles*/
    EA_BLOCK_MODFIED
  },
  {/*Block 64*/
    9,/*EaBlockSize*/
    0,/*EaPageNumber*/
    0xff,/*EaNumberOfWriteCycles*/
    EA_BLOCK_MODFIED
  },
  {/*Block 65*/
    9,/*EaBlockSize*/
    0,/*EaPageNumber*/
    0xff,/*EaNumberOfWriteCycles*/
    EA_BLOCK_MODFIED
  },
  {/*Block 66*/
    8,/*EaBlockSize*/
    0,/*EaPageNumber*/
    0xff,/*EaNumberOfWriteCycles*/
    EA_BLOCK_MODFIED
  },
  {/*Block 67*/
    8,/*EaBlockSize*/
    0,/*EaPageNumber*/
    0xff,/*EaNumberOfWriteCycles*/
    EA_BLOCK_MODFIED
  },
  {/*Block 68*/
    8,/*EaBlockSize*/
    0,/*EaPageNumber*/
    0xff,/*EaNumberOfWriteCycles*/
    EA_BLOCK_MODFIED
  },
  {/*Block 69*/
    8,/*EaBlockSize*/
    0,/*EaPageNumber*/
    0xff,/*EaNumberOfWriteCycles*/
    EA_BLOCK_MODFIED
  },
  {/*Block 70*/
    8,/*EaBlockSize*/
    0,/*EaPageNumber*/
    0xff,/*EaNumberOfWriteCycles*/
    EA_BLOCK_MODFIED
  },
  {/*Block 71*/
    8,/*EaBlockSize*/
    0,/*EaPageNumber*/
    0xff,/*EaNumberOfWriteCycles*/
    EA_BLOCK_MODFIED
  },
  {/*Block 72*/
    8,/*EaBlockSize*/
    0,/*EaPageNumber*/
    0xff,/*EaNumberOfWriteCycles*/
    EA_BLOCK_MODFIED
  },
  {/*Block 73*/
    8,/*EaBlockSize*/
    0,/*EaPageNumber*/
    0xff,/*EaNumberOfWriteCycles*/
    EA_BLOCK_MODFIED
  },
  {/*Block 74*/
    8,/*EaBlockSize*/
    0,/*EaPageNumber*/
    0xff,/*EaNumberOfWriteCycles*/
    EA_BLOCK_MODFIED
  },
  {/*Block 75*/
    8,/*EaBlockSize*/
    0,/*EaPageNumber*/
    0xff,/*EaNumberOfWriteCycles*/
    EA_BLOCK_MODFIED
  },
  {/*Block 76*/
    8,/*EaBlockSize*/
    0,/*EaPageNumber*/
    0xff,/*EaNumberOfWriteCycles*/
    EA_BLOCK_MODFIED
  },
  {/*Block 77*/
    8,/*EaBlockSize*/
    0,/*EaPageNumber*/
    0xff,/*EaNumberOfWriteCycles*/
    EA_BLOCK_MODFIED
  },
  {/*Block 78*/
    8,/*EaBlockSize*/
    0,/*EaPageNumber*/
    0xff,/*EaNumberOfWriteCycles*/
    EA_BLOCK_MODFIED
  },
  {/*Block 79*/
    8,/*EaBlockSize*/
    0,/*EaPageNumber*/
    0xff,/*EaNumberOfWriteCycles*/
    EA_BLOCK_MODFIED
  },
  {/*Block 80*/
    8,/*EaBlockSize*/
    0,/*EaPageNumber*/
    0xff,/*EaNumberOfWriteCycles*/
    EA_BLOCK_MODFIED
  },
  {/*Block 81*/
    5,/*EaBlockSize*/
    0,/*EaPageNumber*/
    0xff,/*EaNumberOfWriteCycles*/
    EA_BLOCK_MODFIED
  },
  {/*Block 82*/
    5,/*EaBlockSize*/
    0,/*EaPageNumber*/
    0xff,/*EaNumberOfWriteCycles*/
    EA_BLOCK_MODFIED
  },
  {/*Block 83*/
    5,/*EaBlockSize*/
    0,/*EaPageNumber*/
    0xff,/*EaNumberOfWriteCycles*/
    EA_BLOCK_MODFIED
  },
  {/*Block 84*/
    5,/*EaBlockSize*/
    0,/*EaPageNumber*/
    0xff,/*EaNumberOfWriteCycles*/
    EA_BLOCK_MODFIED
  },
  {/*Block 85*/
    5,/*EaBlockSize*/
    0,/*EaPageNumber*/
    0xff,/*EaNumberOfWriteCycles*/
    EA_BLOCK_MODFIED
  },
  {/*Block 86*/
    5,/*EaBlockSize*/
    0,/*EaPageNumber*/
    0xff,/*EaNumberOfWriteCycles*/
    EA_BLOCK_MODFIED
  },
  {/*Block 87*/
    5,/*EaBlockSize*/
    0,/*EaPageNumber*/
    0xff,/*EaNumberOfWriteCycles*/
    EA_BLOCK_MODFIED
  },
  {/*Block 88*/
    5,/*EaBlockSize*/
    0,/*EaPageNumber*/
    0xff,/*EaNumberOfWriteCycles*/
    EA_BLOCK_MODFIED
  },
  {/*Block 89*/
    5,/*EaBlockSize*/
    0,/*EaPageNumber*/
    0xff,/*EaNumberOfWriteCycles*/
    EA_BLOCK_MODFIED
  },
  {/*Block 90*/
    5,/*EaBlockSize*/
    0,/*EaPageNumber*/
    0xff,/*EaNumberOfWriteCycles*/
    EA_BLOCK_MODFIED
  },
  {/*Block 91*/
    8,/*EaBlockSize*/
    0,/*EaPageNumber*/
    0xff,/*EaNumberOfWriteCycles*/
    EA_BLOCK_MODFIED
  },
  {/*Block 92*/
    8,/*EaBlockSize*/
    0,/*EaPageNumber*/
    0xff,/*EaNumberOfWriteCycles*/
    EA_BLOCK_MODFIED
  },
  {/*Block 93*/
    8,/*EaBlockSize*/
    0,/*EaPageNumber*/
    0xff,/*EaNumberOfWriteCycles*/
    EA_BLOCK_MODFIED
  },
  {/*Block 94*/
    8,/*EaBlockSize*/
    0,/*EaPageNumber*/
    0xff,/*EaNumberOfWriteCycles*/
    EA_BLOCK_MODFIED
  },
  {/*Block 95*/
    8,/*EaBlockSize*/
    0,/*EaPageNumber*/
    0xff,/*EaNumberOfWriteCycles*/
    EA_BLOCK_MODFIED
  },
  {/*Block 96*/
    8,/*EaBlockSize*/
    0,/*EaPageNumber*/
    0xff,/*EaNumberOfWriteCycles*/
    EA_BLOCK_MODFIED
  },
  {/*Block 97*/
    8,/*EaBlockSize*/
    0,/*EaPageNumber*/
    0xff,/*EaNumberOfWriteCycles*/
    EA_BLOCK_MODFIED
  },
  {/*Block 98*/
    8,/*EaBlockSize*/
    0,/*EaPageNumber*/
    0xff,/*EaNumberOfWriteCycles*/
    EA_BLOCK_MODFIED
  },
  {/*Block 99*/
    8,/*EaBlockSize*/
    0,/*EaPageNumber*/
    0xff,/*EaNumberOfWriteCycles*/
    EA_BLOCK_MODFIED
  },
  {/*Block 100*/
    8,/*EaBlockSize*/
    0,/*EaPageNumber*/
    0xff,/*EaNumberOfWriteCycles*/
    EA_BLOCK_MODFIED
  },
  {/*Block 101*/
    18,/*EaBlockSize*/
    0,/*EaPageNumber*/
    0xff,/*EaNumberOfWriteCycles*/
    EA_BLOCK_MODFIED
  },
  {/*Block 102*/
    10,/*EaBlockSize*/
    0,/*EaPageNumber*/
    0xff,/*EaNumberOfWriteCycles*/
    EA_BLOCK_MODFIED
  },
  {/*Block 103*/
    9,/*EaBlockSize*/
    0,/*EaPageNumber*/
    0xff,/*EaNumberOfWriteCycles*/
    EA_BLOCK_MODFIED
  },
  {/*Block 104*/
    42,/*EaBlockSize*/
    0,/*EaPageNumber*/
    0xff,/*EaNumberOfWriteCycles*/
    EA_BLOCK_MODFIED
  },
  {/*Block 105*/
    42,/*EaBlockSize*/
    0,/*EaPageNumber*/
    0xff,/*EaNumberOfWriteCycles*/
    EA_BLOCK_MODFIED
  },
  {/*Block 106*/
    42,/*EaBlockSize*/
    0,/*EaPageNumber*/
    0xff,/*EaNumberOfWriteCycles*/
    EA_BLOCK_MODFIED
  },
  {/*Block 107*/
    42,/*EaBlockSize*/
    0,/*EaPageNumber*/
    0xff,/*EaNumberOfWriteCycles*/
    EA_BLOCK_MODFIED
  },
  {/*Block 108*/
    42,/*EaBlockSize*/
    0,/*EaPageNumber*/
    0xff,/*EaNumberOfWriteCycles*/
    EA_BLOCK_MODFIED
  },
  {/*Block 109*/
    42,/*EaBlockSize*/
    0,/*EaPageNumber*/
    0xff,/*EaNumberOfWriteCycles*/
    EA_BLOCK_MODFIED
  },
  {/*Block 110*/
    42,/*EaBlockSize*/
    0,/*EaPageNumber*/
    0xff,/*EaNumberOfWriteCycles*/
    EA_BLOCK_MODFIED
  },
  {/*Block 111*/
    42,/*EaBlockSize*/
    0,/*EaPageNumber*/
    0xff,/*EaNumberOfWriteCycles*/
    EA_BLOCK_MODFIED
  },
  {/*Block 112*/
    42,/*EaBlockSize*/
    0,/*EaPageNumber*/
    0xff,/*EaNumberOfWriteCycles*/
    EA_BLOCK_MODFIED
  },
  {/*Block 113*/
    42,/*EaBlockSize*/
    0,/*EaPageNumber*/
    0xff,/*EaNumberOfWriteCycles*/
    EA_BLOCK_MODFIED
  },
  {/*Block 114*/
    42,/*EaBlockSize*/
    0,/*EaPageNumber*/
    0xff,/*EaNumberOfWriteCycles*/
    EA_BLOCK_MODFIED
  },
  {/*Block 115*/
    34,/*EaBlockSize*/
    0,/*EaPageNumber*/
    0xff,/*EaNumberOfWriteCycles*/
    EA_BLOCK_MODFIED
  },
  {/*Block 116*/
    3,/*EaBlockSize*/
    0,/*EaPageNumber*/
    0xff,/*EaNumberOfWriteCycles*/
    EA_BLOCK_MODFIED
  },
  {/*Block 117*/
    34,/*EaBlockSize*/
    0,/*EaPageNumber*/
    0xff,/*EaNumberOfWriteCycles*/
    EA_BLOCK_MODFIED
  },
  {/*Block 118*/
    5,/*EaBlockSize*/
    0,/*EaPageNumber*/
    0xff,/*EaNumberOfWriteCycles*/
    EA_BLOCK_MODFIED
  },
  {/*Block 119*/
    5,/*EaBlockSize*/
    0,/*EaPageNumber*/
    0xff,/*EaNumberOfWriteCycles*/
    EA_BLOCK_MODFIED
  },
  {/*Block 120*/
    5,/*EaBlockSize*/
    0,/*EaPageNumber*/
    0xff,/*EaNumberOfWriteCycles*/
    EA_BLOCK_MODFIED
  },
  {/*Block 121*/
    5,/*EaBlockSize*/
    0,/*EaPageNumber*/
    0xff,/*EaNumberOfWriteCycles*/
    EA_BLOCK_MODFIED
  },
  {/*Block 122*/
    5,/*EaBlockSize*/
    0,/*EaPageNumber*/
    0xff,/*EaNumberOfWriteCycles*/
    EA_BLOCK_MODFIED
  },
  {/*Block 123*/
    5,/*EaBlockSize*/
    0,/*EaPageNumber*/
    0xff,/*EaNumberOfWriteCycles*/
    EA_BLOCK_MODFIED
  },
  {/*Block 124*/
    5,/*EaBlockSize*/
    0,/*EaPageNumber*/
    0xff,/*EaNumberOfWriteCycles*/
    EA_BLOCK_MODFIED
  },
  {/*Block 125*/
    5,/*EaBlockSize*/
    0,/*EaPageNumber*/
    0xff,/*EaNumberOfWriteCycles*/
    EA_BLOCK_MODFIED
  },
  {/*Block 126*/
    5,/*EaBlockSize*/
    0,/*EaPageNumber*/
    0xff,/*EaNumberOfWriteCycles*/
    EA_BLOCK_MODFIED
  },
  {/*Block 127*/
    5,/*EaBlockSize*/
    0,/*EaPageNumber*/
    0xff,/*EaNumberOfWriteCycles*/
    EA_BLOCK_MODFIED
  },
  {/*Block 128*/
    5,/*EaBlockSize*/
    0,/*EaPageNumber*/
    0xff,/*EaNumberOfWriteCycles*/
    EA_BLOCK_MODFIED
  },
  {/*Block 129*/
    5,/*EaBlockSize*/
    0,/*EaPageNumber*/
    0xff,/*EaNumberOfWriteCycles*/
    EA_BLOCK_MODFIED
  },
  {/*Block 130*/
    5,/*EaBlockSize*/
    0,/*EaPageNumber*/
    0xff,/*EaNumberOfWriteCycles*/
    EA_BLOCK_MODFIED
  },
  {/*Block 131*/
    5,/*EaBlockSize*/
    0,/*EaPageNumber*/
    0xff,/*EaNumberOfWriteCycles*/
    EA_BLOCK_MODFIED
  },
  {/*Block 132*/
    8,/*EaBlockSize*/
    0,/*EaPageNumber*/
    0xff,/*EaNumberOfWriteCycles*/
    EA_BLOCK_MODFIED
  },
  {/*Block 133*/
    8,/*EaBlockSize*/
    0,/*EaPageNumber*/
    0xff,/*EaNumberOfWriteCycles*/
    EA_BLOCK_MODFIED
  },
  {/*Block 134*/
    8,/*EaBlockSize*/
    0,/*EaPageNumber*/
    0xff,/*EaNumberOfWriteCycles*/
    EA_BLOCK_MODFIED
  },
  {/*Block 135*/
    8,/*EaBlockSize*/
    0,/*EaPageNumber*/
    0xff,/*EaNumberOfWriteCycles*/
    EA_BLOCK_MODFIED
  },
  {/*Block 136*/
    8,/*EaBlockSize*/
    0,/*EaPageNumber*/
    0xff,/*EaNumberOfWriteCycles*/
    EA_BLOCK_MODFIED
  },
  {/*Block 137*/
    8,/*EaBlockSize*/
    0,/*EaPageNumber*/
    0xff,/*EaNumberOfWriteCycles*/
    EA_BLOCK_MODFIED
  },
  {/*Block 138*/
    8,/*EaBlockSize*/
    0,/*EaPageNumber*/
    0xff,/*EaNumberOfWriteCycles*/
    EA_BLOCK_MODFIED
  },
  {/*Block 139*/
    8,/*EaBlockSize*/
    0,/*EaPageNumber*/
    0xff,/*EaNumberOfWriteCycles*/
    EA_BLOCK_MODFIED
  },
  {/*Block 140*/
    8,/*EaBlockSize*/
    0,/*EaPageNumber*/
    0xff,/*EaNumberOfWriteCycles*/
    EA_BLOCK_MODFIED
  },
  {/*Block 141*/
    8,/*EaBlockSize*/
    0,/*EaPageNumber*/
    0xff,/*EaNumberOfWriteCycles*/
    EA_BLOCK_MODFIED
  },
  {/*Block 142*/
    8,/*EaBlockSize*/
    0,/*EaPageNumber*/
    0xff,/*EaNumberOfWriteCycles*/
    EA_BLOCK_MODFIED
  },
  {/*Block 143*/
    8,/*EaBlockSize*/
    0,/*EaPageNumber*/
    0xff,/*EaNumberOfWriteCycles*/
    EA_BLOCK_MODFIED
  },
  {/*Block 144*/
    8,/*EaBlockSize*/
    0,/*EaPageNumber*/
    0xff,/*EaNumberOfWriteCycles*/
    EA_BLOCK_MODFIED
  },
  {/*Block 145*/
    8,/*EaBlockSize*/
    0,/*EaPageNumber*/
    0xff,/*EaNumberOfWriteCycles*/
    EA_BLOCK_MODFIED
  },

};
const uint16 EA_BLOCK_NUM_ALL = 145;
/*** Generation data:2020-02-17 11:10 ***/
/*** The above lines is generated by tool ***/
/*** End , DO NOT MODIFY THIS TEXT!!! ***/

