/*!Warning!:Please don't modify this file,this is generated by tools!*/
/********************************************************************
File name: Com_Cbk.h
Author: Stephen Du
Version: V1.0
Timestamp: 2017-12-29 10:56:31
Description:
Others:
Function List:
1. ....
History: /
1. Date:
Author:
Modification:
2. ...
********************************************************************/
#ifndef _COM_CBK_H_
#define _COM_CBK_H_

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus
/*===============================================================================*/
/*=========================== START: HEAD FILE INCLUDE ==========================*/
/*===============================================================================*/
#include "ComStack_Types.h"

/*===============================================================================*/
/*============================ END: HEAD FILE INCLUDE ===========================*/
/*===============================================================================*/
extern void Com_RxIndication(PduIdType ComRxPduId, const PduInfoType* PduInfoPtr);
extern void Com_TxConfirmation(PduIdType ComTxPduId);
extern void Com_TxErrorCallBack(PduIdType ComTxPduId);

extern void Com_RxSTimeout_0X70_AVM_070(void);
extern void Com_RxLTimeout_0X70_AVM_070(void);
extern void Com_RxIndicate_0X70_AVM_070(void);

extern void Com_RxSTimeout_0X300_SAS_300(void);
extern void Com_RxLTimeout_0X300_SAS_300(void);
extern void Com_RxIndicate_0X300_SAS_300(void);

extern void Com_RxSTimeout_0X320_BCM_320(void);
extern void Com_RxLTimeout_0X320_BCM_320(void);
extern void Com_RxIndicate_0X320_BCM_320(void);

extern void Com_RxSTimeout_0X326_TCU_326(void);
extern void Com_RxLTimeout_0X326_TCU_326(void);
extern void Com_RxIndicate_0X326_TCU_326(void);

extern void Com_RxSTimeout_0X328_CVT_TCU_328(void);
extern void Com_RxLTimeout_0X328_CVT_TCU_328(void);
extern void Com_RxIndicate_0X328_CVT_TCU_328(void);

extern void Com_RxSTimeout_0X330_ABS_330(void);
extern void Com_RxLTimeout_0X330_ABS_330(void);
extern void Com_RxIndicate_0X330_ABS_330(void);

extern void Com_RxSTimeout_0X340_BCM_340(void);
extern void Com_RxLTimeout_0X340_BCM_340(void);
extern void Com_RxIndicate_0X340_BCM_340(void);

extern void Com_RxSTimeout_0X350_BCM_350(void);
extern void Com_RxLTimeout_0X350_BCM_350(void);
extern void Com_RxIndicate_0X350_BCM_350(void);

extern void Com_RxSTimeout_0X378_AC_378(void);
extern void Com_RxLTimeout_0X378_AC_378(void);
extern void Com_RxIndicate_0X378_AC_378(void);

extern void Com_RxSTimeout_0X391_AVM_391(void);
extern void Com_RxLTimeout_0X391_AVM_391(void);
extern void Com_RxIndicate_0X391_AVM_391(void);

extern void Com_TxTimeout_0X60_RRM_060(void);
extern void Com_TxNotify_0X60_RRM_060(void);
extern void Com_TxError_0X60_RRM_060(void);

extern void Com_TxTimeout_0X85_RRM_085(void);
extern void Com_TxNotify_0X85_RRM_085(void);
extern void Com_TxError_0X85_RRM_085(void);

extern void Com_TxTimeout_0X393_RRM_393(void);
extern void Com_TxNotify_0X393_RRM_393(void);
extern void Com_TxError_0X393_RRM_393(void);

extern void Com_TxTimeout_0X394_RRM_394(void);
extern void Com_TxNotify_0X394_RRM_394(void);
extern void Com_TxError_0X394_RRM_394(void);

extern void Com_TxTimeout_0X395_RRM_395(void);
extern void Com_TxNotify_0X395_RRM_395(void);
extern void Com_TxError_0X395_RRM_395(void);

extern void Com_TxTimeout_0X397_RRM_397(void);
extern void Com_TxNotify_0X397_RRM_397(void);
extern void Com_TxError_0X397_RRM_397(void);

/*===============================================================================*/
/*============================ END: FUNC PROTYPE API ============================*/
/*===============================================================================*/
#ifdef __cplusplus
}
#endif // __cplusplus

#endif

/*============================= END OF FILE: Com_Cbk.h ==========================*/
