/*!Warning!:Please don't modify this file,this is generated by tools!*/
/********************************************************************
File name: Com_Cfg.h
Author: Stephen Du
Version: V1.0
Timestamp: 2017-12-29 10:56:31
Description:
Others:
Function List:
1. ....
History: /
1. Date:
Author:
Modification:
2. ...
********************************************************************/
#ifndef _COM_CFG_H_
#define _COM_CFG_H_

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus
/*===============================================================================*/
/*=========================== START: HEAD FILE INCLUDE ==========================*/
/*===============================================================================*/
#include "ComStack_Types.h"

/*===============================================================================*/
/*============================ END: HEAD FILE INCLUDE ===========================*/
/*===============================================================================*/

/*===============================================================================*/
/*========================== START: GLOBAL MACRO DEFINE =========================*/
/*===============================================================================*/
#define COM_DEV_ERROR_DETECT STD_OFF

#define COM_CONFIGURATION_ID (1712291055)

#define COM_CONFIGURATION_TIMEBASE (5U)//minimum delay time

#define USE_RX_SIG_FILTER STD_ON
#define USE_TX_SIG_FILTER STD_ON

//#define COM_INTERNAL_COMMUNICATON
#define COM_RX_TEMP_BUFFER_SIZE (8U)

/*===============================================================================*/
/*=========================== END: GLOBAL MACRO DEFINE ==========================*/
/*===============================================================================*/

/*===============================================================================*/
/*============================ START: IPDU HANDLE ===============================*/
/*===============================================================================*/
/******************************* Rx IPDU HANDLE **********************************/
/*MessageID: 0X70   MessageName: AVM_070   CycTime: 0mS*/
#define IPDU_HND_AVM_070 (0U)

/*MessageID: 0X300   MessageName: SAS_300   CycTime: 10mS*/
#define IPDU_HND_SAS_300 (1U)

/*MessageID: 0X320   MessageName: BCM_320   CycTime: 10mS*/
#define IPDU_HND_BCM_320 (2U)

/*MessageID: 0X326   MessageName: TCU_326   CycTime: 10mS*/
#define IPDU_HND_TCU_326 (3U)

/*MessageID: 0X328   MessageName: CVT_TCU_328   CycTime: 10mS*/
#define IPDU_HND_CVT_TCU_328 (4U)

/*MessageID: 0X330   MessageName: ABS_330   CycTime: 20mS*/
#define IPDU_HND_ABS_330 (5U)

/*MessageID: 0X340   MessageName: BCM_340   CycTime: 20mS*/
#define IPDU_HND_BCM_340 (6U)

/*MessageID: 0X350   MessageName: BCM_350   CycTime: 40mS*/
#define IPDU_HND_BCM_350 (7U)

/*MessageID: 0X378   MessageName: AC_378   CycTime: 100mS*/
#define IPDU_HND_AC_378 (8U)

/*MessageID: 0X391   MessageName: AVM_391   CycTime: 500mS*/
#define IPDU_HND_AVM_391 (9U)

#define COM_RX_IPDU_MAX_NUM (10U)
#define COM_TX_IPDU_START_INDEX (10U)

/******************************* Tx IPDU HANDLE **********************************/
/*MessageID: 0X60   MessageName: RRM_060   CycTime: 0mS*/
#define IPDU_HND_RRM_060 (10U)

/*MessageID: 0X85   MessageName: RRM_085   CycTime: 0mS*/
#define IPDU_HND_RRM_085 (11U)

/*MessageID: 0X393   MessageName: RRM_393   CycTime: 100mS*/
#define IPDU_HND_RRM_393 (12U)

/*MessageID: 0X394   MessageName: RRM_394   CycTime: 100mS*/
#define IPDU_HND_RRM_394 (13U)

/*MessageID: 0X395   MessageName: RRM_395   CycTime: 0mS*/
#define IPDU_HND_RRM_395 (14U)

/*MessageID: 0X397   MessageName: RRM_397   CycTime: 500mS*/
#define IPDU_HND_RRM_397 (15U)

#define COM_TX_IPDU_MAX_NUM (6U)
#define COM_IPDU_MAX_NUM (16U)

/*===============================================================================*/
/*============================== END: IPDU HANDLE ===============================*/
/*===============================================================================*/

/*===============================================================================*/
/*========================== START: IPDU GROUP HANDLE ===========================*/
/*===============================================================================*/
/***************************** Rx IPDU GROUP HANDLE ******************************/
#define RX_IPDU_GROUP_HND_Default (0U)

#define COM_RX_IPDUGROUP_MAX_NUM (1U)

#define COM_TX_IPDUGROUP_START_INDEX COM_RX_IPDUGROUP_MAX_NUM
/***************************** Tx IPDU GROUP HANDLE ******************************/
#define TX_IPDU_GROUP_HND_Default (1U)

#define COM_TX_IPDUGROUP_MAX_NUM (1U)
#define COM_IPDUGROUP_MAX_NUM (2U)
/*===============================================================================*/
/*========================== END: IPDU GROUP HANDLE =============================*/
/*===============================================================================*/

/*===============================================================================*/
/*============================ START: SIGNAL HANDLE =============================*/
/*===============================================================================*/
/****************************** Rx Signal Handle *********************************/
/*********************************************************************************/
/*MessageID: 0X70   MessageHandle: IPDU_HND_AVM_070   CycTime: 0mS*/
/*SignalName: calibration_state
  Endian:Motor  Type:Uint8  StartBit:3  Length:4*/
#define SIG_HND_calibration_state (0U)

/*SignalName: AVM_cali_time_request
  Endian:Motor  Type:Boolean  StartBit:4  Length:1*/
#define SIG_HND_AVM_cali_time_request (1U)

/*SignalName: front_cam_cali_fault
  Endian:Motor  Type:Boolean  StartBit:8  Length:1*/
#define SIG_HND_front_cam_cali_fault (2U)

/*SignalName: rear_cam_cali_fault
  Endian:Motor  Type:Boolean  StartBit:9  Length:1*/
#define SIG_HND_rear_cam_cali_fault (3U)

/*SignalName: lest_cam_cali_fault
  Endian:Motor  Type:Boolean  StartBit:10  Length:1*/
#define SIG_HND_lest_cam_cali_fault (4U)

/*SignalName: right_cam_cali_fault
  Endian:Motor  Type:Boolean  StartBit:11  Length:1*/
#define SIG_HND_right_cam_cali_fault (5U)

/*********************************************************************************/

/*********************************************************************************/
/*MessageID: 0X300   MessageHandle: IPDU_HND_SAS_300   CycTime: 10mS*/
/*SignalName: steering_angle
  Endian:Motor  Type:Uint16  StartBit:31  Length:16*/
#define SIG_HND_steering_angle (6U)

/*********************************************************************************/

/*********************************************************************************/
/*MessageID: 0X320   MessageHandle: IPDU_HND_BCM_320   CycTime: 10mS*/
/*SignalName: BCM_ReverseGearSwitchStatus
  Endian:Motor  Type:Boolean  StartBit:0  Length:1*/
#define SIG_HND_BCM_ReverseGearSwitchStatus (7U)

/*********************************************************************************/

/*********************************************************************************/
/*MessageID: 0X326   MessageHandle: IPDU_HND_TCU_326   CycTime: 10mS*/
/*SignalName: AT_ShiftPositionValid
  Endian:Motor  Type:Boolean  StartBit:4  Length:1*/
#define SIG_HND_AT_ShiftPositionValid (8U)

/*SignalName: AT_GearShiftPosition
  Endian:Motor  Type:Uint8  StartBit:15  Length:4*/
#define SIG_HND_AT_GearShiftPosition (9U)

/*********************************************************************************/

/*********************************************************************************/
/*MessageID: 0X328   MessageHandle: IPDU_HND_CVT_TCU_328   CycTime: 10mS*/
/*SignalName: TCU_Gear_Position_Status
  Endian:Motor  Type:Uint8  StartBit:3  Length:4*/
#define SIG_HND_TCU_Gear_Position_Status (10U)

/*SignalName: TCU_Gear_Position_VD
  Endian:Motor  Type:Boolean  StartBit:4  Length:1*/
#define SIG_HND_TCU_Gear_Position_VD (11U)

/*********************************************************************************/

/*********************************************************************************/
/*MessageID: 0X330   MessageHandle: IPDU_HND_ABS_330   CycTime: 20mS*/
/*SignalName: vehicle_speed
  Endian:Motor  Type:Uint16  StartBit:4  Length:13*/
#define SIG_HND_vehicle_speed (12U)

/*SignalName: ABS_Vehicle_speed_valid
  Endian:Motor  Type:Boolean  StartBit:16  Length:1*/
#define SIG_HND_ABS_Vehicle_speed_valid (13U)

/*********************************************************************************/

/*********************************************************************************/
/*MessageID: 0X340   MessageHandle: IPDU_HND_BCM_340   CycTime: 20mS*/
/*SignalName: BCM_SmallLampSwitchStatus
  Endian:Motor  Type:Boolean  StartBit:0  Length:1*/
#define SIG_HND_BCM_SmallLampSwitchStatus (14U)

/*********************************************************************************/

/*********************************************************************************/
/*MessageID: 0X350   MessageHandle: IPDU_HND_BCM_350   CycTime: 40mS*/
/*SignalName: BCM_TurnIndicatorLeft
  Endian:Motor  Type:Uint8  StartBit:9  Length:2*/
#define SIG_HND_BCM_TurnIndicatorLeft (15U)

/*SignalName: BCM_TurnIndicatorRight
  Endian:Motor  Type:Uint8  StartBit:11  Length:2*/
#define SIG_HND_BCM_TurnIndicatorRight (16U)

/*SignalName: Handbrakesignal
  Endian:Motor  Type:Uint8  StartBit:21  Length:2*/
#define SIG_HND_Handbrakesignal (17U)

/*********************************************************************************/

/*********************************************************************************/
/*MessageID: 0X378   MessageHandle: IPDU_HND_AC_378   CycTime: 100mS*/
/*SignalName: AcReq
  Endian:Motor  Type:Boolean  StartBit:12  Length:1*/
#define SIG_HND_AcReq (18U)

/*SignalName: AcReqValid
  Endian:Motor  Type:Boolean  StartBit:13  Length:1*/
#define SIG_HND_AcReqValid (19U)

/*SignalName: RearDefrostReq
  Endian:Motor  Type:Boolean  StartBit:20  Length:1*/
#define SIG_HND_RearDefrostReq (20U)

/*SignalName: RearDefrostReqValid
  Endian:Motor  Type:Boolean  StartBit:21  Length:1*/
#define SIG_HND_RearDefrostReqValid (21U)

/*SignalName: DisplayActive
  Endian:Motor  Type:Boolean  StartBit:22  Length:1*/
#define SIG_HND_DisplayActive (22U)

/*SignalName: AcMaxMode
  Endian:Motor  Type:Boolean  StartBit:23  Length:1*/
#define SIG_HND_AcMaxMode (23U)

/*SignalName: SetTemperature
  Endian:Motor  Type:Uint8  StartBit:30  Length:7*/
#define SIG_HND_SetTemperature (24U)

/*SignalName: BlowerSpeedLevel
  Endian:Motor  Type:Uint8  StartBit:35  Length:4*/
#define SIG_HND_BlowerSpeedLevel (25U)

/*SignalName: AirDistrbuteMode
  Endian:Motor  Type:Uint8  StartBit:38  Length:3*/
#define SIG_HND_AirDistrbuteMode (26U)

/*SignalName: DefrostMode
  Endian:Motor  Type:Boolean  StartBit:39  Length:1*/
#define SIG_HND_DefrostMode (27U)

/*SignalName: AirLetMode
  Endian:Motor  Type:Boolean  StartBit:40  Length:1*/
#define SIG_HND_AirLetMode (28U)

/*SignalName: AutoMode
  Endian:Motor  Type:Boolean  StartBit:41  Length:1*/
#define SIG_HND_AutoMode (29U)

/*SignalName: OnOffState
  Endian:Motor  Type:Boolean  StartBit:42  Length:1*/
#define SIG_HND_OnOffState (30U)

/*SignalName: RearMode
  Endian:Motor  Type:Boolean  StartBit:43  Length:1*/
#define SIG_HND_RearMode (31U)

/*********************************************************************************/

/*********************************************************************************/
/*MessageID: 0X391   MessageHandle: IPDU_HND_AVM_391   CycTime: 500mS*/
/*SignalName: main_version
  Endian:Motor  Type:Uint8  StartBit:7  Length:8*/
#define SIG_HND_main_version (32U)

/*SignalName: sub_version
  Endian:Motor  Type:Uint8  StartBit:15  Length:8*/
#define SIG_HND_sub_version (33U)

/*SignalName: AVM_activation_state
  Endian:Motor  Type:Boolean  StartBit:16  Length:1*/
#define SIG_HND_AVM_activation_state (34U)

/*SignalName: display_view_state
  Endian:Motor  Type:Uint8  StartBit:20  Length:4*/
#define SIG_HND_display_view_state (35U)

/*********************************************************************************/

#define COM_RX_SIGNAL_MAX_NUM (36U)

#define COM_TX_SIGNAL_START_INDEX COM_RX_SIGNAL_MAX_NUM

/******************************** Tx Signal Handle *******************************/
/*********************************************************************************/
/*MessageID: 0X60   MessageHandle: IPDU_HND_RRM_060   CycTime: 0mS*/
/*SignalName: Calibrate_start
  Endian:Motor  Type:Uint32  StartBit:7  Length:32*/
#define SIG_HND_Calibrate_start (36U)

/*SignalName: cali_info_req
  Endian:Motor  Type:Boolean  StartBit:32  Length:1*/
#define SIG_HND_cali_info_req (37U)

/*SignalName: time_information
  Endian:Motor  Type:Uint32  StartBit:47  Length:24*/
#define SIG_HND_time_information (38U)

/*********************************************************************************/

/*********************************************************************************/
/*MessageID: 0X85   MessageHandle: IPDU_HND_RRM_085   CycTime: 0mS*/
/*SignalName: ExteriorMirrorElecFlod
  Endian:Motor  Type:Boolean  StartBit:0  Length:1*/
#define SIG_HND_ExteriorMirrorElecFlod (39U)

/*********************************************************************************/

/*********************************************************************************/
/*MessageID: 0X393   MessageHandle: IPDU_HND_RRM_393   CycTime: 100mS*/
/*SignalName: RR_Beep_Fre
  Endian:Motor  Type:Uint8  StartBit:3  Length:4*/
#define SIG_HND_RR_Beep_Fre (40U)

/*********************************************************************************/

/*********************************************************************************/
/*MessageID: 0X394   MessageHandle: IPDU_HND_RRM_394   CycTime: 100mS*/
/*SignalName: ClimateCtlByDvdReq
  Endian:Motor  Type:Boolean  StartBit:0  Length:1*/
#define SIG_HND_ClimateCtlByDvdReq (41U)

/*SignalName: AcKey
  Endian:Motor  Type:Boolean  StartBit:1  Length:1*/
#define SIG_HND_AcKey (42U)

/*SignalName: MaxAcKey
  Endian:Motor  Type:Boolean  StartBit:2  Length:1*/
#define SIG_HND_MaxAcKey (43U)

/*SignalName: AutoKey
  Endian:Motor  Type:Boolean  StartBit:3  Length:1*/
#define SIG_HND_AutoKey (44U)

/*SignalName: BlowerUpkey
  Endian:Motor  Type:Boolean  StartBit:4  Length:1*/
#define SIG_HND_BlowerUpkey (45U)

/*SignalName: BlowerDownKey
  Endian:Motor  Type:Boolean  StartBit:5  Length:1*/
#define SIG_HND_BlowerDownKey (46U)

/*SignalName: SetTempUpKey
  Endian:Motor  Type:Boolean  StartBit:6  Length:1*/
#define SIG_HND_SetTempUpKey (47U)

/*SignalName: SetTempDownKey
  Endian:Motor  Type:Boolean  StartBit:7  Length:1*/
#define SIG_HND_SetTempDownKey (48U)

/*SignalName: DefrostKey
  Endian:Motor  Type:Boolean  StartBit:8  Length:1*/
#define SIG_HND_DefrostKey (49U)

/*SignalName: AirLetKey
  Endian:Motor  Type:Boolean  StartBit:9  Length:1*/
#define SIG_HND_AirLetKey (50U)

/*SignalName: AiirDisModeKey
  Endian:Motor  Type:Uint8  StartBit:13  Length:4*/
#define SIG_HND_AiirDisModeKey (51U)

/*SignalName: RearDefrostKey
  Endian:Motor  Type:Boolean  StartBit:14  Length:1*/
#define SIG_HND_RearDefrostKey (52U)

/*SignalName: OffKey
  Endian:Motor  Type:Boolean  StartBit:15  Length:1*/
#define SIG_HND_OffKey (53U)

/*SignalName: RearKey
  Endian:Motor  Type:Boolean  StartBit:16  Length:1*/
#define SIG_HND_RearKey (54U)

/*********************************************************************************/

/*********************************************************************************/
/*MessageID: 0X395   MessageHandle: IPDU_HND_RRM_395   CycTime: 0mS*/
/*SignalName: active_command
  Endian:Motor  Type:Boolean  StartBit:0  Length:1*/
#define SIG_HND_active_command (55U)

/*SignalName: Language_state
  Endian:Motor  Type:Boolean  StartBit:1  Length:1*/
#define SIG_HND_Language_state (56U)

/*SignalName: screen_state
  Endian:Motor  Type:Boolean  StartBit:2  Length:1*/
#define SIG_HND_screen_state (57U)

/*SignalName: purpose_key
  Endian:Motor  Type:Boolean  StartBit:3  Length:1*/
#define SIG_HND_purpose_key (58U)

/*SignalName: operation_ordinate
  Endian:Motor  Type:Boolean  StartBit:4  Length:1*/
#define SIG_HND_operation_ordinate (59U)

/*SignalName: X_ordinate
  Endian:Motor  Type:Uint16  StartBit:15  Length:16*/
#define SIG_HND_X_ordinate (60U)

/*SignalName: Y_ordinate
  Endian:Motor  Type:Uint16  StartBit:31  Length:16*/
#define SIG_HND_Y_ordinate (61U)

/*********************************************************************************/

/*********************************************************************************/
/*MessageID: 0X397   MessageHandle: IPDU_HND_RRM_397   CycTime: 500mS*/
/*SignalName: cross_navi_mode
  Endian:Motor  Type:Uint8  StartBit:7  Length:8*/
#define SIG_HND_cross_navi_mode (62U)

/*SignalName: cross_navi_distance
  Endian:Motor  Type:Uint16  StartBit:15  Length:16*/
#define SIG_HND_cross_navi_distance (63U)

/*********************************************************************************/

#define COM_TX_SIGNAL_MAX_NUM (28U)

#define COM_SIGNAL_MAX_NUM (64U)

/*===============================================================================*/
/*============================== END: SIGNAL HANDLE =============================*/
/*===============================================================================*/
#ifdef __cplusplus
}
#endif // __cplusplus

#endif

/*============================= END OF FILE: Com_Cfg.h ==========================*/
