/*!Warning!:Please don't modify this file,this is generated by tools!*/
/********************************************************************
File name: Task_General_Cfg.h
Author: Stephen Du
Version: V1.0
Timestamp: 2018-08-14 10:21:02
Description:
Others:
Function List:
1. ....
History: /
1. Date:
Author:
Modification:
2. ...
********************************************************************/
#ifndef _TASK_GENERAL_CFG_H_
#define _TASK_GENERAL_CFG_H_

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

#include "Std_Types.h"

#define TASK_GENERAL_DEBUG_TRACE STD_OFF
#define TASK_GENERAL_STACK_MONITOR STD_OFF

#ifdef __cplusplus
}
#endif // __cplusplus

#endif
/*=========================== END OF FILE: Task_General_Cfg.h ===========================*/
