/* ###################################################################
**     This component module is generated by Processor Expert. Do not modify it.
**     Filename    : eim_cfg.h
**     Project     : S32K_146
**     Processor   : S32K146_144
**     Component   : eim
**     Version     : Component SDK_S32K14x_08, Driver 01.00, CPU db: 3.00.000
**     Repository  : SDK_S32K14x_08
**     Compiler    : GNU C Compiler
**     Date/Time   : 2018-05-15, 15:28, # CodeGen: 60
**     Contents    :
**         EIM_DRV_Init             - void EIM_DRV_Init(uint32_t instance, uint8_t channelCnt, const...
**         EIM_DRV_Deinit           - void EIM_DRV_Deinit(uint32_t instance);
**         EIM_DRV_ConfigChannel    - void EIM_DRV_ConfigChannel(uint32_t instance, const eim_user_channel_config_t...
**         EIM_DRV_GetChannelConfig - void EIM_DRV_GetChannelConfig(uint32_t instance, uint8_t channel,...
**         EIM_DRV_GetDefaultConfig - void EIM_DRV_GetDefaultConfig(uint8_t channel, eim_user_channel_config_t...
**
**     Copyright 1997 - 2015 Freescale Semiconductor, Inc.
**     Copyright 2016-2017 NXP
**     All Rights Reserved.
**     
**     THIS SOFTWARE IS PROVIDED BY NXP "AS IS" AND ANY EXPRESSED OR
**     IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES
**     OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
**     IN NO EVENT SHALL NXP OR ITS CONTRIBUTORS BE LIABLE FOR ANY DIRECT,
**     INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
**     (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
**     SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
**     HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT,
**     STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING
**     IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF
**     THE POSSIBILITY OF SUCH DAMAGE.
** ###################################################################*/
/*!
** @file eim_cfg.h
** @version 01.00
*/
/*!
**  @addtogroup eim_cfg_module eim_cfg module documentation
**  @{
*/
#ifndef eim_cfg_H
#define eim_cfg_H

/* MODULE eim_cfg.
 *
 * @page misra_violations MISRA-C:2012 violations
 *
 * @section [global]
 * Violates MISRA 2012 Advisory Rule 2.5, Global macro not referenced.
 * The global macro will be used in function call of the module.
 */

/* Include inherited beans */
#include "clockManager_cfg.h"
#include "Cpu.h"

/*! Device instance number */
#define INST_EIM_CFG (0U)

/*! The number of configured channels */
#define EIM_CHANNEL_COUNT0 (1U)

/*! User channel configuration structure list */
extern eim_user_channel_config_t eim_ChannelConfig[EIM_CHANNEL_COUNT0];

#endif
/* END eim_cfg */
/*!
** @}
*/
/*
** ###################################################################
**
**     This file was created by Processor Expert 10.1 [05.21]
**     for the Freescale S32K series of microcontrollers.
**
** ###################################################################
*/

