/* ###################################################################
**     This component module is generated by Processor Expert. Do not modify it.
**     Filename    : spi2_pal.h
**     Project     : S32K_146
**     Processor   : S32K146_144
**     Component   : spi_pal
**     Version     : Component SDK_S32K14x_08, Driver 01.00, CPU db: 3.00.000
**     Repository  : SDK_S32K14x_08
**     Compiler    : GNU C Compiler
**     Date/Time   : 2018-05-15, 15:28, # CodeGen: 60
**     Contents    :
**         SPI_MasterInit             - status_t SPI_MasterInit(spi_instance_t instance,spi_master_t * config);
**         SPI_SlaveInit              - status_t SPI_SlaveInit(spi_instance_t instance,spi_slave_t * config);
**         SPI_SetSS                  - status_t SPI_SetSS(spi_instance_t,uint8_t ss);
**         SPI_MasterTransfer         - status_t SPI_MasterTransfer(spi_instance_t instance,void * txBuffer,void *...
**         SPI_MasterTransferBlocking - status_t SPI_MasterTransferBlocking(spi_instance_t instance,void *...
**         SPI_SlaveTransfer          - status_t SPI_SlaveTransfer(spi_instance_t instance,void * txBuffer,void *...
**         SPI_SlaveTransferBlocking  - status_t SPI_SlaveTransferBlocking(spi_instance_t instance,void *...
**         SPI_GetStatus              - status_t SPI_GetStatus(spi_instance_t instance);
**         SPI_GetDefaultMasterConfig - status_t SPI_GetDefaultMasterConfig(spi_master_t * config);
**         SPI_GetDefaultSlaveConfig  - status_t SPI_GetDefaultSlaveConfig(spi_slave_t * config);
**         SPI_MasterDeinit           - status_t SPI_MasterDeinit(spi_instance_t instance);
**         SPI_SlaveDeinit            - status_t SPI_SlaveDeinit(spi_instance_t instance);
**
**     Copyright 1997 - 2015 Freescale Semiconductor, Inc.
**     Copyright 2016-2017 NXP
**     All Rights Reserved.
**     
**     THIS SOFTWARE IS PROVIDED BY NXP "AS IS" AND ANY EXPRESSED OR
**     IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES
**     OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
**     IN NO EVENT SHALL NXP OR ITS CONTRIBUTORS BE LIABLE FOR ANY DIRECT,
**     INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
**     (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
**     SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
**     HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT,
**     STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING
**     IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF
**     THE POSSIBILITY OF SUCH DAMAGE.
** ###################################################################*/
/*!
** @file spi2_pal.h
** @version 01.00
*/
/*!
**  @addtogroup spi2_pal_module spi2_pal module documentation
**  @{
*/
#ifndef spi2_pal_H
#define spi2_pal_H

/* MODULE spi2_pal. */
/* Include inherited beans */
#include "clockManager_cfg.h"
#include "dmaController_cfg.h"
#include "Cpu.h"
/*! @brief Master module configurations */
/*! @brief Slave module configurations */
extern spi_slave_t spi2_pal_SlaveConfig0;
/*! @brief Define external callbacks for slave devices */
extern void SpiIpcCall(void *driverState, spi_event_t event, void *userData);
/*! @brief Define external callbacks for master devices */


#endif
/* ifndef __spi2_pal_H */
/*!
** @}
*/
/*
** ###################################################################
**
**     This file was created by Processor Expert 10.1 [05.21]
**     for the Freescale S32K series of microcontrollers.
**
** ###################################################################
*/

