#include "dtcApp_cfg.h"
#include "dtcApp_if.h"
#include "dtcCore_if.h"
#include "NvM_Cfg.h" 
#include"MemMap.h"


tDtcAppCanFaultInfor gIVICanFaultInfor[] = {
	{ECU_CATEGORY_NONE,ECU_OPT_COND_LEVEL_0,FALSE, FALSE, 0,             FALSE, FALSE,JT2_TIMER_VALUE,FALSE,FALSE,0},//IVI_FAULT_INDEX_BUS_OFF
	{ECU_CATEGORY_NONE,ECU_OPT_COND_LEVEL_0,FALSE, TRUE, JT1_TIMER_VALUE,TRUE,  FALSE,JT2_TIMER_VALUE,FALSE,FALSE,0},//IVI_FAULT_INDEX_TX_MUTE
	{ECU_CATEGORY_C,   ECU_OPT_COND_LEVEL_3,FALSE, TRUE, JT1_TIMER_VALUE,TRUE,  FALSE,JT2_TIMER_VALUE,FALSE,FALSE,0},//IVI_FAULT_INDEX_RX_CAN_MSG_ECM
	{ECU_CATEGORY_D,   ECU_OPT_COND_LEVEL_3,TRUE,  TRUE, JT1_TIMER_VALUE,TRUE,  FALSE,JT2_TIMER_VALUE,FALSE,FALSE,0},//IVI_FAULT_INDEX_RX_CAN_MSG_ABS_VDC
	{ECU_CATEGORY_A,   ECU_OPT_COND_LEVEL_1,TRUE,  TRUE, JT1_TIMER_VALUE,TRUE,  FALSE,JT2_TIMER_VALUE,FALSE,FALSE,0},//IVI_FAULT_INDEX_RX_CAN_MSG_BCM
	{ECU_CATEGORY_D,   ECU_OPT_COND_LEVEL_3,TRUE,  TRUE, JT1_TIMER_VALUE,TRUE,	FALSE,JT2_TIMER_VALUE,FALSE,FALSE,0},//IVI_FAULT_INDEX_RX_CAN_MSG_HVAC	
	{ECU_CATEGORY_D,   ECU_OPT_COND_LEVEL_3,TRUE,  TRUE, JT1_TIMER_VALUE,TRUE,  FALSE,JT2_TIMER_VALUE,FALSE,FALSE,0},//IVI_FAULT_INDEX_RX_CAN_MSG_CVT	
	{ECU_CATEGORY_D,   ECU_OPT_COND_LEVEL_3,TRUE,  TRUE, JT1_TIMER_VALUE,TRUE,  FALSE,JT2_TIMER_VALUE,FALSE,FALSE,0},//IVI_FAULT_INDEX_RX_CAN_MSG_STRG	TODO
	{ECU_CATEGORY_D,   ECU_OPT_COND_LEVEL_3,TRUE,  TRUE, JT1_TIMER_VALUE,TRUE,  FALSE,JT2_TIMER_VALUE,FALSE,FALSE,0},//IVI_FAULT_INDEX_RX_CAN_MSG_EPS
	{ECU_CATEGORY_A,   ECU_OPT_COND_LEVEL_1,TRUE,  TRUE, JT1_TIMER_VALUE,TRUE,  FALSE,JT2_TIMER_VALUE,FALSE,FALSE,0},//IVI_FAULT_INDEX_RX_CAN_MSG_USM
	{ECU_CATEGORY_D,   ECU_OPT_COND_LEVEL_3,TRUE,  TRUE, JT1_TIMER_VALUE,TRUE,  FALSE,JT2_TIMER_VALUE,FALSE,FALSE,0},//IVI_FAULT_INDEX_RX_CAN_MSG_TPMS	TODO
	{ECU_CATEGORY_D,   ECU_OPT_COND_LEVEL_3,TRUE,  TRUE, JT1_TIMER_VALUE,TRUE,  FALSE,JT2_TIMER_VALUE,FALSE,FALSE,0},//IVI_FAULT_INDEX_RX_CAN_MSG_TCU	TODO
	{ECU_CATEGORY_D,   ECU_OPT_COND_LEVEL_3,TRUE,  TRUE, JT1_TIMER_VALUE,TRUE,  FALSE,JT2_TIMER_VALUE,FALSE,FALSE,0},//IVI_FAULT_INDEX_RX_CAN_MSG_UPA	TODO
	{ECU_CATEGORY_D,   ECU_OPT_COND_LEVEL_3,TRUE,  TRUE, JT1_TIMER_VALUE,TRUE,  FALSE,JT2_TIMER_VALUE,FALSE,FALSE,0},//IVI_FAULT_INDEX_RX_CAN_MSG_VCM
	{ECU_CATEGORY_D,   ECU_OPT_COND_LEVEL_3,TRUE,  TRUE, JT1_TIMER_VALUE,TRUE,  FALSE,JT2_TIMER_VALUE,FALSE,FALSE,0},//IVI_FAULT_INDEX_RX_CAN_MSG_ABD	TODO
	{ECU_CATEGORY_A,   ECU_OPT_COND_LEVEL_3,TRUE,  TRUE, JT1_TIMER_VALUE,TRUE,  FALSE,JT2_TIMER_VALUE,FALSE,FALSE,0},//IVI_FAULT_INDEX_RX_CAN_MSG_IKEY	TODO
};



tDtcAppCanFaultInfor gIcCanFaultInfor[] = {	
		{ECU_CATEGORY_NONE,ECU_OPT_COND_LEVEL_0,FALSE, FALSE, 0,FALSE,FALSE,  JT2_TIMER_VALUE,FALSE,FALSE,0},//IC_FAULT_INDEX_BUS_OFF
		{ECU_CATEGORY_NONE,ECU_OPT_COND_LEVEL_0,FALSE, TRUE, JT1_TIMER_VALUE,TRUE,FALSE,  JT2_TIMER_VALUE,FALSE,FALSE,0},//IC_FAULT_INDEX_TX_MUTE
		{ECU_CATEGORY_C,ECU_OPT_COND_LEVEL_3,FALSE, TRUE, JT1_TIMER_VALUE,TRUE,FALSE,JT2_TIMER_VALUE,FALSE,FALSE,0},//IC_FAULT_INDEX_RX_CAN_MSG_ECM
		{ECU_CATEGORY_D,ECU_OPT_COND_LEVEL_3,TRUE, TRUE, JT1_TIMER_VALUE,TRUE,FALSE,JT2_TIMER_VALUE,FALSE,FALSE,0},//IC_FAULT_INDEX_RX_CAN_MSG_ABS_VDC
		{ECU_CATEGORY_A,ECU_OPT_COND_LEVEL_1,TRUE, TRUE, JT1_TIMER_VALUE,TRUE,FALSE,JT2_TIMER_VALUE,FALSE,FALSE,0},//IC_FAULT_INDEX_RX_CAN_MSG_BCM
		{ECU_CATEGORY_D,ECU_OPT_COND_LEVEL_3,TRUE, TRUE, JT1_TIMER_VALUE,TRUE,FALSE,JT2_TIMER_VALUE,FALSE,FALSE,0},//IC_FAULT_INDEX_RX_CAN_MSG_ACU
		{ECU_CATEGORY_D,ECU_OPT_COND_LEVEL_3,TRUE, TRUE, JT1_TIMER_VALUE,TRUE,FALSE,JT2_TIMER_VALUE,FALSE,FALSE,0},//IC_FAULT_INDEX_RX_CAN_MSG_RADAR	TODO
		{ECU_CATEGORY_D,ECU_OPT_COND_LEVEL_3,TRUE, TRUE, JT1_TIMER_VALUE,TRUE,FALSE,JT2_TIMER_VALUE,FALSE,FALSE,0},//IC_FAULT_INDEX_RX_CAN_MSG_HVAC
		{ECU_CATEGORY_D,ECU_OPT_COND_LEVEL_3,TRUE, TRUE, JT1_TIMER_VALUE,TRUE,FALSE,JT2_TIMER_VALUE,FALSE,FALSE,0},//IC_FAULT_INDEX_RX_CAN_MSG_CVT
		{ECU_CATEGORY_D,ECU_OPT_COND_LEVEL_3,TRUE, TRUE, JT1_TIMER_VALUE,TRUE,FALSE,JT2_TIMER_VALUE,FALSE,FALSE,0},//IC_FAULT_INDEX_RX_CAN_MSG_VDC
		{ECU_CATEGORY_D,ECU_OPT_COND_LEVEL_3,TRUE, TRUE, JT1_TIMER_VALUE,TRUE,FALSE,JT2_TIMER_VALUE,FALSE,FALSE,0},//IC_FAULT_INDEX_RX_CAN_MSG_EPS
		{ECU_CATEGORY_A,ECU_OPT_COND_LEVEL_1,TRUE, TRUE, JT1_TIMER_VALUE,TRUE,FALSE,JT2_TIMER_VALUE,FALSE,FALSE,0},//IC_FAULT_INDEX_RX_CAN_MSG_IPDM
		{ECU_CATEGORY_D,ECU_OPT_COND_LEVEL_3,TRUE, TRUE, JT1_TIMER_VALUE,TRUE,FALSE,JT2_TIMER_VALUE,FALSE,FALSE,0},//IC_FAULT_INDEX_RX_CAN_MSG_TPMS	TODO
		{ECU_CATEGORY_A,ECU_OPT_COND_LEVEL_3,TRUE, TRUE, JT1_TIMER_VALUE,TRUE,FALSE,JT2_TIMER_VALUE,FALSE,FALSE,0},//IC_FAULT_INDEX_RX_CAN_MSG_IKEY	TODO
		{ECU_CATEGORY_D,ECU_OPT_COND_LEVEL_3,TRUE, TRUE, JT1_TIMER_VALUE,TRUE,FALSE,JT2_TIMER_VALUE,FALSE,FALSE,0},//IC_FAULT_INDEX_RX_CAN_MSG_BSW	TODO
		{ECU_CATEGORY_D,ECU_OPT_COND_LEVEL_3,TRUE, TRUE, JT1_TIMER_VALUE,TRUE,FALSE,JT2_TIMER_VALUE,FALSE,FALSE,0},//IC_FAULT_INDEX_RX_CAN_MSG_LANE_CAMERA	TODO
		{ECU_CATEGORY_D,ECU_OPT_COND_LEVEL_3,TRUE, TRUE, JT1_TIMER_VALUE,TRUE,FALSE,JT2_TIMER_VALUE,FALSE,FALSE,0},//IC_FAULT_INDEX_RX_CAN_MSG_SCU
		{ECU_CATEGORY_D,ECU_OPT_COND_LEVEL_3,TRUE, TRUE, JT1_TIMER_VALUE,TRUE,FALSE,JT2_TIMER_VALUE,FALSE,FALSE,0},//IC_FAULT_INDEX_RX_CAN_MSG_LCMR
		{ECU_CATEGORY_D,ECU_OPT_COND_LEVEL_3,TRUE, TRUE, JT1_TIMER_VALUE,TRUE,FALSE,JT2_TIMER_VALUE,FALSE,FALSE,0},//IC_FAULT_INDEX_RX_CAN_MSG_LCML

};


tDtcAppCanFaultInfor gAvmCanFaultInfor[] = {	
		{ECU_CATEGORY_NONE,ECU_OPT_COND_LEVEL_3,FALSE, FALSE, 0,FALSE,FALSE,  JT2_TIMER_VALUE,FALSE,FALSE,0},//AVM_FAULT_INDEX_BUS_OFF
		{ECU_CATEGORY_NONE,ECU_OPT_COND_LEVEL_0,FALSE, TRUE, JT1_TIMER_VALUE,TRUE,FALSE,  JT2_TIMER_VALUE,FALSE,FALSE,0},//AVM_FAULT_INDEX_TX_MUTE
		{ECU_CATEGORY_C,ECU_OPT_COND_LEVEL_3,FALSE, TRUE, JT1_TIMER_VALUE,TRUE,FALSE,JT2_TIMER_VALUE,FALSE,FALSE,0},//AVM_FAULT_INDEX_RX_CAN_MSG_HCM
		{ECU_CATEGORY_D,ECU_OPT_COND_LEVEL_3,TRUE, TRUE, JT1_TIMER_VALUE,TRUE,FALSE,JT2_TIMER_VALUE,FALSE,FALSE,0},//AVM_FAULT_INDEX_RX_CAN_MSG_ABS_VDC
		{ECU_CATEGORY_D,ECU_OPT_COND_LEVEL_3,TRUE, TRUE, JT1_TIMER_VALUE,TRUE,FALSE,JT2_TIMER_VALUE,FALSE,FALSE,0},//AVM_FAULT_INDEX_RX_CAN_MSG_BCM
		{ECU_CATEGORY_D,ECU_OPT_COND_LEVEL_3,TRUE, TRUE, JT1_TIMER_VALUE,TRUE,FALSE,JT2_TIMER_VALUE,FALSE,FALSE,0},//AVM_FAULT_INDEX_RX_CAN_MSG_CVT
		{ECU_CATEGORY_D,ECU_OPT_COND_LEVEL_3,TRUE, TRUE, JT1_TIMER_VALUE,TRUE,FALSE,JT2_TIMER_VALUE,FALSE,FALSE,0},//AVM_FAULT_INDEX_RX_CAN_MSG_STRG	TODO
		{ECU_CATEGORY_D,ECU_OPT_COND_LEVEL_3,TRUE, TRUE, JT1_TIMER_VALUE,TRUE,FALSE,JT2_TIMER_VALUE,FALSE,FALSE,0},//AVM_FAULT_INDEX_RX_CAN_MSG_BSW
};


uint8 gIVICanFaultRealtimeFlag[] = {
	IVI_INNER_ID_CAN_BUS_OFF_MASK,
	IVI_CAN_TX_MUTE,
	IVI_RX_CAN_MSG_MASK_ECM_0X180|IVI_RX_CAN_MSG_MASK_ECM_0X551|IVI_RX_CAN_MSG_MASK_ECM_0X1F9|IVI_RX_CAN_MSG_MASK_ECM_0X160,	//for ECM
	IVI_RX_CAN_MSG_MASK_ABS_0X284|IVI_RX_CAN_MSG_MASK_ABS_0X354|IVI_RX_CAN_MSG_MASK_VDC_0X245,	//FOR ABS_VDC
	IVI_RX_CAN_MSG_MASK_BCM_0X358|IVI_RX_CAN_MSG_MASK_BCM_0X35A|IVI_RX_CAN_MSG_MASK_BCM_0X35D|IVI_RX_CAN_MSG_MASK_BCM_0X60D,	//for bcm
	IVI_RX_CAN_MSG_MASK_HVAC_0X5CB, //HVAC
	IVI_RX_CAN_MSG_MASK_CVT_0X421,	//AT[CVT]
	IVI_RX_CAN_MSG_MASK_STRG_0X2,	//STRG
	IVI_RX_CAN_MSG_MASK_EPS_0X5E4,	//EPS
	IVI_RX_CAN_MSG_MASK_USM_0X625,  //USM[IPDM]
	IVI_RX_CAN_MSG_MASK_TPMS_0X385, //TPMS[FROM BCM]
	IVI_RX_CAN_MSG_MASK_TCU_0X563,	////for TCU
	IVI_RX_CAN_MSG_MASK_UPA_0X57A,	//UPA
	0,	//VCM
	IVI_RX_CAN_MSG_MASK_ABD_0X572, //ABD
	IVI_RX_CAN_MSG_MASK_IKEY_0X351,//351 IKEY
	
};
	
uint8 gIcCanFaultRealtimeFlag[] = {
	IC_INNER_ID_CAN_BUS_OFF_MASK,
	IC_CAN_TX_MUTE,
	IC_RX_CAN_MSG_MASK_ECM_0X180|IC_RX_CAN_MSG_MASK_ECM_0X551|IC_RX_CAN_MSG_MASK_ECM_0X6E2|IC_RX_CAN_MSG_MASK_ECM_0X580,//for ECM
	IC_RX_CAN_MSG_MASK_ABS_0X284|IC_RX_CAN_MSG_MASK_ABS_0X354|IC_RX_CAN_MSG_MASK_VDC_0X245,//FOR ABS_VDC
	IC_RX_CAN_MSG_MASK_BCM_0X358|IC_RX_CAN_MSG_MASK_BCM_0X35D|IC_RX_CAN_MSG_MASK_BCM_0X60D,//for BCM
	IC_RX_CAN_MSG_MASK_ACU_0X02A,//for ACU
	IC_RX_CAN_MSG_MASK_RADAR_0X4CC|IC_RX_CAN_MSG_MASK_RADAR_0X2B7,//FOR RADAR
	0, //IC_RX_CAN_MSG_MASK_HVAC_0X54C,//HVAC
	IC_RX_CAN_MSG_MASK_CVT_0X421,//CVT
	IC_RX_CAN_MSG_MASK_VDC_0X58A,//ONLY FOR VDC
	IC_RX_CAN_MSG_MASK_EPS_0X5E4,//EPS
	IC_RX_CAN_MSG_MASK_IPDM_0X625,//IPDM
	IC_RX_CAN_MSG_MASK_TPMS_0X385,//TPMS
	IC_RX_CAN_MSG_MASK_IKEY_0X351,//IKEY
	IC_RX_CAN_MSG_MASK_BSW_0X57A|IC_RX_CAN_MSG_MASK_BSW_0X2C8,//BSW
	IC_RX_CAN_MSG_MASK_LANE_CAMERA_0X4CB|IC_RX_CAN_MSG_MASK_LANE_CAMERA_0X2B1,//LENE_CAMERA
	IC_RX_CAN_MSG_MASK_SCU_0X11B,//SCU
	IC_RX_CAN_MSG_MASK_LCMR_0X629,//LCMR
	IC_RX_CAN_MSG_MASK_LCML_0X628,//LCML
	
};

//TODO:
boolean gAvmCanFaultRealtimeFlag[AVM_FAULT_INDEX_MAX] = {
	AVM_INNER_ID_CAN_BUS_OFF_MASK,
	AVM_CAN_TX_MUTE,
	AVM_RX_CAN_MSG_MASK_HCM_0X551,//for HCM
	AVM_RX_CAN_MSG_MASK_ABS_0X284,//FOR ABS_VDC
	AVM_RX_CAN_MSG_MASK_BCM_0X358|AVM_RX_CAN_MSG_MASK_BCM_0X60D,//for BCM
	AVM_RX_CAN_MSG_MASK_CVT_0X421,//for CVT
	AVM_RX_CAN_MSG_MASK_STRG_0X2,//STRG
	AVM_RX_CAN_MSG_MASK_BSW_0X57A|AVM_RX_CAN_MSG_MASK_BSW_0X5E9, //BSW
};

uint8 *gDtcAppCanFaultBitRealtimeArray[UDS_CH_MAX_NUM] = {
	&gIVICanFaultRealtimeFlag[0],
	&gIcCanFaultRealtimeFlag[0],
	&gAvmCanFaultRealtimeFlag[0],
};



tDtcAppCanFaultInfor * gDtcAppCanFaultInforPtr[UDS_CH_MAX_NUM] = {
	&gIVICanFaultInfor[0],
	&gIcCanFaultInfor[0],
	&gAvmCanFaultInfor[0],
};


NVM_SEC_VAR_UNSPECIFIED uint16 gIVICanFaultBitFlagArray[IVI_FAULT_INDEX_MAX] = {0};
NVM_SEC_VAR_UNSPECIFIED uint16 gIcCanFaultBitFlagArray[IC_FAULT_INDEX_MAX] = {0};
NVM_SEC_VAR_UNSPECIFIED uint16 gAvmCanFaultBitFlagArray[AVM_FAULT_INDEX_MAX] = {0};

uint8 gCanMsgTotalNum[UDS_CH_MAX_NUM] = {0,0,0,0};

uint16 *gDtcAppCanFaultBitArray[UDS_CH_MAX_NUM] = {
	&gIVICanFaultBitFlagArray[0],
	&gIcCanFaultBitFlagArray[0],
	&gAvmCanFaultBitFlagArray[0],
};

uint16 gDtcAppNvmBlockIdPtr[UDS_CH_MAX_NUM] = {gIVICanFaultBitFlagArrayNvMBlockID,gIcCanFaultBitFlagArrayNvMBlockID,gAvmCanFaultBitFlagArrayNvMBlockID};



void dtcAppPartInit()
{
	// gDtcGroupCbkCounter = sizeof(gDtcGroupCbkList)/sizeof(tDtcGroupCbkList);
}


