#include "adc_wrapper_if.h"

#ifdef PLATFORM_S32K_FOR_ADC
#include "adc_pal.h"
#include "string.h"
#endif

#if 1
const tAdcInstanceChMap gAdcInstanceChMap[] = {

	
	{ADC_LOGIC_CH_VARIANT_CTRL,     0,   ADC_PHY_CH_INDEX_VARIANT_CTRL},
	{ADC_LOGIC_CH_TUNER_ANT_PWR,    0,   ADC_PHY_CH_INDEX_TUNER_ANT_PWR},
	{ADC_LOGIC_CH_GPS_ANT_PWR,      0,	 ADC_PHY_CH_INDEX_GPS_ANT_PWR},
	{ADC_LOGIC_CH_MB_TEMP,          0,   ADC_PHY_CH_INDEX_MB_TEMP},
	{ADC_LOGIC_CH_CIRCUIT_VERSION,  0,   ADC_PHY_CH_INDEX_CIRCUIT_VERSION},
	{ADC_LOGIC_CH_STEERING_B_IN,    0,   ADC_PHY_CH_INDEX_STEERING_B_IN},
	{ADC_LOGIC_CH_STEERING_A_IN,    0,   ADC_PHY_CH_INDEX_STEERING_A_IN},
	
	
	{ADC_LOGIC_CH_AMP_TEMP,         1,	ADC_PHY_CH_INDEX_AMP_TEMP},
	{ADC_LOGIC_CH_FUEL_PWR,         1,	ADC_PHY_CH_INDEX_FUEL_PWR},
	{ADC_LOGIC_CH_FUEL_AD,          1,	ADC_PHY_CH_INDEX_FUEL_AD},
	{ADC_LOGIC_CH_UDBATT_AD,        1,	ADC_PHY_CH_INDEX_UDBATT_AD}
};

#else

const tAdcInstanceChMap gAdcInstanceChMap[] = {
	{ADC_LOGIC_CH_FUEL_PWR,0,ADC_PHY_CH_INDEX_FUEL_PWR},
	{ADC_LOGIC_CH_FUEL_AD,0,ADC_PHY_CH_INDEX_FUEL_AD},
	
	{ADC_LOGIC_CH_AMP_TEMP,0,ADC_PHY_CH_INDEX_AMP_TEMP},
	{ADC_LOGIC_CH_NTC,0,ADC_PHY_CH_INDEX_NTC},
	{ADC_LOGIC_CH_STEERING_A_IN,0,ADC_PHY_CH_INDEX_STEERING_A_IN},
	{ADC_LOGIC_CH_STEERING_B_IN,0,ADC_PHY_CH_INDEX_STEERING_B_IN},

	
	{ADC_LOGIC_CH_UDBATT_AD,1,	ADC_PHY_CH_INDEX_UDBATT_AD}
};
#endif

const uint8 gAdcUsedChNum = sizeof(gAdcInstanceChMap)/sizeof(tAdcInstanceChMap);



