/****************** Warning Lamp Lighting Records *******************/
#include "diagAppWllr_cfg.h"
#include "MemMap.h"


NVM_SEC_VAR_UNSPECIFIED tWlInfor gWarningLampLightingRecords[] = {
	//DON'T CHANGE THE ORDER

	{MILEAGE_INIT_VALUE, WLLR_INIT_VALUE},       //INNER_WL_ID_ABS
	{MILEAGE_INIT_VALUE, WLLR_INIT_VALUE},       //INNER_WL_ID_VDC_TCS_OFF
	{MILEAGE_INIT_VALUE, WLLR_INIT_VALUE},       //INNER_WL_ID_SLIP_IND
	{MILEAGE_INIT_VALUE, WLLR_INIT_VALUE},       //INNER_WL_ID_BRAKE
	{MILEAGE_INIT_VALUE, WLLR_INIT_VALUE},       //INNER_WL_ID_DOOR
	{MILEAGE_INIT_VALUE, WLLR_INIT_VALUE},       //INNER_WL_ID_TRUCK_HATCHBACK
	{MILEAGE_INIT_VALUE, WLLR_INIT_VALUE},       //INNER_WL_ID_OIL
	{MILEAGE_INIT_VALUE, WLLR_INIT_VALUE},       //INNER_WL_ID_C_ENG
	{MILEAGE_INIT_VALUE, WLLR_INIT_VALUE},       //INNER_WL_ID_C_ENG2
	{MILEAGE_INIT_VALUE, WLLR_INIT_VALUE},       //INNER_WL_ID_CRUISE_IND
	{MILEAGE_INIT_VALUE, WLLR_INIT_VALUE},       //INNER_WL_ID_SET_IND
	{MILEAGE_INIT_VALUE, WLLR_INIT_VALUE},       //INNER_WL_ID_CRUISE
	{MILEAGE_INIT_VALUE, WLLR_INIT_VALUE},       //INNER_WL_ID_BA
	{MILEAGE_INIT_VALUE, WLLR_INIT_VALUE},       //INNER_WL_ID_O_D_OFF
	{MILEAGE_INIT_VALUE, WLLR_INIT_VALUE},       //INNER_WL_ID_ATC_T_AMT
	{MILEAGE_INIT_VALUE, WLLR_INIT_VALUE},       //INNER_WL_ID_AT_OIL_TMP
	{MILEAGE_INIT_VALUE, WLLR_INIT_VALUE},       //INNER_WL_ID_CVT_IND
	{MILEAGE_INIT_VALUE, WLLR_INIT_VALUE},       //INNER_WL_ID_SPORT_IND
	{MILEAGE_INIT_VALUE, WLLR_INIT_VALUE},       //INNER_WL_ID_4WD
	{MILEAGE_INIT_VALUE, WLLR_INIT_VALUE},       //INNER_WL_ID_FUEL
	{MILEAGE_INIT_VALUE, WLLR_INIT_VALUE},       //INNER_WL_ID_WASHER
	{MILEAGE_INIT_VALUE, WLLR_INIT_VALUE},       //INNER_WL_ID_TIRE_PRESSURE
	{MILEAGE_INIT_VALUE, WLLR_INIT_VALUE},       //INNER_WL_ID_KEY_GREEN_YELLOW
	{MILEAGE_INIT_VALUE, WLLR_INIT_VALUE},       //INNER_WL_ID_KEY_RED
	{MILEAGE_INIT_VALUE, WLLR_INIT_VALUE},       //INNER_WL_ID_KEY_KNOB
	{MILEAGE_INIT_VALUE, WLLR_INIT_VALUE},       //INNER_WL_ID_EPS
	{MILEAGE_INIT_VALUE, WLLR_INIT_VALUE},       //INNER_WL_ID_E_4WD
	{MILEAGE_INIT_VALUE, WLLR_INIT_VALUE},       //INNER_WL_ID_AFS_OFF_IND
	{MILEAGE_INIT_VALUE, WLLR_INIT_VALUE},       //INNER_WL_ID_4WAS_RAS
	{MILEAGE_INIT_VALUE, WLLR_INIT_VALUE},       //INNER_WL_ID_HDC
	{MILEAGE_INIT_VALUE, WLLR_INIT_VALUE},       //INNER_WL_ID_SYS_FAIL
	{MILEAGE_INIT_VALUE, WLLR_INIT_VALUE},       //INNER_WL_ID_SFT_POSI
	{MILEAGE_INIT_VALUE, WLLR_INIT_VALUE},       //INNER_WL_ID_HV_BAT
	{MILEAGE_INIT_VALUE, WLLR_INIT_VALUE},       //INNER_WL_ID_HEV_BRAKE
	{MILEAGE_INIT_VALUE, WLLR_INIT_VALUE},       //INNER_WL_ID_SFT_OPERATION
	{MILEAGE_INIT_VALUE, WLLR_INIT_VALUE},       //INNER_WL_ID_L_K_MAS
	{MILEAGE_INIT_VALUE, WLLR_INIT_VALUE},       //INNER_WL_ID_CHARGE
	{MILEAGE_INIT_VALUE, WLLR_INIT_VALUE},       //INNER_WL_ID_CHARGE_IND
	{MILEAGE_INIT_VALUE, WLLR_INIT_VALUE},       //INNER_WL_ID_OIL_LEV
	{MILEAGE_INIT_VALUE, WLLR_INIT_VALUE},       //INNER_WL_ID_DPF
	{MILEAGE_INIT_VALUE, WLLR_INIT_VALUE},       //INNER_WL_ID_TRAILER
	{MILEAGE_INIT_VALUE, WLLR_INIT_VALUE},       //INNER_WL_ID_RUN_FLAT
	{MILEAGE_INIT_VALUE, WLLR_INIT_VALUE},       //INNER_WL_ID_E_SUS
	{MILEAGE_INIT_VALUE, WLLR_INIT_VALUE},       //INNER_WL_ID_ROUNCH_CNT
	{MILEAGE_INIT_VALUE, WLLR_INIT_VALUE},       //INNER_WL_ID_SOW_O_IND
	{MILEAGE_INIT_VALUE, WLLR_INIT_VALUE},       //INNER_WL_ID_FILTER
	{MILEAGE_INIT_VALUE, WLLR_INIT_VALUE},       //INNER_WL_ID_BRAKE_PAD
	{MILEAGE_INIT_VALUE, WLLR_INIT_VALUE},       //INNER_WL_ID_SCR
	{MILEAGE_INIT_VALUE, WLLR_INIT_VALUE},       //INNER_WL_ID_E_PKB_IND
	{MILEAGE_INIT_VALUE, WLLR_INIT_VALUE},       //INNER_WL_ID_E_PKB
	{MILEAGE_INIT_VALUE, WLLR_INIT_VALUE},       //INNER_WL_ID_LED_HEADLAMP
	{MILEAGE_INIT_VALUE, WLLR_INIT_VALUE},       //INNER_WL_ID_ISS_IND
	{MILEAGE_INIT_VALUE, WLLR_INIT_VALUE},       //INNER_WL_ID_FUEL_CAP
	{MILEAGE_INIT_VALUE, WLLR_INIT_VALUE},       //INNER_WL_ID_ENG_REMOTE_IND
	{MILEAGE_INIT_VALUE, WLLR_INIT_VALUE},       //INNER_WL_ID_BATTERY_REMAINING
	{MILEAGE_INIT_VALUE, WLLR_INIT_VALUE},       //INNER_WL_ID_READY_IND
	{MILEAGE_INIT_VALUE, WLLR_INIT_VALUE},       //INNER_WL_ID_SLOW_IND
	{MILEAGE_INIT_VALUE, WLLR_INIT_VALUE},       //INNER_WL_ID_CAUTION
	{MILEAGE_INIT_VALUE, WLLR_INIT_VALUE},       //INNER_WL_ID_BATTERY_BRAKEDOWN
	
};


tWlStatusRecord gWlStatusRecords[] = {
	//DON'T CHANGE THE ORDER
	
	{WL_OFF, FALSE},     //INNER_WL_ID_ABS
	{WL_OFF, FALSE},     //INNER_WL_ID_VDC_TCS_OFF
	{WL_OFF, FALSE},     //INNER_WL_ID_SLIP_IND
	{WL_OFF, FALSE},     //INNER_WL_ID_BRAKE
	{WL_OFF, FALSE},     //INNER_WL_ID_DOOR
	{WL_OFF, FALSE},     //INNER_WL_ID_TRUCK_HATCHBACK
	{WL_OFF, FALSE},     //INNER_WL_ID_OIL
	{WL_OFF, FALSE},     //INNER_WL_ID_C_ENG
	{WL_OFF, FALSE},     //INNER_WL_ID_C_ENG2
	{WL_OFF, FALSE},     //INNER_WL_ID_CRUISE_IND
	{WL_OFF, FALSE},     //INNER_WL_ID_SET_IND
	{WL_OFF, FALSE},     //INNER_WL_ID_CRUISE
	{WL_OFF, FALSE},     //INNER_WL_ID_BA
	{WL_OFF, FALSE},     //INNER_WL_ID_O_D_OFF
	{WL_OFF, FALSE},     //INNER_WL_ID_ATC_T_AMT
	{WL_OFF, FALSE},     //INNER_WL_ID_AT_OIL_TMP
	{WL_OFF, FALSE},     //INNER_WL_ID_CVT_IND
	{WL_OFF, FALSE},     //INNER_WL_ID_SPORT_IND
	{WL_OFF, FALSE},     //INNER_WL_ID_4WD
	{WL_OFF, FALSE},     //INNER_WL_ID_FUEL
	{WL_OFF, FALSE},     //INNER_WL_ID_WASHER
	{WL_OFF, FALSE},     //INNER_WL_ID_TIRE_PRESSURE
	{WL_OFF, FALSE},     //INNER_WL_ID_KEY_GREEN_YELLOW
	{WL_OFF, FALSE},     //INNER_WL_ID_KEY_RED
	{WL_OFF, FALSE},     //INNER_WL_ID_KEY_KNOB
	{WL_OFF, FALSE},     //INNER_WL_ID_EPS
	{WL_OFF, FALSE},     //INNER_WL_ID_E_4WD
	{WL_OFF, FALSE},     //INNER_WL_ID_AFS_OFF_IND
	{WL_OFF, FALSE},     //INNER_WL_ID_4WAS_RAS
	{WL_OFF, FALSE},     //INNER_WL_ID_HDC
	{WL_OFF, FALSE},     //INNER_WL_ID_SYS_FAIL
	{WL_OFF, FALSE},     //INNER_WL_ID_SFT_POSI
	{WL_OFF, FALSE},     //INNER_WL_ID_HV_BAT
	{WL_OFF, FALSE},     //INNER_WL_ID_HEV_BRAKE
	{WL_OFF, FALSE},     //INNER_WL_ID_SFT_OPERATION
	{WL_OFF, FALSE},     //INNER_WL_ID_L_K_MAS
	{WL_OFF, FALSE},     //INNER_WL_ID_CHARGE
	{WL_OFF, FALSE},     //INNER_WL_ID_CHARGE_IND
	{WL_OFF, FALSE},     //INNER_WL_ID_OIL_LEV
	{WL_OFF, FALSE},     //INNER_WL_ID_DPF
	{WL_OFF, FALSE},     //INNER_WL_ID_TRAILER
	{WL_OFF, FALSE},     //INNER_WL_ID_RUN_FLAT
	{WL_OFF, FALSE},     //INNER_WL_ID_E_SUS
	{WL_OFF, FALSE},     //INNER_WL_ID_ROUNCH_CNT
	{WL_OFF, FALSE},     //INNER_WL_ID_SOW_O_IND
	{WL_OFF, FALSE},     //INNER_WL_ID_FILTER
	{WL_OFF, FALSE},     //INNER_WL_ID_BRAKE_PAD
	{WL_OFF, FALSE},     //INNER_WL_ID_SCR
	{WL_OFF, FALSE},     //INNER_WL_ID_E_PKB_IND
	{WL_OFF, FALSE},     //INNER_WL_ID_E_PKB
	{WL_OFF, FALSE},     //INNER_WL_ID_LED_HEADLAMP
	{WL_OFF, FALSE},     //INNER_WL_ID_ISS_IND
	{WL_OFF, FALSE},     //INNER_WL_ID_FUEL_CAP
	{WL_OFF, FALSE},     //INNER_WL_ID_ENG_REMOTE_IND
	{WL_OFF, FALSE},     //INNER_WL_ID_BATTERY_REMAINING
	{WL_OFF, FALSE},     //INNER_WL_ID_READY_IND
	{WL_OFF, FALSE},     //INNER_WL_ID_SLOW_IND
	{WL_OFF, FALSE},     //INNER_WL_ID_CAUTION
	{WL_OFF, FALSE},     //INNER_WL_ID_BATTERY_BRAKEDOWN
	
};





