#include "dtcApp_cfg.h"
#include "dtcApp_if.h"
#include "dtcCore_if.h"
#include "NvM_Cfg.h" 
#include"MemMap.h"


tDtcAppCanFaultInfor gIVICanFaultInfor[] = {
	{ECU_CATEGORY_NONE,ECU_OPT_COND_LEVEL_0,FALSE, FALSE, 0,             FALSE, FALSE,JT2_TIMER_VALUE,FALSE,FALSE,0},
	{ECU_CATEGORY_NONE,ECU_OPT_COND_LEVEL_0,FALSE, TRUE, JT1_TIMER_VALUE,TRUE,  FALSE,JT2_TIMER_VALUE,FALSE,FALSE,0},
	{ECU_CATEGORY_C,   ECU_OPT_COND_LEVEL_3,FALSE, TRUE, JT1_TIMER_VALUE,TRUE,  FALSE,JT2_TIMER_VALUE,FALSE,FALSE,0},
	{ECU_CATEGORY_D,   ECU_OPT_COND_LEVEL_3,TRUE,  TRUE, JT1_TIMER_VALUE,TRUE,  FALSE,JT2_TIMER_VALUE,FALSE,FALSE,0},
	{ECU_CATEGORY_A,   ECU_OPT_COND_LEVEL_1,TRUE,  TRUE, JT1_TIMER_VALUE,TRUE,  FALSE,JT2_TIMER_VALUE,FALSE,FALSE,0},
	{ECU_CATEGORY_D,   ECU_OPT_COND_LEVEL_3,TRUE,  TRUE, JT1_TIMER_VALUE,TRUE,	FALSE,JT2_TIMER_VALUE,FALSE,FALSE,0},
	{ECU_CATEGORY_D,   ECU_OPT_COND_LEVEL_3,TRUE,  TRUE, JT1_TIMER_VALUE,TRUE,  FALSE,JT2_TIMER_VALUE,FALSE,FALSE,0},
	{ECU_CATEGORY_D,   ECU_OPT_COND_LEVEL_3,TRUE,  TRUE, JT1_TIMER_VALUE,TRUE,  FALSE,JT2_TIMER_VALUE,FALSE,FALSE,0},
	{ECU_CATEGORY_D,   ECU_OPT_COND_LEVEL_3,TRUE,  TRUE, JT1_TIMER_VALUE,TRUE,  FALSE,JT2_TIMER_VALUE,FALSE,FALSE,0},
	{ECU_CATEGORY_A,   ECU_OPT_COND_LEVEL_1,TRUE,  TRUE, JT1_TIMER_VALUE,TRUE,  FALSE,JT2_TIMER_VALUE,FALSE,FALSE,0},
	{ECU_CATEGORY_D,   ECU_OPT_COND_LEVEL_3,TRUE,  TRUE, JT1_TIMER_VALUE,TRUE,  FALSE,JT2_TIMER_VALUE,FALSE,FALSE,0},
	{ECU_CATEGORY_D,   ECU_OPT_COND_LEVEL_3,TRUE,  TRUE, JT1_TIMER_VALUE,TRUE,  FALSE,JT2_TIMER_VALUE,FALSE,FALSE,0},
	{ECU_CATEGORY_D,   ECU_OPT_COND_LEVEL_3,TRUE,  TRUE, JT1_TIMER_VALUE,TRUE,  FALSE,JT2_TIMER_VALUE,FALSE,FALSE,0},
	{ECU_CATEGORY_D,   ECU_OPT_COND_LEVEL_3,TRUE,  TRUE, JT1_TIMER_VALUE,TRUE,  FALSE,JT2_TIMER_VALUE,FALSE,FALSE,0},
	{ECU_CATEGORY_D,   ECU_OPT_COND_LEVEL_3,TRUE,  TRUE, JT1_TIMER_VALUE,TRUE,  FALSE,JT2_TIMER_VALUE,FALSE,FALSE,0},
	{ECU_CATEGORY_A,   ECU_OPT_COND_LEVEL_3,TRUE,  TRUE, JT1_TIMER_VALUE,TRUE,  FALSE,JT2_TIMER_VALUE,FALSE,FALSE,0},
};



tDtcAppCanFaultInfor gIcCanFaultInfor[] = {	
		{ECU_CATEGORY_NONE,ECU_OPT_COND_LEVEL_0,FALSE, FALSE, 0,FALSE,FALSE,  JT2_TIMER_VALUE,FALSE,FALSE,0},
		{ECU_CATEGORY_NONE,ECU_OPT_COND_LEVEL_0,FALSE, TRUE, JT1_TIMER_VALUE,TRUE,FALSE,  JT2_TIMER_VALUE,FALSE,FALSE,0},
		{ECU_CATEGORY_C,ECU_OPT_COND_LEVEL_3,FALSE, TRUE, JT1_TIMER_VALUE,TRUE,FALSE,JT2_TIMER_VALUE,FALSE,FALSE,0},
		{ECU_CATEGORY_D,ECU_OPT_COND_LEVEL_3,TRUE, TRUE, JT1_TIMER_VALUE,TRUE,FALSE,JT2_TIMER_VALUE,FALSE,FALSE,0},
		{ECU_CATEGORY_A,ECU_OPT_COND_LEVEL_1,TRUE, TRUE, JT1_TIMER_VALUE,TRUE,FALSE,JT2_TIMER_VALUE,FALSE,FALSE,0},
		{ECU_CATEGORY_D,ECU_OPT_COND_LEVEL_3,TRUE, TRUE, JT1_TIMER_VALUE,TRUE,FALSE,JT2_TIMER_VALUE,FALSE,FALSE,0},
		{ECU_CATEGORY_D,ECU_OPT_COND_LEVEL_3,TRUE, TRUE, JT1_TIMER_VALUE,TRUE,FALSE,JT2_TIMER_VALUE,FALSE,FALSE,0},
		{ECU_CATEGORY_D,ECU_OPT_COND_LEVEL_3,TRUE, TRUE, JT1_TIMER_VALUE,TRUE,FALSE,JT2_TIMER_VALUE,FALSE,FALSE,0},
		{ECU_CATEGORY_D,ECU_OPT_COND_LEVEL_3,TRUE, TRUE, JT1_TIMER_VALUE,TRUE,FALSE,JT2_TIMER_VALUE,FALSE,FALSE,0},
		{ECU_CATEGORY_D,ECU_OPT_COND_LEVEL_3,TRUE, TRUE, JT1_TIMER_VALUE,TRUE,FALSE,JT2_TIMER_VALUE,FALSE,FALSE,0},
		{ECU_CATEGORY_D,ECU_OPT_COND_LEVEL_3,TRUE, TRUE, JT1_TIMER_VALUE,TRUE,FALSE,JT2_TIMER_VALUE,FALSE,FALSE,0},
		{ECU_CATEGORY_A,ECU_OPT_COND_LEVEL_1,TRUE, TRUE, JT1_TIMER_VALUE,TRUE,FALSE,JT2_TIMER_VALUE,FALSE,FALSE,0},
		{ECU_CATEGORY_D,ECU_OPT_COND_LEVEL_3,TRUE, TRUE, JT1_TIMER_VALUE,TRUE,FALSE,JT2_TIMER_VALUE,FALSE,FALSE,0},
		{ECU_CATEGORY_A,ECU_OPT_COND_LEVEL_3,TRUE, TRUE, JT1_TIMER_VALUE,TRUE,FALSE,JT2_TIMER_VALUE,FALSE,FALSE,0},
		{ECU_CATEGORY_D,ECU_OPT_COND_LEVEL_3,TRUE, TRUE, JT1_TIMER_VALUE,TRUE,FALSE,JT2_TIMER_VALUE,FALSE,FALSE,0},
		{ECU_CATEGORY_D,ECU_OPT_COND_LEVEL_3,TRUE, TRUE, JT1_TIMER_VALUE,TRUE,FALSE,JT2_TIMER_VALUE,FALSE,FALSE,0},
		{ECU_CATEGORY_D,ECU_OPT_COND_LEVEL_3,TRUE, TRUE, JT1_TIMER_VALUE,TRUE,FALSE,JT2_TIMER_VALUE,FALSE,FALSE,0},
		{ECU_CATEGORY_D,ECU_OPT_COND_LEVEL_3,TRUE, TRUE, JT1_TIMER_VALUE,TRUE,FALSE,JT2_TIMER_VALUE,FALSE,FALSE,0},
		{ECU_CATEGORY_D,ECU_OPT_COND_LEVEL_3,TRUE, TRUE, JT1_TIMER_VALUE,TRUE,FALSE,JT2_TIMER_VALUE,FALSE,FALSE,0},

};


tDtcAppCanFaultInfor gAvmCanFaultInfor[] = {	
		{ECU_CATEGORY_NONE,ECU_OPT_COND_LEVEL_3,FALSE, FALSE, 0,FALSE,FALSE,  JT2_TIMER_VALUE,FALSE,FALSE,0},
		{ECU_CATEGORY_NONE,ECU_OPT_COND_LEVEL_0,FALSE, TRUE, JT1_TIMER_VALUE,TRUE,FALSE,  JT2_TIMER_VALUE,FALSE,FALSE,0},
		{ECU_CATEGORY_C,ECU_OPT_COND_LEVEL_3,FALSE, TRUE, JT1_TIMER_VALUE,TRUE,FALSE,JT2_TIMER_VALUE,FALSE,FALSE,0},
		{ECU_CATEGORY_D,ECU_OPT_COND_LEVEL_3,TRUE, TRUE, JT1_TIMER_VALUE,TRUE,FALSE,JT2_TIMER_VALUE,FALSE,FALSE,0},
		{ECU_CATEGORY_D,ECU_OPT_COND_LEVEL_3,TRUE, TRUE, JT1_TIMER_VALUE,TRUE,FALSE,JT2_TIMER_VALUE,FALSE,FALSE,0},
		{ECU_CATEGORY_D,ECU_OPT_COND_LEVEL_3,TRUE, TRUE, JT1_TIMER_VALUE,TRUE,FALSE,JT2_TIMER_VALUE,FALSE,FALSE,0},
		{ECU_CATEGORY_D,ECU_OPT_COND_LEVEL_3,TRUE, TRUE, JT1_TIMER_VALUE,TRUE,FALSE,JT2_TIMER_VALUE,FALSE,FALSE,0},
		{ECU_CATEGORY_D,ECU_OPT_COND_LEVEL_3,TRUE, TRUE, JT1_TIMER_VALUE,TRUE,FALSE,JT2_TIMER_VALUE,FALSE,FALSE,0},
};


uint8 gIVICanFaultRealtimeFlag[] = {
	IVI_INNER_ID_CAN_BUS_OFF_MASK,
	IVI_CAN_TX_MUTE,
	IVI_RX_CAN_MSG_MASK_ECM_0X180|IVI_RX_CAN_MSG_MASK_ECM_0X551|IVI_RX_CAN_MSG_MASK_ECM_0X1F9|IVI_RX_CAN_MSG_MASK_ECM_0X160,	
	IVI_RX_CAN_MSG_MASK_ABS_0X284|IVI_RX_CAN_MSG_MASK_ABS_0X354|IVI_RX_CAN_MSG_MASK_VDC_0X245,	
	IVI_RX_CAN_MSG_MASK_BCM_0X358|IVI_RX_CAN_MSG_MASK_BCM_0X35A|IVI_RX_CAN_MSG_MASK_BCM_0X35D|IVI_RX_CAN_MSG_MASK_BCM_0X60D,	
	IVI_RX_CAN_MSG_MASK_HVAC_0X5CB, 
	IVI_RX_CAN_MSG_MASK_CVT_0X421,	
	IVI_RX_CAN_MSG_MASK_STRG_0X2,	
	IVI_RX_CAN_MSG_MASK_EPS_0X5E4,	
	IVI_RX_CAN_MSG_MASK_USM_0X625,  
	IVI_RX_CAN_MSG_MASK_TPMS_0X385, 
	IVI_RX_CAN_MSG_MASK_TCU_0X563,	
	IVI_RX_CAN_MSG_MASK_UPA_0X57A,	
	0,	
	IVI_RX_CAN_MSG_MASK_ABD_0X572, 
	IVI_RX_CAN_MSG_MASK_IKEY_0X351,
	
};
	
uint8 gIcCanFaultRealtimeFlag[] = {
	IC_INNER_ID_CAN_BUS_OFF_MASK,
	IC_CAN_TX_MUTE,
	IC_RX_CAN_MSG_MASK_ECM_0X180|IC_RX_CAN_MSG_MASK_ECM_0X551|IC_RX_CAN_MSG_MASK_ECM_0X6E2|IC_RX_CAN_MSG_MASK_ECM_0X580,
	IC_RX_CAN_MSG_MASK_ABS_0X284|IC_RX_CAN_MSG_MASK_ABS_0X354|IC_RX_CAN_MSG_MASK_VDC_0X245,
	IC_RX_CAN_MSG_MASK_BCM_0X358|IC_RX_CAN_MSG_MASK_BCM_0X35D|IC_RX_CAN_MSG_MASK_BCM_0X60D,
	IC_RX_CAN_MSG_MASK_ACU_0X02A,
	IC_RX_CAN_MSG_MASK_RADAR_0X4CC|IC_RX_CAN_MSG_MASK_RADAR_0X2B7,
	0, 
	IC_RX_CAN_MSG_MASK_CVT_0X421,
	IC_RX_CAN_MSG_MASK_VDC_0X58A,
	IC_RX_CAN_MSG_MASK_EPS_0X5E4,
	IC_RX_CAN_MSG_MASK_IPDM_0X625,
	IC_RX_CAN_MSG_MASK_TPMS_0X385,
	IC_RX_CAN_MSG_MASK_IKEY_0X351,
	IC_RX_CAN_MSG_MASK_BSW_0X57A|IC_RX_CAN_MSG_MASK_BSW_0X2C8,
	IC_RX_CAN_MSG_MASK_LANE_CAMERA_0X4CB|IC_RX_CAN_MSG_MASK_LANE_CAMERA_0X2B1,
	IC_RX_CAN_MSG_MASK_SCU_0X11B,
	IC_RX_CAN_MSG_MASK_LCMR_0X629,
	IC_RX_CAN_MSG_MASK_LCML_0X628,
	
};


boolean gAvmCanFaultRealtimeFlag[AVM_FAULT_INDEX_MAX] = {
	AVM_INNER_ID_CAN_BUS_OFF_MASK,
	AVM_CAN_TX_MUTE,
	AVM_RX_CAN_MSG_MASK_HCM_0X551,
	AVM_RX_CAN_MSG_MASK_ABS_0X284,
	AVM_RX_CAN_MSG_MASK_BCM_0X358|AVM_RX_CAN_MSG_MASK_BCM_0X60D,
	AVM_RX_CAN_MSG_MASK_CVT_0X421,
	AVM_RX_CAN_MSG_MASK_STRG_0X2,
	AVM_RX_CAN_MSG_MASK_BSW_0X57A|AVM_RX_CAN_MSG_MASK_BSW_0X5E9, 
};

uint8 *gDtcAppCanFaultBitRealtimeArray[UDS_CH_MAX_NUM] = {
	&gIVICanFaultRealtimeFlag[0],
	&gIcCanFaultRealtimeFlag[0],
	&gAvmCanFaultRealtimeFlag[0],
};



tDtcAppCanFaultInfor * gDtcAppCanFaultInforPtr[UDS_CH_MAX_NUM] = {
	&gIVICanFaultInfor[0],
	&gIcCanFaultInfor[0],
	&gAvmCanFaultInfor[0],
};


NVM_SEC_VAR_UNSPECIFIED uint16 gIVICanFaultBitFlagArray[IVI_FAULT_INDEX_MAX] = {0};
NVM_SEC_VAR_UNSPECIFIED uint16 gIcCanFaultBitFlagArray[IC_FAULT_INDEX_MAX] = {0};
NVM_SEC_VAR_UNSPECIFIED uint16 gAvmCanFaultBitFlagArray[AVM_FAULT_INDEX_MAX] = {0};

uint8 gCanMsgTotalNum[UDS_CH_MAX_NUM] = {0,0,0,0};

uint16 *gDtcAppCanFaultBitArray[UDS_CH_MAX_NUM] = {
	&gIVICanFaultBitFlagArray[0],
	&gIcCanFaultBitFlagArray[0],
	&gAvmCanFaultBitFlagArray[0],
};

uint16 gDtcAppNvmBlockIdPtr[UDS_CH_MAX_NUM] = {gIVICanFaultBitFlagArrayNvMBlockID,gIcCanFaultBitFlagArrayNvMBlockID,gAvmCanFaultBitFlagArrayNvMBlockID};



void dtcAppPartInit()
{
	
}


