

#include "sid0x27_cfg.h"



uint8  gKeyAuthFailCounter[UDS_CH_MAX_NUM] = {0,0,0};
tUdsSecurityStatus gUdsGlobalSecurityStatus[UDS_CH_MAX_NUM] = {UDS_SECURITY_STATUS_NOT_ACTIVE,UDS_SECURITY_STATUS_NOT_ACTIVE,UDS_SECURITY_STATUS_NOT_ACTIVE};
tUdsSecurityLevel gUdsSecuLevel[UDS_CH_MAX_NUM] = {UDS_SECURITY_LEVEL_0,UDS_SECURITY_LEVEL_0,UDS_SECURITY_LEVEL_0};
tSid0x27SeedKeyPairInfor gSid0x27SeedKeyPairInfor[UDS_CH_MAX_NUM][UDS_SECURITY_INDEX_MAX];
uint32 gLockTimePreTick[UDS_CH_MAX_NUM] = {0,0,0};
tUdsSecurityStatus gSecurityStatusArray[UDS_CH_MAX_NUM][UDS_SECURITY_INDEX_MAX] = {
	{UDS_SECURITY_STATUS_NOT_ACTIVE,UDS_SECURITY_STATUS_NOT_ACTIVE,UDS_SECURITY_STATUS_NOT_ACTIVE,UDS_SECURITY_STATUS_NOT_ACTIVE},
	{UDS_SECURITY_STATUS_NOT_ACTIVE,UDS_SECURITY_STATUS_NOT_ACTIVE,UDS_SECURITY_STATUS_NOT_ACTIVE,UDS_SECURITY_STATUS_NOT_ACTIVE},
	{UDS_SECURITY_STATUS_NOT_ACTIVE,UDS_SECURITY_STATUS_NOT_ACTIVE,UDS_SECURITY_STATUS_NOT_ACTIVE,UDS_SECURITY_STATUS_NOT_ACTIVE},

};

const tSid0x27CfgInfor gSid0x27CfgInfor = {
	.maxChNum = UDS_CH_MAX_NUM,
	.enableSecurityAccessType1 = TRUE,
	.enableSecurityAccessType3 = TRUE,
	.enableSecurityAccessType5 = TRUE,
	.enableSecurityAccessType7 = TRUE,
	.keyLen = SID_0X27_CFG_SECURITY_SEED_LEN,
	.seedLen = SID_0X27_CFG_SECURITY_KEY_LEN,
	.authFailedMaxCount = SID_0X27_KEY_COUNTER_LIMIT,
	.delayTimerForReAuth = SID_0X27_DELAY_TIMER_MAX,
	.needCheckSessionMatchAccessType = TRUE,
	.continueDelayTimerAfterSysReset = FALSE,
	.nvmBlockIdForLockTimer = 0,
};





uint32 gSecurityLockTimer[UDS_CH_MAX_NUM] = {0};


const tSessionMapAccessTypeArray gSessionMapAccessTypeArray[UDS_CH_MAX_NUM] = {
	{	
		{
			{UDS_SECURITY_ACCESS_TYPE_REQ_SEED_1,UDS_EXTENDED_DIAG_SESSION|UDS_PROGRAMMING_SESSION},
			{UDS_SECURITY_ACCESS_TYPE_REQ_SEED_3,UDS_EXTENDED_DIAG_SESSION|UDS_PROGRAMMING_SESSION},
			{UDS_SECURITY_ACCESS_TYPE_REQ_SEED_5,UDS_EXTENDED_DIAG_SESSION|UDS_CODING_SESSION},
			{UDS_SECURITY_ACCESS_TYPE_REQ_SEED_7,UDS_PROGRAMMING_SESSION},
		}
	},
	{	
		{
			{UDS_SECURITY_ACCESS_TYPE_REQ_SEED_1,UDS_EXTENDED_DIAG_SESSION|UDS_PROGRAMMING_SESSION},
			{UDS_SECURITY_ACCESS_TYPE_REQ_SEED_3,UDS_EXTENDED_DIAG_SESSION|UDS_PROGRAMMING_SESSION},
			{UDS_SECURITY_ACCESS_TYPE_REQ_SEED_5,UDS_EXTENDED_DIAG_SESSION|UDS_CODING_SESSION},
			{UDS_SECURITY_ACCESS_TYPE_REQ_SEED_7,UDS_PROGRAMMING_SESSION},
		}
	},
	{	
		{
			{UDS_SECURITY_ACCESS_TYPE_REQ_SEED_1,UDS_EXTENDED_DIAG_SESSION|UDS_PROGRAMMING_SESSION},
			{UDS_SECURITY_ACCESS_TYPE_REQ_SEED_3,UDS_EXTENDED_DIAG_SESSION|UDS_PROGRAMMING_SESSION},
			{UDS_SECURITY_ACCESS_TYPE_REQ_SEED_5,UDS_EXTENDED_DIAG_SESSION|UDS_CODING_SESSION},
			{UDS_SECURITY_ACCESS_TYPE_REQ_SEED_7,UDS_PROGRAMMING_SESSION},
		}
	},
	{	
		{
			{UDS_SECURITY_ACCESS_TYPE_REQ_SEED_1,UDS_EXTENDED_DIAG_SESSION|UDS_PROGRAMMING_SESSION},
			{UDS_SECURITY_ACCESS_TYPE_REQ_SEED_3,UDS_EXTENDED_DIAG_SESSION|UDS_PROGRAMMING_SESSION},
			{UDS_SECURITY_ACCESS_TYPE_REQ_SEED_5,UDS_EXTENDED_DIAG_SESSION|UDS_CODING_SESSION},
			{UDS_SECURITY_ACCESS_TYPE_REQ_SEED_7,UDS_PROGRAMMING_SESSION},
		}
	},
};

