/*!Warning!:Please don't modify this file,this is generated by tools!*/
/********************************************************************
File name: BattVolt_Cfg.h
Author: Stephen Du
Version: V1.0
Timestamp: 2017-01-16 15:55:25
Description:
Others:
Function List:
1. ....
History: /
1. Date:
Author:
Modification:
2. ...
********************************************************************/
#ifndef _BATTVOLT_CFG_H_
#define _BATTVOLT_CFG_H_

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

#include "Std_Types.h"

#define BATTVOLT_DEBUG_TRACE STD_ON

//#define BATTVOLT_CONVERT_ALGO(adcValue)   ((adcValue * 3030) / 1024 + 15)
//#define BATTVOLT_CONVERT_ALGO(adcValue)   (((adcValue * 378)+5274)>>7)
//because fuel ADC sample chaned to 12bit,so this value need div 4
#define BATTVOLT_CONVERT_ALGO(adcValue)   ((((adcValue>>2) * 378)+5274)>>7)

#define BATTVOLT_FILTER_TIME (2U)

#if 0
#define BATTVOLT_VOLTRANGE_ULTRALOW_START (0U)

#define BATTVOLT_VOLTRANGE_LOW_START (780U)
#define BATTVOLT_THRESHOLD_ULTRALOW (760U)//(650U)
#define BATTVOLT_VOLTRANGE_ULTRALOW_END (800U)

#define BATTVOLT_VOLTRANGE_NORMAL_START (820U)
#define BATTVOLT_THRESHOLD_LOW (840U)
#define BATTVOLT_VOLTRANGE_LOW_END (900U)

#define BATTVOLT_VOLTRANGE_HIGH_START (1480U)
#define BATTVOLT_THRESHOLD_HIGH (1500U)
#define BATTVOLT_VOLTRANGE_NORMAL_END (1520U)

#define BATTVOLT_VOLTRANGE_ULTRAHIGH_START (1680U)
#define BATTVOLT_THRESHOLD_ULTRAHIGH (1700U)
#define BATTVOLT_VOLTRANGE_HIGH_END (1720U)

#define BATTVOLT_VOLTRANGE_ULTRAHIGH_END (2200U)
#else
#define BATTVOLT_VOLTRANGE_ULTRALOW_START (0U)

#define BATTVOLT_VOLTRANGE_LOW_START (630U)
#define BATTVOLT_THRESHOLD_ULTRALOW (580U)//(650U)
#define BATTVOLT_VOLTRANGE_ULTRALOW_END (710U)

#define BATTVOLT_VOLTRANGE_NORMAL_START (780U)
#define BATTVOLT_THRESHOLD_LOW (800U)
#define BATTVOLT_VOLTRANGE_LOW_END (820U)

#define BATTVOLT_VOLTRANGE_HIGH_START (1800U)
#define BATTVOLT_THRESHOLD_HIGH (1820U)
#define BATTVOLT_VOLTRANGE_NORMAL_END (1840U)

#define BATTVOLT_VOLTRANGE_ULTRAHIGH_START (1880U)
//#define BATTVOLT_THRESHOLD_ULTRAHIGH (1900U)
//#define BATTVOLT_VOLTRANGE_HIGH_END (1920U)
#define BATTVOLT_THRESHOLD_ULTRAHIGH (2150U)
//#define BATTVOLT_VOLTRANGE_HIGH_END (2120U)
#define BATTVOLT_VOLTRANGE_HIGH_END (2130U)

#define BATTVOLT_VOLTRANGE_ULTRAHIGH_END (2200U)

#endif


#ifdef __cplusplus
}
#endif // __cplusplus

#endif
