/*!Warning!:Please don't modify this file,this is generated by tools!*/
/********************************************************************
File name: Task_DigitalAMP_Cfg.h
Author: Stephen Du
Version: V1.0
Timestamp: 2019-01-30 11:11:46
Description:
Others:
Function List:
1. ....
History: /
1. Date:
Author:
Modification:
2. ...
********************************************************************/
#ifndef _TASK_DIGITALAMP_CFG_H_
#define _TASK_DIGITALAMP_CFG_H_

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

#include "Std_Types.h"

#define TASK_DIGITALAMP_DEBUG_TRACE STD_ON
#define TASK_DIGITALAMP_STACK_MONITOR STD_OFF

#ifdef __cplusplus
}
#endif // __cplusplus

#endif
/*=========================== END OF FILE: Task_DigitalAMP_Cfg.h ===========================*/
