/*!Warning!:Please don't modify this file,this is generated by tools!*/
/********************************************************************
File name: TempAmp_Cfg.h
Author: Stephen Du
Version: V1.0
Timestamp: 2017-01-16 15:55:25
Description:
Others:
Function List:
1. ....
History: /
1. Date:
Author:
Modification:
2. ...
********************************************************************/
#ifndef _TEMPAMP_CFG_H_
#define _TEMPAMP_CFG_H_

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

#include "Std_Types.h"

#define TEMPAMP_DEBUG_TRACE STD_ON

#define TEMPAMP_FILTER_TIME (2U)

#define TEMPAMP_VOLTRANGE_ULTRALOW_START (-400)

#define TEMPAMP_VOLTRANGE_LOW_START (-250)
#define TEMPAMP_THRESHOLD_ULTRALOW (-200)
#define TEMPAMP_VOLTRANGE_ULTRALOW_END (-150)

#define TEMPAMP_VOLTRANGE_NORMAL_START (-50)
#define TEMPAMP_THRESHOLD_LOW (0)
#define TEMPAMP_VOLTRANGE_LOW_END (50)

#define TEMPAMP_VOLTRANGE_HIGH_START (950)
#define TEMPAMP_THRESHOLD_HIGH (1000)
#define TEMPAMP_VOLTRANGE_NORMAL_END (1050)

#define TEMPAMP_VOLTRANGE_ULTRAHIGH_START (1150)
#define TEMPAMP_THRESHOLD_ULTRAHIGH (1200)
#define TEMPAMP_VOLTRANGE_HIGH_END (1250)

#define TEMPAMP_VOLTRANGE_ULTRAHIGH_END (1300)


#ifdef __cplusplus
}
#endif // __cplusplus

#endif