#include "Std_Types.h"
#include "AppInfo.h"
#include "MemMap.h"
extern int _start();

APPVALID_START_SEC_VAR_FAST_POWER_ON_INIT_UNSPECIFIED
const uint8 AppValidNumEnd[8] = {0x5a, 0xa1, 0xca, 0xa5, 0xca, 0xe7, 0x6f, 0x2e};
APPVALID_STOP_SEC_VAR_FAST_POWER_ON_INIT_UNSPECIFIED


APPINFO_START_SEC_VAR_FAST_POWER_ON_INIT_UNSPECIFIED
const AppinfoStructType Appinfo =
{
	(uint32)_start,
	(uint32)&AppValidNumEnd[0],
	{0x5a, 0xa1, 0xca, 0xa5, 0xca, 0xe7, 0x6f, 0x2e}
};

const SysVerInfoSType SysVersionInfo =
{
	{__DATE__},
	{__TIME__},
	{'3','G','1','2',' '},
	{'I', 'P', 'C', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' '},
	{SYS_VERINFO_PROJECTNUM, SYS_VERINFO_TEAMNUM, (uint8)(SYS_VERINFO_PARTSERIALNUM >> 8), (uint8)(SYS_VERINFO_PARTSERIALNUM), SYS_VERINFO_VERSTAGE, SYS_VERINFO_VERSUBSTAGE},
	{SYS_VERINFO_PROJECTNUM, SYS_VERINFO_TEAMNUM, (uint8)(SYS_VERINFO_PARTSERIALNUM >> 8), (uint8)(SYS_VERINFO_PARTSERIALNUM) + SYS_CATEGOAY_SW, SYS_VERINFO_SWHWSERIALNUM, (uint8)((SYS_VERINFO_FRS_MAINSTAGE << 4) + SYS_VERINFO_FRS_SUBSTAGE), SYS_VERINFO_SW_SUBVER},
	{SYS_VERINFO_PROJECTNUM, SYS_VERINFO_TEAMNUM, (uint8)(SYS_VERINFO_PARTSERIALNUM >> 8), (uint8)(SYS_VERINFO_PARTSERIALNUM) + SYS_CATEGOAY_APP, SYS_VERINFO_SWHWSERIALNUM, (uint8)((SYS_VERINFO_FRS_MAINSTAGE << 4) + SYS_VERINFO_FRS_SUBSTAGE), SYS_VERINFO_APP_SUBVER},
	{SYS_VERINFO_PROJECTNUM, SYS_VERINFO_TEAMNUM, (uint8)(SYS_VERINFO_PARTSERIALNUM >> 8), (uint8)(SYS_VERINFO_PARTSERIALNUM) + SYS_CATEGOAY_BSC, SYS_VERINFO_SWHWSERIALNUM, (uint8)((SYS_VERINFO_FRS_MAINSTAGE << 4) + SYS_VERINFO_FRS_SUBSTAGE), SYS_VERINFO_BSC_SUBVER},
	{SYS_VERINFO_PROJECTNUM, SYS_VERINFO_TEAMNUM, (uint8)(SYS_VERINFO_PARTSERIALNUM >> 8), (uint8)(SYS_VERINFO_PARTSERIALNUM) + SYS_CATEGOAY_HMI, SYS_VERINFO_SWHWSERIALNUM, (uint8)((SYS_VERINFO_FRS_MAINSTAGE << 4) + SYS_VERINFO_FRS_SUBSTAGE), SYS_VERINFO_HMI_SUBVER},
	{'M', '8', '1', '0', '5', ' ', ' ', ' ', ' ', ' '},
	{'M', '8', '1', '0', '5', 'J', '0', '0', '0', '0', '0'},
	{'M', '8', '1', '0', '5', 'S', '0', '0', '0', '0'},
	SYS_VERINFO_DBC,
};

#if 0
const SysVerInfoSType SysVerInfo =
{
	{0x49, 0x50, 0x43, 0x20, 0x20, 0x20, 0x20, 0x20, 0x20, 0x20, 0x20, 0x20, 0x20, 0x20, 0x20},
	0x00,
	0x51,
	0x75,
	0x0030,
	0x9005,
	0x4100,
	0x8000,
	0x8000,
	0x8000,
	0x8000,
	{0x4d, 0x38, 0x31, 0x30, 0x35, 0x4a, 0x30, 0x30, 0x30, 0x30, 0x30},
	{0x4d, 0x38, 0x31, 0x30, 0x35, 0x4a, 0x30, 0x30, 0x30, 0x30}
};
#endif
APPINFO_STOP_SEC_VAR_FAST_POWER_ON_INIT_UNSPECIFIED

uint8 Sys_GetBootloaderVersion(uint8* buff)
{
	uint8 lenLoop = 0u;

	for(lenLoop=0;lenLoop<SYS_BOOTLOADER_VER_LEN;lenLoop++)
	{
		*buff++=*(uint8*)(SYS_BOOTLOADER_VER_ADDR+lenLoop);
	}
	return(SYS_BOOTLOADER_VER_LEN);
}

