/*!Warning!:Please don't modify this file,this is generated by tools!*/
/********************************************************************
File name: Alarm_Cfg.h
Author: Stephen Du
Version: V1.0
Timestamp: 2019-12-16 11:05:58
Description:
Others:
Function List:
1. ....
History: /
1. Date:
Author:
Modification:
2. ...
********************************************************************/
#ifndef _ALARM_CFG_H_
#define _ALARM_CFG_H_

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

#define ALARM_DEBUG_TRACE STD_OFF

#define ALARM_TASK_BASETIME (1U)

#define ALARM_REGMAX_1MS (1U)
#define ALARM_REGMAX_2MS (6U)
#define ALARM_REGMAX_5MS (6U)
#define ALARM_REGMAX_6MS (6U)
#define ALARM_REGMAX_10MS (6U)
#define ALARM_REGMAX_13MS (6U)
#define ALARM_REGMAX_100MS (2U)
#define ALARM_REGMAX_60S (1U)
#define ALARM_REGMAX_500MS (1U)
#define ALARM_REGMAX_1S (1U)
#define ALARM_REGMAX_5S (1U)
#define ALARM_REGMAX_30S (1U)
#define ALARM_REGMAX_7MS (1U)

#define ALARM_ID_1MS (0U)
#define ALARM_ID_2MS (1U)
#define ALARM_ID_5MS (2U)
#define ALARM_ID_6MS (3U)
#define ALARM_ID_10MS (4U)
#define ALARM_ID_13MS (5U)
#define ALARM_ID_100MS (6U)
#define ALARM_ID_60S (7U)
#define ALARM_ID_500MS (8U)
#define ALARM_ID_1S (9U)
#define ALARM_ID_5S (10U)
#define ALARM_ID_30S (11U)
#define ALARM_ID_7MS (12U)
#define ALARM_ID_MAX (13U)

#ifdef __cplusplus
}
#endif // __cplusplus

#endif
/*=========================== END OF FILE: Alarm_Cfg.h ===========================*/
