/******************************************************************************
**          Copyright (c) by HASE (Chengdu) Technology Center.
**
**          CONFIDENTIAL and PROPRIETARY
**          UNPUBLISHED SOURCE CODE
**          Disclosure, use or reproduction without authorization of
**          HASE (Chengdu) Technology Center is prohibited.
*******************************************************************************
**
**          File  : Ea_cfg.c
**          Modifly:brown
**			author: weltry wang
**          Date  : 2017-06-20
**          
**          History:
**          1. Date:2018-02-26
**             Author:weltry wang
**             Modification:
**
******************************************************************************/
/*====================[I N C L U D E S]====================*/
#include "Ea_Cfg.h"
#include "Ea.h"



/*====================[V A R I A N T S]====================*/


//32~39 Ea Markers
const uint16 EaMarkerAddStart  =   32u;
const uint16 EaMarkerAddEnd    =   39u;
//const uint8  EaMarkerAddLen    =   8u;

//40~159 BlockIndex,a block index need two bytes
const uint16 BlockIndexAddStart  = 40u;
const uint16 BlockIndexAddEnd    = 159u;
const uint8  A_BlockIndexLen     = 2u;

//160~3159  page1 save diagnostic
const uint16 PAGEADDSTART_0  = 160;
const uint16 PAGEADDEND_0    = 3159;

//3160~4095 page2 save others
const uint16 PAGEADDSTART_1 = 3160;
const uint16 PAGEADDEND_1   = 4095;
//all pages number
//#define	PAGENUMALL           2

const uint8 EA_CrcLength    = 2;


const uint8  FristWriteCheakTab[4]={0x5A,0xA5,0x9F,0xAF};

EaBlockAdminType      EaBlockAdmin[EA_BLOCK_NUM_ALL_DF+1] = {0u};
uint16                PageNextWriteAdd[PAGENUMALL]     = {0u}; //next write address in pagex

/*** Start , DO NOT MODIFY THIS TEXT!!! ***/
/*** Don't write any code pass this line, or it will be deleted during code generation. ***/
/*** ***********************The below lines is generated by tool*********************** ***/
const uint16 EA_VERSION=12;
const EaBlockConfigType EaBlockConfiguration[EA_BLOCK_NUM_ALL_DF+1u]=
{
  {0,0,0,0},
  {/*Block 1*/
    4,/*EaBlockSize*/
    0,/*EaPageNumber*/
    0xff,/*EaNumberOfWriteCycles*/
    EA_BLOCK_NO_MODFIED
  },
  {/*Block 2*/
    32,/*EaBlockSize*/
    0,/*EaPageNumber*/
    0xff,/*EaNumberOfWriteCycles*/
    EA_BLOCK_NO_MODFIED
  },
  {/*Block 3*/
    42,/*EaBlockSize*/
    0,/*EaPageNumber*/
    0xff,/*EaNumberOfWriteCycles*/
    EA_BLOCK_NO_MODFIED
  },

};
const uint16 EA_BLOCK_NUM_ALL = 3;
/*** Generation data:2018-09-12 16:29 ***/
/*** The above lines is generated by tool ***/
/*** End , DO NOT MODIFY THIS TEXT!!! ***/

