/* ###################################################################
**     This component module is generated by Processor Expert. Do not modify it.
**     Filename    : adc1_pal_cfg.c
**     Project     : D532_VAVE_APP
**     Processor   : S32K148_176
**     Component   : adc_pal
**     Version     : Component SDK_S32K14x_08, Driver 01.00, CPU db: 3.00.000
**     Repository  : SDK_S32K14x_08
**     Compiler    : GNU C Compiler
**     Date/Time   : 2020-11-26, 14:42, # CodeGen: 106
**
**     Copyright 1997 - 2015 Freescale Semiconductor, Inc.
**     Copyright 2016-2017 NXP
**     All Rights Reserved.
**     
**     THIS SOFTWARE IS PROVIDED BY NXP "AS IS" AND ANY EXPRESSED OR
**     IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES
**     OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
**     IN NO EVENT SHALL NXP OR ITS CONTRIBUTORS BE LIABLE FOR ANY DIRECT,
**     INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
**     (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
**     SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
**     HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT,
**     STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING
**     IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF
**     THE POSSIBILITY OF SUCH DAMAGE.
** ###################################################################*/
/*!
** @file adc1_pal_cfg.c
** @version 01.00
*/
/*!
**  @addtogroup adc1_pal_cfg_module adc1_pal_cfg module documentation
**  @{
*/

/* MODULE adc1_pal_cfg. */

/**
 * @page misra_violations MISRA-C:2012 violations
 *
 * @section [global]
 * Violates MISRA 2012 Advisory Rule 8.7, External variable could be made static.
 * The external variables will be used in other source files, with the same initialized values.
 */

#include <stddef.h>
#include "adc1_pal_cfg.h"


/*! Configuration 0 declaration */

const adc_config_t adc1_pal_InitConfig = {
    .sampleTicks        = 100,
    .numGroups          = 1,
    .groupConfigArray   = adc1_pal_cfg_GroupArray0,
    .extension          = &adc1_pal_cfg_Extension0
};

extension_adc_s32k1xx_t adc1_pal_cfg_Extension0 = {
    .clockDivide        = ADC_CLK_DIVIDE_1,
    .resolution         = ADC_RESOLUTION_12BIT,
    .inputClock         = ADC_CLK_ALT_1,
    .voltageRef         = ADC_VOLTAGEREF_VREF
};

const adc_group_config_t adc1_pal_cfg_GroupArray0[1u] = {
    /*        inputChannelArray,      resultBuffer,         numChannels,  numSetsResultBuffer,  hwTriggerSupport,  triggerSource,                   continuousConvEn,  callback,                callbackUserData */
    /* 0 */ { adc1_pal_cfg_ChansArray,  adc1_pal_cfg_Results,   4,            1,                    false,              TRGMUX_TRIG_SOURCE_DISABLED,     true,             AdcWrapperIntNotifyCbk,     NULL               },
};

adc_input_chan_t adc1_pal_cfg_ChansArray[4u] = {
    ADC_INPUTCHAN_EXT13,
    ADC_INPUTCHAN_EXT14,
    ADC_INPUTCHAN_EXT15,
    ADC_INPUTCHAN_EXT31,
};
uint16_t adc1_pal_cfg_Results[(4u) * (1u)];


/* END adc1_pal_cfg. */
/*!
** @}
*/
/*
** ###################################################################
**
**     This file was created by Processor Expert 10.1 [05.21]
**     for the Freescale S32K series of microcontrollers.
**
** ###################################################################
*/
