/* ###################################################################
**     This component module is generated by Processor Expert. Do not modify it.
**     Filename    : dmaController_cfg.c
**     Project     : D532_VAVE_APP
**     Processor   : S32K148_176
**     Component   : edma
**     Version     : Component SDK_S32K14x_08, Driver 01.00, CPU db: 3.00.000
**     Repository  : SDK_S32K14x_08
**     Compiler    : GNU C Compiler
**     Date/Time   : 2020-11-26, 14:42, # CodeGen: 106
**
**     Copyright 1997 - 2015 Freescale Semiconductor, Inc.
**     Copyright 2016-2017 NXP
**     All Rights Reserved.
**     
**     THIS SOFTWARE IS PROVIDED BY NXP "AS IS" AND ANY EXPRESSED OR
**     IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES
**     OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
**     IN NO EVENT SHALL NXP OR ITS CONTRIBUTORS BE LIABLE FOR ANY DIRECT,
**     INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
**     (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
**     SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
**     HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT,
**     STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING
**     IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF
**     THE POSSIBILITY OF SUCH DAMAGE.
** ###################################################################*/
/*!
** @file dmaController_cfg.c
** @version 01.00
*/
/*!
**  @addtogroup dmaController_cfg_module dmaController_cfg module documentation
**  @{
*/

/* dmaController_cfg. */

/* MODULE dmaController_cfg.
 *
 * @page misra_violations MISRA-C:2012 violations
 *
 * @section [global]
 * Violates MISRA 2012 Advisory Rule 8.7, External variable could be made static.
 * The external variables will be used in other source files that user initialize
 * to use this module.
 */

#include "dmaController_cfg.h"

edma_state_t dmaController_State;

edma_chn_state_t dmaController1Chn0_State;

edma_chn_state_t dmaController1Chn1_State;

edma_chn_state_t dmaController_cfgChn2_State;

edma_chn_state_t dmaController_cfgChn3_State;

edma_chn_state_t * const edmaChnStateArray[] = {
    &dmaController1Chn0_State,
    &dmaController1Chn1_State,
    &dmaController_cfgChn2_State,
    &dmaController_cfgChn3_State
};

edma_channel_config_t dmaController1Chn0_Config = {
    .priority = EDMA_CHN_DEFAULT_PRIORITY,
    .channel = EDMA_CHN0_NUMBER,
    .source = EDMA_REQ_LPSPI1_RX,
    .callback = NULL,
    .callbackParam = NULL
};

edma_channel_config_t dmaController1Chn1_Config = {
    .priority = EDMA_CHN_DEFAULT_PRIORITY,
    .channel = EDMA_CHN1_NUMBER,
    .source = EDMA_REQ_LPSPI1_TX,
    .callback = NULL,
    .callbackParam = NULL
};

edma_channel_config_t dmaController_cfgChn2_Config = {
    .priority = EDMA_CHN_DEFAULT_PRIORITY,
    .channel = EDMA_CHN2_NUMBER,
    .source = EDMA_REQ_LPSPI0_RX,
    .callback = NULL,
    .callbackParam = NULL
};

edma_channel_config_t dmaController_cfgChn3_Config = {
    .priority = EDMA_CHN_DEFAULT_PRIORITY,
    .channel = EDMA_CHN3_NUMBER,
    .source = EDMA_REQ_LPSPI0_TX,
    .callback = NULL,
    .callbackParam = NULL
};

const edma_channel_config_t * const edmaChnConfigArray[] = {
    &dmaController1Chn0_Config,
    &dmaController1Chn1_Config,
    &dmaController_cfgChn2_Config,
    &dmaController_cfgChn3_Config
};

const edma_user_config_t dmaController_cfg_InitConfig0 = {
  .chnArbitration = EDMA_ARBITRATION_FIXED_PRIORITY,
  .notHaltOnError = false,
};


/* END dmaController_cfg. */

/*!
** @}
*/
/*
** ###################################################################
**
**     This file was created by Processor Expert 10.1 [05.21]
**     for the Freescale S32K series of microcontrollers.
**
** ###################################################################
*/
