/*!Warning!:Please don't modify this file,this is generated by tools!*/
/********************************************************************
File name: System_Task_Cfg.c
Author: Stephen Du
Version: V1.0
Timestamp: 2018-05-15 18:07:11
Description:
Others:
Function List:
1. ....
History: /
1. Date:
Author:
Modification:
2. ...
********************************************************************/
#include "Std_Types.h"
#include "System_Task.h"
#include "System_Task_Cfg.h"

SystemTaskListType SystemTaskList[SYSTEM_TASK_ID_MAX];
const uint16 System_TaskMaxId = SYSTEM_TASK_ID_MAX;

extern void Task_SysMonitor(void * pvParameters);
extern void Task_Alarm(void * pvParameters);
extern void Task_General(void * pvParameters);
extern void Task_Trace(void * pvParameters);
extern void Task_Tp(void * pvParameters);
extern void Task_Dtc(void * pvParameters);
extern void Task_Test(void * pvParameters);

const char Task_Name_SysMonitor[] = {"SysMonitor"};
const char Task_Name_Alarm[] = {"Alarm"};
const char Task_Name_General[] = {"General"};
const char Task_Name_Trace[] = {"Trace"};
const char Task_Name_Tp[] = {"Tp"};
const char Task_Name_Dtc[] = {"Dtc"};
const char Task_Name_Test[] = {"Test"};

SystemTaskConfigType SystemTaskConfig[SYSTEM_TASK_ID_MAX] =
{
	//taskName, priority, stackSize, taskMainFuncPtr, taskParameter, active, queueSize
	{&Task_Name_SysMonitor[0], 7, 256, Task_SysMonitor, NULL, STD_ON, 3},
	{&Task_Name_Alarm[0], 13, 256, Task_Alarm, NULL, STD_ON, 3},
	{&Task_Name_General[0], 7, 512, Task_General, NULL, STD_ON, 3},
	{&Task_Name_Trace[0], 6, 512, Task_Trace, NULL, STD_ON, 3},
	{&Task_Name_Tp[0], 8, 512, Task_Tp, NULL, STD_ON, 3},
	{&Task_Name_Dtc[0], 8, 512, Task_Dtc, NULL, STD_ON, 3},
	{&Task_Name_Test[0], 7, 256, Task_Test, NULL, STD_ON, 3},
};
/*=========================== END OF FILE: System_Task_Cfg.c ===========================*/
