/*!Warning!:Please don't modify this file,this is generated by tools!*/
/********************************************************************
File name: BattVolt_Cfg.h
Author: Stephen Du
Version: V1.0
Timestamp: 2017-01-16 15:55:25
Description:
Others:
Function List:
1. ....
History: /
1. Date:
Author:
Modification:
2. ...
********************************************************************/
#ifndef _BATTVOLT_CFG_H_
#define _BATTVOLT_CFG_H_

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

#include "Std_Types.h"

#define BATTVOLT_DEBUG_TRACE STD_ON

#define BATTVOLT_CONVERT_ALGO(adcValue) ((adcValue * 303) >> 10)//-90 

#define BATTVOLT_FILTER_TIME (10U)

#define BATTVOLT_VOLTRANGE_ULTRALOW_START (0U)

#define BATTVOLT_VOLTRANGE_LOW_START (550U)
#define BATTVOLT_THRESHOLD_ULTRALOW (575U)
#define BATTVOLT_VOLTRANGE_ULTRALOW_END (600U)

#define BATTVOLT_VOLTRANGE_NORMAL_START (850U)
#define BATTVOLT_THRESHOLD_LOW (875U)
#define BATTVOLT_VOLTRANGE_LOW_END (900U)

#define BATTVOLT_VOLTRANGE_HIGH_START (1600U)
#define BATTVOLT_THRESHOLD_HIGH (1625U)
#define BATTVOLT_VOLTRANGE_NORMAL_END (1650U)

#define BATTVOLT_VOLTRANGE_ULTRAHIGH_START (1730U)
#define BATTVOLT_THRESHOLD_ULTRAHIGH (1755U)
#define BATTVOLT_VOLTRANGE_HIGH_END (1780U)

#define BATTVOLT_VOLTRANGE_ULTRAHIGH_END (2200U)

#ifdef __cplusplus
}
#endif // __cplusplus

#endif
