/*!Warning!:Please don't modify this file,this is generated by tools!*/
/********************************************************************
File name: BattVolt.c
Author: Stephen Du
Version: V1.0
Timestamp: 2017-01-16 15:55:25
Description:
Others:
Function List:
1. ....
History: /
1. Date:
Author:
Modification:
2. ...
********************************************************************/
#include "BattVoltage.h"
#include "BattVoltage_Cfg.h"
#include "System_Signal.h"
#include "adc_wrapper_if.h"
#if(STD_ON == BATTVOLT_DEBUG_TRACE)
#include "trace.h"
#endif

typedef struct
{
    uint16 Start;
    uint16 End;
} BattVolt_VoltRangeType;

typedef struct
{
    boolean Init;
    uint8 Status;
} BattVolt_ManageType;

static BattVolt_ManageType BattVolt_Manager =
{
    STD_OFF, BATTVOLT_STATE_NORMAL
};

static BattVolt_VoltRangeType BattVolt_VoltRange[BATTVOLT_STATE_MAX] =
{
    {BATTVOLT_VOLTRANGE_ULTRALOW_START, BATTVOLT_VOLTRANGE_ULTRALOW_END},
    {BATTVOLT_VOLTRANGE_LOW_START, BATTVOLT_VOLTRANGE_LOW_END},
    {BATTVOLT_VOLTRANGE_NORMAL_START, BATTVOLT_VOLTRANGE_NORMAL_END},
    {BATTVOLT_VOLTRANGE_HIGH_START, BATTVOLT_VOLTRANGE_HIGH_END},
    {BATTVOLT_VOLTRANGE_ULTRAHIGH_START, BATTVOLT_VOLTRANGE_ULTRAHIGH_END}
};

/*
*@par Service ID[hex]
*0X3
*@par Sync/Async
*Synchronous
*@par Reentrancy
*Reentrant
*@param[in] None
*
*@param[inout] None
*
*@param[out] VoltageValue
*
*@retval E_OK/E_NOT_OK
*
*Service to get the voltage value;
*/
Std_ReturnType BattVolt_GetVoltage(uint16 *VoltageValue)
{
    uint16 l_adcValue = 0u;
    Std_ReturnType l_returnValue = E_NOT_OK;

    if (STD_ON == BattVolt_Manager.Init)
    {
		if(AdcWrapper_Read(0,ADC_CH_SYSTEM_VOLTAGE,&l_adcValue) == TRUE)
		{
        	*VoltageValue = BATTVOLT_CONVERT_ALGO(l_adcValue);
			l_returnValue = E_OK;
		}
    }
    return (l_returnValue);
}

static Std_ReturnType BattVolt_GetInternalState(uint8 * state)
{
    Std_ReturnType l_returnValue = E_NOT_OK;
    uint16 l_battValue = 0;

    if (STD_ON == BattVolt_Manager.Init)
    {
        if (E_OK == BattVolt_GetVoltage(&l_battValue))
        {
            if ((l_battValue <= BattVolt_VoltRange[BattVolt_Manager.Status].Start)
                    || (l_battValue >= BattVolt_VoltRange[BattVolt_Manager.Status].End))
            {
                if (l_battValue < BATTVOLT_THRESHOLD_ULTRALOW)
                {
                    *state = BATTVOLT_STATE_ULTRALOW;
                }
                else if (l_battValue < BATTVOLT_THRESHOLD_LOW)
                {
                    *state = BATTVOLT_STATE_LOW;
                }
                else if (l_battValue < BATTVOLT_THRESHOLD_HIGH)
                {
                    *state = BATTVOLT_STATE_NORMAL;
                }
                else if (l_battValue < BATTVOLT_THRESHOLD_ULTRAHIGH)
                {
                    *state = BATTVOLT_STATE_HIGH;
                }
                else
                {
                    *state = BATTVOLT_STATE_ULTRAHIGH;
                }
                l_returnValue = E_OK;
            }
        }
    }
    return (l_returnValue);
}

/*
*@par Service ID[hex]
*0X0
*@par Sync/Async
*Synchronous
*@par Reentrancy
*Reentrant
*@param[in] None
*
*@param[inout] None
*
*@param[out] None
*
*@retval None
*
*Service to initialize the module;
*You must call this function first before you call the others.
*/
void BattVolt_Init(void)
{
    if (STD_OFF == BattVolt_Manager.Init)
    {
        BattVolt_Manager.Init = STD_ON;
    }
}

/*
*@par Service ID[hex]
*0X1
*@par Sync/Async
*Synchronous
*@par Reentrancy
*Reentrant
*@param[in] None
*
*@param[inout] None
*
*@param[out] None
*
*@retval None
*
*Scanf the signal periodically and do the debouncer.
*/
void BattVolt_Scan(void)
{
    uint8 l_portState;
    boolean l_TxState;
    static uint8 l_sampleCounter = BATTVOLT_FILTER_TIME;

    if (STD_ON == BattVolt_Manager.Init)
    {
        if (E_OK == BattVolt_GetInternalState(&l_portState))
        {
            if (0 != l_sampleCounter)
            {
                l_sampleCounter--;
            }
            if ((0 == l_sampleCounter) && (BattVolt_Manager.Status != l_portState))
            {
                BattVolt_Manager.Status = l_portState;
                l_TxState = System_Signal_Send(SYSTEM_SIG_ID_BATTVOLT_STATUS, BattVolt_Manager.Status, STD_OFF);
#if (STD_ON == BATTVOLT_DEBUG_TRACE)
                TracePrintf(SYSTEM_TRACE, TRACE_INFO, "[Power-I]>Batt Voltage Changed:%d,Tx:%d\r\n", BattVolt_Manager.Status, l_TxState);
#endif
            }
            if (l_portState == BattVolt_Manager.Status)
            {
                l_sampleCounter = BATTVOLT_FILTER_TIME;
            }
        }
    }
}

/*
*@par Service ID[hex]
*0X2
*@par Sync/Async
*Synchronous
*@par Reentrancy
*Reentrant
*@param[in] None
*
*@param[inout] None
*
*@param[out] None
*
*@retval BATTVOLT_STATE_ULTRALOW: Batt voltage is ultra low.
*@retval BATTVOLT_STATE_LOW: Batt voltage is low.
*@retval BATTVOLT_STATE_NORMAL: Batt voltage is normal.
*@retval BATTVOLT_STATE_HIGH: Batt voltage is high.
*@retval BATTVOLT_STATE_ULTRAHIGH: Batt voltage is ultra high.
*
*Call this function to register user callback.
*/
uint8 BattVolt_GetStatus(void)
{
    return (BattVolt_Manager.Status);
}

/*
*@par Service ID[hex]
*0X4
*@par Sync/Async
*Synchronous
*@par Reentrancy
*Reentrant
*@param[in] None
*
*@param[inout] None
*
*@param[out] None
*
*@retval None
*
*Service to deinitialize the module;
*/
void BattVolt_Deinit(void)
{
    if (STD_ON == BattVolt_Manager.Init)
    {
        //CALL AD API
        BattVolt_Manager.Init = STD_OFF;
    }
}
