/*!Warning!:Please don't modify this file,this is generated by tools!*/
/********************************************************************
File name: Task_DiagApp_Cfg.h
Author: Stephen Du
Version: V1.0
Timestamp: 2019-01-03 16:47:37
Description:
Others:
Function List:
1. ....
History: /
1. Date:
Author:
Modification:
2. ...
********************************************************************/
#ifndef _TASK_DIAGAPP_CFG_H_
#define _TASK_DIAGAPP_CFG_H_

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

#include "Std_Types.h"

#define TASK_DIAGAPP_DEBUG_TRACE STD_OFF
#define TASK_DIAGAPP_STACK_MONITOR STD_OFF

#ifdef __cplusplus
}
#endif // __cplusplus

#endif
/*=========================== END OF FILE: Task_DiagApp_Cfg.h ===========================*/
