/*!Warning!:Please don't modify this file,this is generated by tools!*/
/********************************************************************
File name: VirtualSig_Cfg.c
Author: Stephen Du
Version: V1.0
Timestamp: 2018-05-07 19:30:33
Description:
Others:
Function List:
1. ....
History: /
1. Date:
Author:
Modification:
2. ...
********************************************************************/
#include "Std_Types.h"
#include "VirtualSig.h"
#include "VirtualSig_Cfg.h"

const uint16 VirtualSig_MaxId = VIRTUALSIG_ID_MAX;
VirtualSig_RuntimeInfoType VirtualSig_RuntimeInfo[VIRTUALSIG_ID_MAX];

#define VIRTUALSIG_REGMAX_DIAGCMD (3U)
#define VIRTUALSIG_REGMAX_NM_WAKEUP (1U)
#define VIRTUALSIG_REGMAX_BUS_SLEEP (1U)
#define VIRTUALSIG_REGMAX_VOLTSTATE (1U)
#define VIRTUALSIG_REGMAX_RESTART (1U)
#define VIRTUALSIG_REGMAX_UDS_REQ (1U)
#define VIRTUALSIG_REGMAX_TEMPAMP_STATUS (1U)
#define VIRTUALSIG_REGMAX_TEMPBOARD_STATUS (1U)
#define VIRTUALSIG_REGMAX_BATTVOLT_STATUS (1U)

static VirtualSig_RegTaskInfoType VirtualSig_DIAGCMD[VIRTUALSIG_REGMAX_DIAGCMD];
static VirtualSig_RegTaskInfoType VirtualSig_NM_WAKEUP[VIRTUALSIG_REGMAX_NM_WAKEUP];
static VirtualSig_RegTaskInfoType VirtualSig_BUS_SLEEP[VIRTUALSIG_REGMAX_BUS_SLEEP];
static VirtualSig_RegTaskInfoType VirtualSig_VOLTSTATE[VIRTUALSIG_REGMAX_VOLTSTATE];
static VirtualSig_RegTaskInfoType VirtualSig_RESTART[VIRTUALSIG_REGMAX_RESTART];
static VirtualSig_RegTaskInfoType VirtualSig_UDS_REQ[VIRTUALSIG_REGMAX_UDS_REQ];
static VirtualSig_RegTaskInfoType VirtualSig_TEMPAMP_STATUS[VIRTUALSIG_REGMAX_TEMPAMP_STATUS];
static VirtualSig_RegTaskInfoType VirtualSig_TEMPBOARD_STATUS[VIRTUALSIG_REGMAX_TEMPBOARD_STATUS];
static VirtualSig_RegTaskInfoType VirtualSig_BATTVOLT_STATUS[VIRTUALSIG_REGMAX_BATTVOLT_STATUS];

VirtualSig_CfgInfoType VirtualSig_CfgInfo[VIRTUALSIG_ID_MAX] =
{
	{STD_ON, VIRTUALSIG_REGMAX_DIAGCMD, VirtualSig_DIAGCMD},
	{STD_ON, VIRTUALSIG_REGMAX_NM_WAKEUP, VirtualSig_NM_WAKEUP},
	{STD_ON, VIRTUALSIG_REGMAX_BUS_SLEEP, VirtualSig_BUS_SLEEP},
	{STD_ON, VIRTUALSIG_REGMAX_VOLTSTATE, VirtualSig_VOLTSTATE},
	{STD_ON, VIRTUALSIG_REGMAX_RESTART, VirtualSig_RESTART},
	{STD_ON, VIRTUALSIG_REGMAX_UDS_REQ, VirtualSig_UDS_REQ},
	{STD_OFF, VIRTUALSIG_REGMAX_TEMPAMP_STATUS, VirtualSig_TEMPAMP_STATUS},
	{STD_OFF, VIRTUALSIG_REGMAX_TEMPBOARD_STATUS, VirtualSig_TEMPBOARD_STATUS},
	{STD_OFF, VIRTUALSIG_REGMAX_BATTVOLT_STATUS, VirtualSig_BATTVOLT_STATUS},
};
/*=========================== END OF FILE: VirtualSig_Cfg.c ===========================*/
