/*!Warning!:Please don't modify this file,this is generated by tools!*/
/********************************************************************
File name: BinSig_Tcu_Acc.c
Author: Stephen Du
Version: V2.0
Timestamp: 2018-10-23 10:38:12
Description:
Others:
Function List:
1. ....
History: /
1. Date:
Author:
Modification:
2. ...
********************************************************************/
#if(STD_ON == BINSIG_TCU_ACC_MODULE_ACTIVE)
#include "BinSig_Tcu_Acc_Cfg.h"
#include "System_Signal.h"
#include "trace.h"

#define BINSIG_TCU_ACC_INITIALIZE 0XFFFFFFFF
#endif

/*
*@par Service ID[hex]
*0X0
*@par Sync/Async
*Synchronous
*@par Reentrancy
*Reentrant
*@param[in] None
*
*@param[inout] None
*
*@param[out] None
*
*@retval None
*
*Scanf the signal periodically and do the debouncer.
*/
void BinSig_Tcu_Acc_Scan(void)
{
#if(STD_ON == BINSIG_TCU_ACC_MODULE_ACTIVE)
    boolean l_portState;
    static uint8 l_sampleCounter = BINSIG_TCU_ACC_FILTER_TIME;
    uint32 l_value = BINSIG_TCU_ACC_INITIALIZE;

    l_portState = BINSIG_TCU_ACC_GET_PORT_VALUE;
    if (0 != l_sampleCounter) {
        l_sampleCounter--;
    }
    if (0 == l_sampleCounter) {
        if ((E_OK == System_Signal_Receive(SYSTEM_SIG_ID_TCU_ACC, &l_value)) && (l_value != l_portState)) {
#if (STD_ON == BINSIG_TCU_ACC_DEBUG_TRACE)
            TracePrintf(INPUT_TRACE, TRACE_INFO, "[BinSig-I]:Signal Tcu_Acc state changed\r\n");
#endif
            System_Signal_Send(SYSTEM_SIG_ID_TCU_ACC, l_portState, STD_OFF);
        }
    }
    if ((E_OK == System_Signal_Receive(SYSTEM_SIG_ID_TCU_ACC, &l_value)) && (l_value == l_portState)) {
        l_sampleCounter = BINSIG_TCU_ACC_FILTER_TIME;
    }
#endif
}
/*=========================== END OF FILE: BinSig_Tcu_Acc.c ===========================*/
