#ifndef _DTC_CORE_CFG_H
#define _DTC_CORE_CFG_H

#include"dtcCore.h"

#define DTC_20_PERCENT_STORED_NUM 4

typedef enum _tSnapshortType{
	GLOBAL_SNAPSHORT_RECORED_NUM = 1,
	LOCAL_SNAPSHORT_RECORD_NUM = 2,
	ALL_SNAPSHORT_RECORD_NUM = 0xff,
}tSnapshortType;

typedef enum {
	GLOBAL_EXTENDED_DATA_RECORED_NUM = 1,
	LOCAL_EXTENDED_DATA_RECORD_NUM = 2,
	ALL_EXTENDED_DATA_RECORD_NUM = 0xff,
}tDtcExtDataRecordNum;


typedef enum{
	// TODO:DON'T CHANGE THE ORDER*/
 	EXT_DTC_ID_VOLTAGE_TOO_LOW = 0xA0A016,
	EXT_DTC_ID_VOLTAGE_TOO_HIGH = 0xA0A017,
	EXT_DTC_ID_CAN_BUS_OFF = 0xC07388,
	EXT_DTC_ID_LOST_COMMUNICATION_WITH_WCT = 0xD10587,
	EXT_DTC_ID_LOST_COMMUNICATION_WITH_BZS = 0xD10487,
	EXT_DTC_ID_LOST_COMMUNICATION_WITH_IPC = 0xC15587,
	EXT_DTC_ID_LOST_COMMUNICATION_WITH_TPMS = 0xC12787, 
	EXT_DTC_ID_SYSTEM_BOOT_ERROR = 0xA0B004,
	EXT_DTC_ID_MP5_CALIBRATION_FILE_ERROR = 0xA0B104,
}tExtDTCId;

typedef enum{
	// TODO:DON'T CHANGE THE ORDER*/
	INNER_DTC_ID_VOLTAGE_TOO_LOW = 0,
	INNER_DTC_ID_VOLTAGE_TOO_HIGH = 1,
	INNER_DTC_ID_CAN_BUS_OFF = 2,
	INNER_DTC_ID_LOST_COMMUNICATION_WITH_WCT = 3,
	INNER_DTC_ID_LOST_COMMUNICATION_WITH_BZS = 4,
	INNER_DTC_ID_LOST_COMMUNICATION_WITH_IPC = 5,
	INNER_DTC_ID_LOST_COMMUNICATION_WITH_TPMS = 6,
	INNER_DTC_ID_SYSTEM_BOOT_ERROR = 7,
	INNER_DTC_ID_MP5_CALIBRATION_FILE_ERROR = 8,

}tInnerDTCId;

#endif
