/*!Warning!:Please don't modify this file,this is generated by tools!*/
/********************************************************************
File name: Com_Cfg.h
Author: Stephen Du
Version: V2.0
Timestamp: 2020-06-05 17:20:10
Description:
Others:
Function List:
1. ....
History: /
1. Date:
Author:
Modification:
2. ...
********************************************************************/
#ifndef _COM_CFG_H_
#define _COM_CFG_H_

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus
/*===============================================================================*/
/*=========================== START: HEAD FILE INCLUDE ==========================*/
/*===============================================================================*/
#include "ComStack_Types.h"

/*===============================================================================*/
/*============================ END: HEAD FILE INCLUDE ===========================*/
/*===============================================================================*/

/*===============================================================================*/
/*========================== START: GLOBAL MACRO DEFINE =========================*/
/*===============================================================================*/
#define COM_DEV_ERROR_DETECT STD_OFF

#define COM_NOTUSED_BUF_PADDING 0XFFU

#define COM_CONFIGURATION_ID (2006051716)

#define COM_CONFIGURATION_TIMEBASE (10U)//minimum delay time

#define USE_RX_SIG_FILTER STD_ON
#define USE_TX_SIG_FILTER STD_ON

//#define COM_INTERNAL_COMMUNICATON
#define COM_RX_TEMP_BUFFER_SIZE (64U)

/*===============================================================================*/
/*=========================== END: GLOBAL MACRO DEFINE ==========================*/
/*===============================================================================*/

/*===============================================================================*/
/*============================ START: IPDU HANDLE ===============================*/
/*===============================================================================*/
/******************************* Rx IPDU HANDLE **********************************/
#define COM_RX_IPDU_START_INDEX (0U)

/*MessageID: 0X2   MessageName: LWSOUT_M2   CycTime: 10mS*/
#define IPDU_HND_LWSOUT_M2 (0U)

/*MessageID: 0X2A   MessageName: ACU_GeneralStatus_6   CycTime: 100mS*/
#define IPDU_HND_ACU_GeneralStatus_6 (1U)

/*MessageID: 0X11A   MessageName: ShBW_GeneralStatus   CycTime: 10mS*/
#define IPDU_HND_ShBW_GeneralStatus (2U)

/*MessageID: 0X11B   MessageName: SCU_GeneralStatus   CycTime: 10mS*/
#define IPDU_HND_SCU_GeneralStatus (3U)

/*MessageID: 0X160   MessageName: ECM_TorqueControl_RN2   CycTime: 10mS*/
#define IPDU_HND_ECM_TorqueControl_RN2 (4U)

/*MessageID: 0X180   MessageName: ECM_TorqueControl_RN1   CycTime: 10mS*/
#define IPDU_HND_ECM_TorqueControl_RN1 (5U)

/*MessageID: 0X182   MessageName: ECM_TorqueControl_N1   CycTime: 10mS*/
#define IPDU_HND_ECM_TorqueControl_N1 (6U)

/*MessageID: 0X1F9   MessageName: ECM_SystemControl_1f9   CycTime: 10mS*/
#define IPDU_HND_ECM_SystemControl_1f9 (7U)

/*MessageID: 0X218   MessageName: PEPS_Message_Sts   CycTime: 20mS*/
#define IPDU_HND_PEPS_Message_Sts (8U)

/*MessageID: 0X245   MessageName: Brake_StabilityControl_RN1   CycTime: 20mS*/
#define IPDU_HND_Brake_StabilityControl_RN1 (9U)

/*MessageID: 0X284   MessageName: Front_Wheel_Speed_Frame   CycTime: 20mS*/
#define IPDU_HND_Front_Wheel_Speed_Frame (10U)

/*MessageID: 0X2B1   MessageName: ITS_InfoStatus_N1   CycTime: 20mS*/
#define IPDU_HND_ITS_InfoStatus_N1 (11U)

/*MessageID: 0X2B7   MessageName: ITS_InfoStatus_N2   CycTime: 20mS*/
#define IPDU_HND_ITS_InfoStatus_N2 (12U)

/*MessageID: 0X2C8   MessageName: SRR_Left   CycTime: 50mS*/
#define IPDU_HND_SRR_Left (13U)

/*MessageID: 0X2C9   MessageName: SRR_Right   CycTime: 50mS*/
#define IPDU_HND_SRR_Right (14U)

/*MessageID: 0X351   MessageName: SMART_bcmMSG_PUSH   CycTime: 100mS*/
#define IPDU_HND_SMART_bcmMSG_PUSH (15U)

/*MessageID: 0X352   MessageName: IKEY_352   CycTime: 100mS*/
#define IPDU_HND_IKEY_352 (16U)

/*MessageID: 0X354   MessageName: Brake_GeneralData   CycTime: 40mS*/
#define IPDU_HND_Brake_GeneralData (17U)

/*MessageID: 0X358   MessageName: BCMMSG1   CycTime: 100mS*/
#define IPDU_HND_BCMMSG1 (18U)

/*MessageID: 0X35A   MessageName: BCM_SystemControl_2   CycTime: 100mS*/
#define IPDU_HND_BCM_SystemControl_2 (19U)

/*MessageID: 0X35D   MessageName: BCM_SystemControl   CycTime: 100mS*/
#define IPDU_HND_BCM_SystemControl (20U)

/*MessageID: 0X385   MessageName: TPMS_GeneralStatus_BCM   CycTime: 100mS*/
#define IPDU_HND_TPMS_GeneralStatus_BCM (21U)

/*MessageID: 0X421   MessageName: ATCVT_to_MMI_RN1   CycTime: 60mS*/
#define IPDU_HND_ATCVT_to_MMI_RN1 (22U)

/*MessageID: 0X4CB   MessageName: ITS_InfoStatus_N3_7b   CycTime: 100mS*/
#define IPDU_HND_ITS_InfoStatus_N3_7b (23U)

/*MessageID: 0X4CC   MessageName: ITS_InfoStatus_N2_1   CycTime: 100mS*/
#define IPDU_HND_ITS_InfoStatus_N2_1 (24U)

/*MessageID: 0X502   MessageName: RETREIVE_ASSIST_POWER_48V   CycTime: 50mS*/
#define IPDU_HND_RETREIVE_ASSIST_POWER_48V (25U)

/*MessageID: 0X54C   MessageName: CLIMATE_ControlData_F   CycTime: 100mS*/
#define IPDU_HND_CLIMATE_ControlData_F (26U)

/*MessageID: 0X551   MessageName: ECM_GeneralStatus   CycTime: 100mS*/
#define IPDU_HND_ECM_GeneralStatus (27U)

/*MessageID: 0X563   MessageName: DCM_GeneralStatus_5   CycTime: 100mS*/
#define IPDU_HND_DCM_GeneralStatus_5 (28U)

/*MessageID: 0X57A   MessageName: SONAR_GeneralStatus_8   CycTime: 100mS*/
#define IPDU_HND_SONAR_GeneralStatus_8 (29U)

/*MessageID: 0X580   MessageName: ECM_to_ITM   CycTime: 100mS*/
#define IPDU_HND_ECM_to_ITM (30U)

/*MessageID: 0X58A   MessageName: EPB_SystemControl   CycTime: 20mS*/
#define IPDU_HND_EPB_SystemControl (31U)

/*MessageID: 0X5C8   MessageName: S_BOX_ControlData_SetPM   CycTime: 100mS*/
#define IPDU_HND_S_BOX_ControlData_SetPM (32U)

/*MessageID: 0X5CA   MessageName: S_BOX_ControlData_enjoy   CycTime: 100mS*/
#define IPDU_HND_S_BOX_ControlData_enjoy (33U)

/*MessageID: 0X5CB   MessageName: S_BOX_ControlData_AC   CycTime: 100mS*/
#define IPDU_HND_S_BOX_ControlData_AC (34U)

/*MessageID: 0X5E4   MessageName: EPS_GeneralStatus   CycTime: 100mS*/
#define IPDU_HND_EPS_GeneralStatus (35U)

/*MessageID: 0X5E8   MessageName: TPMS_GeneralStatus2   CycTime: 500mS*/
#define IPDU_HND_TPMS_GeneralStatus2 (36U)

/*MessageID: 0X5E9   MessageName: APA_HMI_system   CycTime: 100mS*/
#define IPDU_HND_APA_HMI_system (37U)

/*MessageID: 0X60D   MessageName: BCM_GeneralStatus   CycTime: 100mS*/
#define IPDU_HND_BCM_GeneralStatus (38U)

/*MessageID: 0X625   MessageName: USM_GeneralStatus   CycTime: 100mS*/
#define IPDU_HND_USM_GeneralStatus (39U)

/*MessageID: 0X628   MessageName: LowWarningSignal628   CycTime: 100mS*/
#define IPDU_HND_LowWarningSignal628 (40U)

/*MessageID: 0X629   MessageName: LOW_WNG_STATUS_629   CycTime: 100mS*/
#define IPDU_HND_LOW_WNG_STATUS_629 (41U)

/*MessageID: 0X6E2   MessageName: ECCSMSG8_OBD_IS   CycTime: 100mS*/
#define IPDU_HND_ECCSMSG8_OBD_IS (42U)

#define COM_RX_IPDU_MAX_NUM (43U)
#define COM_TX_IPDU_START_INDEX (43U)

/******************************* Tx IPDU HANDLE **********************************/
/*MessageID: 0X280   MessageName: CLUSTER_BasicInfo_1   CycTime: 20mS*/
#define IPDU_HND_CLUSTER_BasicInfo_1 (43U)

/*MessageID: 0X2DE   MessageName: METMSG1   CycTime: 10mS*/
#define IPDU_HND_METMSG1 (44U)

/*MessageID: 0X355   MessageName: CLUSTER_BasicInfo_2   CycTime: 40mS*/
#define IPDU_HND_CLUSTER_BasicInfo_2 (45U)

/*MessageID: 0X447   MessageName: DA_Information   CycTime: 0mS*/
#define IPDU_HND_DA_Information (46U)

/*MessageID: 0X4F8   MessageName: CLUSTER_BasicInfo_3   CycTime: 100mS*/
#define IPDU_HND_CLUSTER_BasicInfo_3 (47U)

/*MessageID: 0X567   MessageName: SystemTimeInfo   CycTime: 500mS*/
#define IPDU_HND_SystemTimeInfo (48U)

/*MessageID: 0X5A8   MessageName: DA_ControlData   CycTime: 100mS*/
#define IPDU_HND_DA_ControlData (49U)

/*MessageID: 0X5B7   MessageName: CLIMATE_ControlData   CycTime: 100mS*/
#define IPDU_HND_CLIMATE_ControlData (50U)

/*MessageID: 0X5C5   MessageName: CLUSTER_GeneralStatus   CycTime: 100mS*/
#define IPDU_HND_CLUSTER_GeneralStatus (51U)

/*MessageID: 0X5E5   MessageName: IKEY_Display_SwitchStatus   CycTime: 100mS*/
#define IPDU_HND_IKEY_Display_SwitchStatus (52U)

/*MessageID: 0X5FE   MessageName: TCU_DA_information   CycTime: 100mS*/
#define IPDU_HND_TCU_DA_information (53U)

/*MessageID: 0X602   MessageName: CLUSTER_WakeUpFrame   CycTime: 0mS*/
#define IPDU_HND_CLUSTER_WakeUpFrame (54U)

/*MessageID: 0X635   MessageName: DA_WakeUpFrame   CycTime: 0mS*/
#define IPDU_HND_DA_WakeUpFrame (55U)

#define COM_TX_IPDU_MAX_NUM (13U)
#define COM_IPDU_MAX_NUM (56U)

/*===============================================================================*/
/*============================== END: IPDU HANDLE ===============================*/
/*===============================================================================*/

/*===============================================================================*/
/*========================== START: IPDU GROUP HANDLE ===========================*/
/*===============================================================================*/
/***************************** Rx IPDU GROUP HANDLE ******************************/
#define COM_IPDUGROUP_HND_RX (0U)

#define COM_RX_IPDUGROUP_MAX_NUM (1U)

#define COM_TX_IPDUGROUP_START_INDEX COM_RX_IPDUGROUP_MAX_NUM
/***************************** Tx IPDU GROUP HANDLE ******************************/
#define COM_IPDUGROUP_HND_TX (1U)

#define COM_TX_IPDUGROUP_MAX_NUM (1U)
#define COM_IPDUGROUP_MAX_NUM (2U)
/*===============================================================================*/
/*========================== END: IPDU GROUP HANDLE =============================*/
/*===============================================================================*/

/*===============================================================================*/
/*============================ START: SIGNAL HANDLE =============================*/
/*===============================================================================*/
/****************************** Rx Signal Handle *********************************/
/*********************************************************************************/
/*MessageID: 0X2   MessageHandle: IPDU_HND_LWSOUT_M2   CycTime: 10mS*/
/*SignalName: STRANGLE
  Endian:Motor  Type:Sint16  StartBit:7  Length:16*/
#define SIG_HND_STRANGLE (0U)

/*SignalName: STRSPEED
  Endian:Motor  Type:Uint8  StartBit:23  Length:8*/
#define SIG_HND_STRSPEED (1U)

/*SignalName: LWSCAL
  Endian:Motor  Type:Boolean  StartBit:25  Length:1*/
#define SIG_HND_LWSCAL (2U)

/*SignalName: LWSOK
  Endian:Motor  Type:Boolean  StartBit:24  Length:1*/
#define SIG_HND_LWSOK (3U)

/*SignalName: CHCKSUM
  Endian:Motor  Type:Uint8  StartBit:39  Length:4*/
#define SIG_HND_CHCKSUM (4U)

/*SignalName: MSGCOUNT
  Endian:Motor  Type:Uint8  StartBit:35  Length:4*/
#define SIG_HND_MSGCOUNT (5U)

/*SignalName: LWSTRIM
  Endian:Motor  Type:Boolean  StartBit:26  Length:1*/
#define SIG_HND_LWSTRIM (6U)

/*********************************************************************************/

/*********************************************************************************/
/*MessageID: 0X2A   MessageHandle: IPDU_HND_ACU_GeneralStatus_6   CycTime: 100mS*/
/*SignalName: AIRBAG_FAIL
  Endian:Motor  Type:Boolean  StartBit:16  Length:1*/
#define SIG_HND_AIRBAG_FAIL (7U)

/*SignalName: Second_ROW_L_BELT_STA
  Endian:Motor  Type:Uint8  StartBit:39  Length:2*/
#define SIG_HND_Second_ROW_L_BELT_STA (8U)

/*SignalName: Second_ROW_C_BELT_STA
  Endian:Motor  Type:Uint8  StartBit:37  Length:2*/
#define SIG_HND_Second_ROW_C_BELT_STA (9U)

/*SignalName: Second_ROW_R_BELT_STA
  Endian:Motor  Type:Uint8  StartBit:35  Length:2*/
#define SIG_HND_Second_ROW_R_BELT_STA (10U)

/*********************************************************************************/

/*********************************************************************************/
/*MessageID: 0X11A   MessageHandle: IPDU_HND_ShBW_GeneralStatus   CycTime: 10mS*/
/*SignalName: SBW_FALSTAT
  Endian:Motor  Type:Uint8  StartBit:9  Length:2*/
#define SIG_HND_SBW_FALSTAT (11U)

/*SignalName: REFUSE_BUZZER
  Endian:Motor  Type:Boolean  StartBit:10  Length:1*/
#define SIG_HND_REFUSE_BUZZER (12U)

/*SignalName: SBW_WARNING_MSG
  Endian:Motor  Type:Uint8  StartBit:21  Length:3*/
#define SIG_HND_SBW_WARNING_MSG (13U)

/*********************************************************************************/

/*********************************************************************************/
/*MessageID: 0X11B   MessageHandle: IPDU_HND_SCU_GeneralStatus   CycTime: 10mS*/
/*SignalName: SCU_WARNING_MSG_11B
  Endian:Motor  Type:Uint8  StartBit:21  Length:3*/
#define SIG_HND_SCU_WARNING_MSG_11B (14U)

/*SignalName: ALARM_BUZZER
  Endian:Motor  Type:Boolean  StartBit:10  Length:1*/
#define SIG_HND_ALARM_BUZZER (15U)

/*********************************************************************************/

/*********************************************************************************/
/*MessageID: 0X160   MessageHandle: IPDU_HND_ECM_TorqueControl_RN2   CycTime: 10mS*/
/*SignalName: IDSTSTS
  Endian:Motor  Type:Boolean  StartBit:30  Length:1*/
#define SIG_HND_IDSTSTS (16U)

/*SignalName: ISACT
  Endian:Motor  Type:Boolean  StartBit:29  Length:1*/
#define SIG_HND_ISACT (17U)

/*********************************************************************************/

/*********************************************************************************/
/*MessageID: 0X180   MessageHandle: IPDU_HND_ECM_TorqueControl_RN1   CycTime: 10mS*/
/*SignalName: TACHO
  Endian:Motor  Type:Uint16  StartBit:7  Length:16*/
#define SIG_HND_TACHO (18U)

/*SignalName: SHIFT_IND
  Endian:Motor  Type:Uint8  StartBit:57  Length:2*/
#define SIG_HND_SHIFT_IND (19U)

/*SignalName: RawPedal_APOFS
  Endian:Motor  Type:Uint16  StartBit:47  Length:10*/
#define SIG_HND_RawPedal_APOFS (20U)

/*********************************************************************************/

/*********************************************************************************/
/*MessageID: 0X182   MessageHandle: IPDU_HND_ECM_TorqueControl_N1   CycTime: 10mS*/
/*SignalName: VirtualAcceleratorAngle_ForTM
  Endian:Motor  Type:Uint8  StartBit:39  Length:8*/
#define SIG_HND_VirtualAcceleratorAngle_ForTM (21U)

/*********************************************************************************/

/*********************************************************************************/
/*MessageID: 0X1F9   MessageHandle: IPDU_HND_ECM_SystemControl_1f9   CycTime: 10mS*/
/*SignalName: EngineStatus_1f9
  Endian:Motor  Type:Uint8  StartBit:5  Length:2*/
#define SIG_HND_EngineStatus_1f9 (22U)

/*SignalName: ECM_48V_Status_Display
  Endian:Motor  Type:Uint8  StartBit:34  Length:3*/
#define SIG_HND_ECM_48V_Status_Display (23U)

/*********************************************************************************/

/*********************************************************************************/
/*MessageID: 0X218   MessageHandle: IPDU_HND_PEPS_Message_Sts   CycTime: 20mS*/
/*SignalName: PEPS_REMOTE_STS
  Endian:Motor  Type:Boolean  StartBit:0  Length:1*/
#define SIG_HND_PEPS_REMOTE_STS (24U)

/*SignalName: Remote_disable_start
  Endian:Motor  Type:Boolean  StartBit:15  Length:1*/
#define SIG_HND_Remote_disable_start (25U)

/*********************************************************************************/

/*********************************************************************************/
/*MessageID: 0X245   MessageHandle: IPDU_HND_Brake_StabilityControl_RN1   CycTime: 20mS*/
/*SignalName: VDCFAIL
  Endian:Motor  Type:Boolean  StartBit:25  Length:1*/
#define SIG_HND_VDCFAIL (26U)

/*SignalName: MSGCNTRR
  Endian:Motor  Type:Uint8  StartBit:39  Length:8*/
#define SIG_HND_MSGCNTRR (27U)

/*********************************************************************************/

/*********************************************************************************/
/*MessageID: 0X284   MessageHandle: IPDU_HND_Front_Wheel_Speed_Frame   CycTime: 20mS*/
/*SignalName: VSO
  Endian:Motor  Type:Uint16  StartBit:39  Length:16*/
#define SIG_HND_VSO (28U)

/*SignalName: WRFR
  Endian:Motor  Type:Uint16  StartBit:7  Length:16*/
#define SIG_HND_WRFR (29U)

/*SignalName: WRFL
  Endian:Motor  Type:Uint16  StartBit:23  Length:16*/
#define SIG_HND_WRFL (30U)

/*SignalName: MessageCounterFront
  Endian:Motor  Type:Uint8  StartBit:55  Length:8*/
#define SIG_HND_MessageCounterFront (31U)

/*SignalName: CHKSUMFR
  Endian:Motor  Type:Uint8  StartBit:63  Length:8*/
#define SIG_HND_CHKSUMFR (32U)

/*********************************************************************************/

/*********************************************************************************/
/*MessageID: 0X2B1   MessageHandle: IPDU_HND_ITS_InfoStatus_N1   CycTime: 20mS*/
/*SignalName: WARN_LANE_L
  Endian:Motor  Type:Uint8  StartBit:7  Length:2*/
#define SIG_HND_WARN_LANE_L (33U)

/*SignalName: WARN_LANE_R
  Endian:Motor  Type:Uint8  StartBit:5  Length:2*/
#define SIG_HND_WARN_LANE_R (34U)

/*SignalName: ALIVE_CNT_N1
  Endian:Motor  Type:Uint8  StartBit:51  Length:4*/
#define SIG_HND_ALIVE_CNT_N1 (35U)

/*SignalName: CHECKSUM_N1
  Endian:Motor  Type:Uint8  StartBit:63  Length:8*/
#define SIG_HND_CHECKSUM_N1 (36U)

/*SignalName: HandOffStrgWhlDetnSta
  Endian:Motor  Type:Uint8  StartBit:3  Length:2*/
#define SIG_HND_HandOffStrgWhlDetnSta (37U)

/*SignalName: LKADrvrTkovReq
  Endian:Motor  Type:Boolean  StartBit:0  Length:1*/
#define SIG_HND_LKADrvrTkovReq (38U)

/*********************************************************************************/

/*********************************************************************************/
/*MessageID: 0X2B7   MessageHandle: IPDU_HND_ITS_InfoStatus_N2   CycTime: 20mS*/
/*SignalName: PRE_WARN_FR
  Endian:Motor  Type:Boolean  StartBit:6  Length:1*/
#define SIG_HND_PRE_WARN_FR (39U)

/*SignalName: AEB_ACTIVE
  Endian:Motor  Type:Boolean  StartBit:5  Length:1*/
#define SIG_HND_AEB_ACTIVE (40U)

/*SignalName: ALIVE_CNT_N2
  Endian:Motor  Type:Uint8  StartBit:51  Length:4*/
#define SIG_HND_ALIVE_CNT_N2 (41U)

/*SignalName: CHECKSUM_N2
  Endian:Motor  Type:Uint8  StartBit:63  Length:8*/
#define SIG_HND_CHECKSUM_N2 (42U)

/*********************************************************************************/

/*********************************************************************************/
/*MessageID: 0X2C8   MessageHandle: IPDU_HND_SRR_Left   CycTime: 50mS*/
/*SignalName: SFS
  Endian:Motor  Type:Uint8  StartBit:7  Length:2*/
#define SIG_HND_SFS (43U)

/*SignalName: UI
  Endian:Motor  Type:Boolean  StartBit:5  Length:1*/
#define SIG_HND_UI (44U)

/*SignalName: FAILD_DT
  Endian:Motor  Type:Boolean  StartBit:4  Length:1*/
#define SIG_HND_FAILD_DT (45U)

/*SignalName: BLOCK_DT
  Endian:Motor  Type:Boolean  StartBit:3  Length:1*/
#define SIG_HND_BLOCK_DT (46U)

/*SignalName: ALT_ST
  Endian:Motor  Type:Uint8  StartBit:2  Length:3*/
#define SIG_HND_ALT_ST (47U)

/*SignalName: ALT_IND
  Endian:Motor  Type:Uint8  StartBit:15  Length:2*/
#define SIG_HND_ALT_IND (48U)

/*SignalName: RIGHT_ID_FLG
  Endian:Motor  Type:Boolean  StartBit:13  Length:1*/
#define SIG_HND_RIGHT_ID_FLG (49U)

/*SignalName: MSG_CNT_SRR
  Endian:Motor  Type:Uint8  StartBit:55  Length:8*/
#define SIG_HND_MSG_CNT_SRR (50U)

/*SignalName: CHKSUM_SRR
  Endian:Motor  Type:Uint8  StartBit:63  Length:8*/
#define SIG_HND_CHKSUM_SRR (51U)

/*SignalName: SRRL_SET
  Endian:Motor  Type:Uint8  StartBit:23  Length:2*/
#define SIG_HND_SRRL_SET (52U)

/*********************************************************************************/

/*********************************************************************************/
/*MessageID: 0X2C9   MessageHandle: IPDU_HND_SRR_Right   CycTime: 50mS*/
/*SignalName: SFS_R
  Endian:Motor  Type:Uint8  StartBit:7  Length:2*/
#define SIG_HND_SFS_R (53U)

/*SignalName: UI_R
  Endian:Motor  Type:Boolean  StartBit:5  Length:1*/
#define SIG_HND_UI_R (54U)

/*SignalName: FAILD_DT_R
  Endian:Motor  Type:Boolean  StartBit:4  Length:1*/
#define SIG_HND_FAILD_DT_R (55U)

/*SignalName: BLOCK_DT_R
  Endian:Motor  Type:Boolean  StartBit:3  Length:1*/
#define SIG_HND_BLOCK_DT_R (56U)

/*SignalName: ALT_ST_R
  Endian:Motor  Type:Uint8  StartBit:2  Length:3*/
#define SIG_HND_ALT_ST_R (57U)

/*SignalName: ALT_IND_R
  Endian:Motor  Type:Uint8  StartBit:15  Length:2*/
#define SIG_HND_ALT_IND_R (58U)

/*SignalName: RIGHT_ID_FLG_R
  Endian:Motor  Type:Boolean  StartBit:13  Length:1*/
#define SIG_HND_RIGHT_ID_FLG_R (59U)

/*SignalName: MSG_CNT_SRR_R
  Endian:Motor  Type:Uint8  StartBit:55  Length:8*/
#define SIG_HND_MSG_CNT_SRR_R (60U)

/*SignalName: CHKSUM_SRR_R
  Endian:Motor  Type:Uint8  StartBit:63  Length:8*/
#define SIG_HND_CHKSUM_SRR_R (61U)

/*SignalName: SRRR_SET_R
  Endian:Motor  Type:Uint8  StartBit:23  Length:2*/
#define SIG_HND_SRRR_SET_R (62U)

/*********************************************************************************/

/*********************************************************************************/
/*MessageID: 0X351   MessageHandle: IPDU_HND_SMART_bcmMSG_PUSH   CycTime: 100mS*/
/*SignalName: remote_ENG_ST_STATE
  Endian:Motor  Type:Boolean  StartBit:32  Length:1*/
#define SIG_HND_remote_ENG_ST_STATE (63U)

/*SignalName: WARNING_REQ_PIC
  Endian:Motor  Type:Uint8  StartBit:43  Length:4*/
#define SIG_HND_WARNING_REQ_PIC (64U)

/*SignalName: RING_ILLUMI_REQ
  Endian:Motor  Type:Boolean  StartBit:0  Length:1*/
#define SIG_HND_RING_ILLUMI_REQ (65U)

/*SignalName: WARNING_REQ_BUZZER1
  Endian:Motor  Type:Boolean  StartBit:44  Length:1*/
#define SIG_HND_WARNING_REQ_BUZZER1 (66U)

/*SignalName: WARNING_REQ_BUZZER2
  Endian:Motor  Type:Boolean  StartBit:45  Length:1*/
#define SIG_HND_WARNING_REQ_BUZZER2 (67U)

/*SignalName: WARNING_REQ_IND
  Endian:Motor  Type:Uint8  StartBit:47  Length:2*/
#define SIG_HND_WARNING_REQ_IND (68U)

/*SignalName: KEY_WARNING_BUZZER
  Endian:Motor  Type:Boolean  StartBit:55  Length:1*/
#define SIG_HND_KEY_WARNING_BUZZER (69U)

/*SignalName: AHL_IND_REQ
  Endian:Motor  Type:Boolean  StartBit:52  Length:1*/
#define SIG_HND_AHL_IND_REQ (70U)

/*SignalName: No_INFOR
  Endian:Motor  Type:Uint8  StartBit:51  Length:3*/
#define SIG_HND_No_INFOR (71U)

/*SignalName: STARTER_CONT_STA
  Endian:Motor  Type:Boolean  StartBit:60  Length:1*/
#define SIG_HND_STARTER_CONT_STA (72U)

/*SignalName: IGN1_FAILURE_WARNING
  Endian:Motor  Type:Boolean  StartBit:36  Length:1*/
#define SIG_HND_IGN1_FAILURE_WARNING (73U)

/*SignalName: ESCL_FAILURE_WARNING
  Endian:Motor  Type:Boolean  StartBit:35  Length:1*/
#define SIG_HND_ESCL_FAILURE_WARNING (74U)

/*SignalName: SSB_FAILURE_WARNING
  Endian:Motor  Type:Boolean  StartBit:48  Length:1*/
#define SIG_HND_SSB_FAILURE_WARNING (75U)

/*********************************************************************************/

/*********************************************************************************/
/*MessageID: 0X352   MessageHandle: IPDU_HND_IKEY_352   CycTime: 100mS*/
/*SignalName: PEPS_APUfbResult352
  Endian:Motor  Type:Boolean  StartBit:3  Length:1*/
#define SIG_HND_PEPS_APUfbResult352 (76U)

/*SignalName: PEPS_WALfbResult352
  Endian:Motor  Type:Boolean  StartBit:2  Length:1*/
#define SIG_HND_PEPS_WALfbResult352 (77U)

/*********************************************************************************/

/*********************************************************************************/
/*MessageID: 0X354   MessageHandle: IPDU_HND_Brake_GeneralData   CycTime: 40mS*/
/*SignalName: VDCStateForDAMenu
  Endian:Motor  Type:Boolean  StartBit:41  Length:1*/
#define SIG_HND_VDCStateForDAMenu (78U)

/*SignalName: VDC_LAMP
  Endian:Motor  Type:Uint8  StartBit:39  Length:3*/
#define SIG_HND_VDC_LAMP (79U)

/*SignalName: ABS_LAMP
  Endian:Motor  Type:Uint8  StartBit:36  Length:2*/
#define SIG_HND_ABS_LAMP (80U)

/*SignalName: EBD_LAMP
  Endian:Motor  Type:Uint8  StartBit:34  Length:2*/
#define SIG_HND_EBD_LAMP (81U)

/*SignalName: HDC_LAMP
  Endian:Motor  Type:Uint8  StartBit:62  Length:2*/
#define SIG_HND_HDC_LAMP (82U)

/*********************************************************************************/

/*********************************************************************************/
/*MessageID: 0X358   MessageHandle: IPDU_HND_BCMMSG1   CycTime: 100mS*/
/*SignalName: Auto_Light_SW_Status
  Endian:Motor  Type:Boolean  StartBit:43  Length:1*/
#define SIG_HND_Auto_Light_SW_Status (83U)

/*SignalName: OIL_P_SW
  Endian:Motor  Type:Boolean  StartBit:29  Length:1*/
#define SIG_HND_OIL_P_SW (84U)

/*SignalName: KEY_NO
  Endian:Motor  Type:Uint8  StartBit:3  Length:3*/
#define SIG_HND_KEY_NO (85U)

/*SignalName: CLUSTER_ILL_REQ
  Endian:Motor  Type:Boolean  StartBit:15  Length:1*/
#define SIG_HND_CLUSTER_ILL_REQ (86U)

/*SignalName: H_POSITION
  Endian:Motor  Type:Boolean  StartBit:9  Length:1*/
#define SIG_HND_H_POSITION (87U)

/*SignalName: TPMS_RFWL_REQ
  Endian:Motor  Type:Boolean  StartBit:8  Length:1*/
#define SIG_HND_TPMS_RFWL_REQ (88U)

/*SignalName: TRUNK_SW
  Endian:Motor  Type:Boolean  StartBit:16  Length:1*/
#define SIG_HND_TRUNK_SW (89U)

/*SignalName: GLASS_HATCH
  Endian:Motor  Type:Boolean  StartBit:30  Length:1*/
#define SIG_HND_GLASS_HATCH (90U)

/*SignalName: TPMS_W_L_REQ
  Endian:Motor  Type:Boolean  StartBit:39  Length:1*/
#define SIG_HND_TPMS_W_L_REQ (91U)

/*********************************************************************************/

/*********************************************************************************/
/*MessageID: 0X35A   MessageHandle: IPDU_HND_BCM_SystemControl_2   CycTime: 100mS*/
/*SignalName: BCM_Area2
  Endian:Motor  Type:Uint8  StartBit:47  Length:4*/
#define SIG_HND_BCM_Area2 (92U)

/*SignalName: DR_Window_status
  Endian:Motor  Type:Uint8  StartBit:55  Length:4*/
#define SIG_HND_DR_Window_status (93U)

/*SignalName: AS_Window_status
  Endian:Motor  Type:Uint8  StartBit:51  Length:4*/
#define SIG_HND_AS_Window_status (94U)

/*SignalName: RL_Window_status
  Endian:Motor  Type:Uint8  StartBit:63  Length:4*/
#define SIG_HND_RL_Window_status (95U)

/*SignalName: RR_Window_status
  Endian:Motor  Type:Uint8  StartBit:59  Length:4*/
#define SIG_HND_RR_Window_status (96U)

/*********************************************************************************/

/*********************************************************************************/
/*MessageID: 0X35D   MessageHandle: IPDU_HND_BCM_SystemControl   CycTime: 100mS*/
/*SignalName: BCM_WAKE_SLEEP_COM
  Endian:Motor  Type:Uint8  StartBit:9  Length:2*/
#define SIG_HND_BCM_WAKE_SLEEP_COM (97U)

/*SignalName: CABRESW
  Endian:Motor  Type:Uint8  StartBit:37  Length:2*/
#define SIG_HND_CABRESW (98U)

/*SignalName: RLS_FW_value
  Endian:Motor  Type:Uint16  StartBit:19  Length:12*/
#define SIG_HND_RLS_FW_value (99U)

/*SignalName: RLS_Amb_value
  Endian:Motor  Type:Uint16  StartBit:35  Length:12*/
#define SIG_HND_RLS_Amb_value (100U)

/*SignalName: Se_IN_Re
  Endian:Motor  Type:Boolean  StartBit:3  Length:1*/
#define SIG_HND_Se_IN_Re (101U)

/*********************************************************************************/

/*********************************************************************************/
/*MessageID: 0X385   MessageHandle: IPDU_HND_TPMS_GeneralStatus_BCM   CycTime: 100mS*/
/*SignalName: D_STYLE
  Endian:Motor  Type:Uint8  StartBit:3  Length:2*/
#define SIG_HND_D_STYLE (102U)

/*SignalName: SYSTEM_FAIL_TPMS
  Endian:Motor  Type:Boolean  StartBit:1  Length:1*/
#define SIG_HND_SYSTEM_FAIL_TPMS (103U)

/*SignalName: FT_FR
  Endian:Motor  Type:Boolean  StartBit:15  Length:1*/
#define SIG_HND_FT_FR (104U)

/*SignalName: FT_FL
  Endian:Motor  Type:Boolean  StartBit:14  Length:1*/
#define SIG_HND_FT_FL (105U)

/*SignalName: FT_RL
  Endian:Motor  Type:Boolean  StartBit:12  Length:1*/
#define SIG_HND_FT_RL (106U)

/*SignalName: FT_RR
  Endian:Motor  Type:Boolean  StartBit:13  Length:1*/
#define SIG_HND_FT_RR (107U)

/*SignalName: LTP_FL
  Endian:Motor  Type:Boolean  StartBit:10  Length:1*/
#define SIG_HND_LTP_FL (108U)

/*SignalName: LTP_FR
  Endian:Motor  Type:Boolean  StartBit:11  Length:1*/
#define SIG_HND_LTP_FR (109U)

/*SignalName: LTP_RL
  Endian:Motor  Type:Boolean  StartBit:8  Length:1*/
#define SIG_HND_LTP_RL (110U)

/*SignalName: LTP_RR
  Endian:Motor  Type:Boolean  StartBit:9  Length:1*/
#define SIG_HND_LTP_RR (111U)

/*SignalName: TPD_FL
  Endian:Motor  Type:Uint8  StartBit:31  Length:8*/
#define SIG_HND_TPD_FL (112U)

/*SignalName: TPD_FR
  Endian:Motor  Type:Uint8  StartBit:23  Length:8*/
#define SIG_HND_TPD_FR (113U)

/*SignalName: TPD_RL
  Endian:Motor  Type:Uint8  StartBit:47  Length:8*/
#define SIG_HND_TPD_RL (114U)

/*SignalName: TPD_RR
  Endian:Motor  Type:Uint8  StartBit:39  Length:8*/
#define SIG_HND_TPD_RR (115U)

/*SignalName: TS_FL
  Endian:Motor  Type:Boolean  StartBit:54  Length:1*/
#define SIG_HND_TS_FL (116U)

/*SignalName: TS_FR
  Endian:Motor  Type:Boolean  StartBit:55  Length:1*/
#define SIG_HND_TS_FR (117U)

/*SignalName: TS_RL
  Endian:Motor  Type:Boolean  StartBit:52  Length:1*/
#define SIG_HND_TS_RL (118U)

/*SignalName: TS_RR
  Endian:Motor  Type:Boolean  StartBit:53  Length:1*/
#define SIG_HND_TS_RR (119U)

/*SignalName: TPMS_POSI_SYNC
  Endian:Motor  Type:Boolean  StartBit:49  Length:1*/
#define SIG_HND_TPMS_POSI_SYNC (120U)

/*SignalName: PRESS_FRONT
  Endian:Motor  Type:Uint8  StartBit:63  Length:4*/
#define SIG_HND_PRESS_FRONT (121U)

/*SignalName: PRESS_REAR
  Endian:Motor  Type:Uint8  StartBit:59  Length:4*/
#define SIG_HND_PRESS_REAR (122U)

/*********************************************************************************/

/*********************************************************************************/
/*MessageID: 0X421   MessageHandle: IPDU_HND_ATCVT_to_MMI_RN1   CycTime: 60mS*/
/*SignalName: IND_RNG
  Endian:Motor  Type:Uint8  StartBit:7  Length:5*/
#define SIG_HND_IND_RNG (123U)

/*SignalName: ATLAMP_INDSSIG_CVTLAMPSIG
  Endian:Motor  Type:Boolean  StartBit:2  Length:1*/
#define SIG_HND_ATLAMP_INDSSIG_CVTLAMPSIG (124U)

/*SignalName: RGB_GP_REFUSE
  Endian:Motor  Type:Boolean  StartBit:10  Length:1*/
#define SIG_HND_RGB_GP_REFUSE (125U)

/*SignalName: TrFaultContBuz
  Endian:Motor  Type:Boolean  StartBit:1  Length:1*/
#define SIG_HND_TrFaultContBuz (126U)

/*SignalName: TrFaultBuz
  Endian:Motor  Type:Boolean  StartBit:0  Length:1*/
#define SIG_HND_TrFaultBuz (127U)

/*SignalName: TrFaultWdRemind
  Endian:Motor  Type:Uint8  StartBit:15  Length:3*/
#define SIG_HND_TrFaultWdRemind (128U)

/*SignalName: RGB_PBP_REQ
  Endian:Motor  Type:Boolean  StartBit:11  Length:1*/
#define SIG_HND_RGB_PBP_REQ (129U)

/*SignalName: TrFaultWdRemind2
  Endian:Motor  Type:Uint8  StartBit:22  Length:3*/
#define SIG_HND_TrFaultWdRemind2 (130U)

/*********************************************************************************/

/*********************************************************************************/
/*MessageID: 0X4CB   MessageHandle: IPDU_HND_ITS_InfoStatus_N3_7b   CycTime: 100mS*/
/*SignalName: SET_LDW_STA
  Endian:Motor  Type:Uint8  StartBit:7  Length:2*/
#define SIG_HND_SET_LDW_STA (131U)

/*SignalName: LDW_INFO
  Endian:Motor  Type:Uint8  StartBit:5  Length:3*/
#define SIG_HND_LDW_INFO (132U)

/*SignalName: MSG_LDW_TMP_ERR
  Endian:Motor  Type:Boolean  StartBit:2  Length:1*/
#define SIG_HND_MSG_LDW_TMP_ERR (133U)

/*SignalName: MSG_LDW_PER_ERR
  Endian:Motor  Type:Boolean  StartBit:1  Length:1*/
#define SIG_HND_MSG_LDW_PER_ERR (134U)

/*SignalName: MSG_CAM_BLK
  Endian:Motor  Type:Boolean  StartBit:0  Length:1*/
#define SIG_HND_MSG_CAM_BLK (135U)

/*SignalName: ALIVE_CNT_N3_7b
  Endian:Motor  Type:Uint8  StartBit:51  Length:4*/
#define SIG_HND_ALIVE_CNT_N3_7b (136U)

/*SignalName: CHECKSUM_N3_7b
  Endian:Motor  Type:Uint8  StartBit:63  Length:8*/
#define SIG_HND_CHECKSUM_N3_7b (137U)

/*SignalName: SET_LKA_STA
  Endian:Motor  Type:Uint8  StartBit:15  Length:2*/
#define SIG_HND_SET_LKA_STA (138U)

/*SignalName: LKA_INFO
  Endian:Motor  Type:Uint8  StartBit:13  Length:3*/
#define SIG_HND_LKA_INFO (139U)

/*SignalName: MSG_HIGH_TEMP
  Endian:Motor  Type:Boolean  StartBit:10  Length:1*/
#define SIG_HND_MSG_HIGH_TEMP (140U)

/*SignalName: MSG_LKA_TMP_ERR
  Endian:Motor  Type:Boolean  StartBit:9  Length:1*/
#define SIG_HND_MSG_LKA_TMP_ERR (141U)

/*SignalName: MSG_LKA_PER_ERR
  Endian:Motor  Type:Boolean  StartBit:8  Length:1*/
#define SIG_HND_MSG_LKA_PER_ERR (142U)

/*SignalName: MSG_HANDSOFF_STDBY
  Endian:Motor  Type:Boolean  StartBit:23  Length:1*/
#define SIG_HND_MSG_HANDSOFF_STDBY (143U)

/*SignalName: STA_CHG_ALERT
  Endian:Motor  Type:Boolean  StartBit:22  Length:1*/
#define SIG_HND_STA_CHG_ALERT (144U)

/*SignalName: MSG_SW1
  Endian:Motor  Type:Boolean  StartBit:29  Length:1*/
#define SIG_HND_MSG_SW1 (145U)

/*SignalName: MSG_SW2
  Endian:Motor  Type:Boolean  StartBit:28  Length:1*/
#define SIG_HND_MSG_SW2 (146U)

/*SignalName: MSG_SW3
  Endian:Motor  Type:Boolean  StartBit:27  Length:1*/
#define SIG_HND_MSG_SW3 (147U)

/*********************************************************************************/

/*********************************************************************************/
/*MessageID: 0X4CC   MessageHandle: IPDU_HND_ITS_InfoStatus_N2_1   CycTime: 100mS*/
/*SignalName: SET_PEBS_STA
  Endian:Motor  Type:Uint8  StartBit:7  Length:2*/
#define SIG_HND_SET_PEBS_STA (148U)

/*SignalName: PEBS_INFO
  Endian:Motor  Type:Uint8  StartBit:5  Length:3*/
#define SIG_HND_PEBS_INFO (149U)

/*SignalName: WARN_VRU
  Endian:Motor  Type:Boolean  StartBit:2  Length:1*/
#define SIG_HND_WARN_VRU (150U)

/*SignalName: MSG_TMP_ERR_N2_1
  Endian:Motor  Type:Boolean  StartBit:1  Length:1*/
#define SIG_HND_MSG_TMP_ERR_N2_1 (151U)

/*SignalName: MSG_PER_ERR_N2_1
  Endian:Motor  Type:Boolean  StartBit:0  Length:1*/
#define SIG_HND_MSG_PER_ERR_N2_1 (152U)

/*SignalName: MSG_BLKT
  Endian:Motor  Type:Boolean  StartBit:15  Length:1*/
#define SIG_HND_MSG_BLKT (153U)

/*SignalName: MSG_VRU
  Endian:Motor  Type:Boolean  StartBit:14  Length:1*/
#define SIG_HND_MSG_VRU (154U)

/*SignalName: MSG_VDC
  Endian:Motor  Type:Boolean  StartBit:13  Length:1*/
#define SIG_HND_MSG_VDC (155U)

/*SignalName: ALIVE_CNT_N2_1
  Endian:Motor  Type:Uint8  StartBit:51  Length:4*/
#define SIG_HND_ALIVE_CNT_N2_1 (156U)

/*SignalName: CHECKSUM_N2_1
  Endian:Motor  Type:Uint8  StartBit:63  Length:8*/
#define SIG_HND_CHECKSUM_N2_1 (157U)

/*SignalName: ACC_MSG_TMP_ERR
  Endian:Motor  Type:Boolean  StartBit:12  Length:1*/
#define SIG_HND_ACC_MSG_TMP_ERR (158U)

/*SignalName: ACC_MSG_PER_ERR
  Endian:Motor  Type:Boolean  StartBit:11  Length:1*/
#define SIG_HND_ACC_MSG_PER_ERR (159U)

/*SignalName: ACC_HEADW_SET
  Endian:Motor  Type:Uint8  StartBit:10  Length:2*/
#define SIG_HND_ACC_HEADW_SET (160U)

/*SignalName: ACC_DrSeSp
  Endian:Motor  Type:Uint8  StartBit:23  Length:8*/
#define SIG_HND_ACC_DrSeSp (161U)

/*SignalName: ACC_DisToTgt
  Endian:Motor  Type:Uint8  StartBit:31  Length:8*/
#define SIG_HND_ACC_DisToTgt (162U)

/*SignalName: ACC_TgtDet
  Endian:Motor  Type:Boolean  StartBit:39  Length:1*/
#define SIG_HND_ACC_TgtDet (163U)

/*SignalName: ACC_TextMessage
  Endian:Motor  Type:Uint8  StartBit:38  Length:4*/
#define SIG_HND_ACC_TextMessage (164U)

/*SignalName: ACC_GoNoti
  Endian:Motor  Type:Boolean  StartBit:34  Length:1*/
#define SIG_HND_ACC_GoNoti (165U)

/*SignalName: ACC_TOREQ
  Endian:Motor  Type:Boolean  StartBit:33  Length:1*/
#define SIG_HND_ACC_TOREQ (166U)

/*SignalName: ACC_INFO
  Endian:Motor  Type:Uint8  StartBit:45  Length:3*/
#define SIG_HND_ACC_INFO (167U)

/*********************************************************************************/

/*********************************************************************************/
/*MessageID: 0X502   MessageHandle: IPDU_HND_RETREIVE_ASSIST_POWER_48V   CycTime: 50mS*/
/*SignalName: RETREIVE_48V
  Endian:Motor  Type:Boolean  StartBit:7  Length:1*/
#define SIG_HND_RETREIVE_48V (168U)

/*SignalName: ASSIST_48V
  Endian:Motor  Type:Boolean  StartBit:6  Length:1*/
#define SIG_HND_ASSIST_48V (169U)

/*SignalName: RETREIVE_ASSIST_POWER_PERCENTAGE
  Endian:Motor  Type:Uint8  StartBit:15  Length:8*/
#define SIG_HND_RETREIVE_ASSIST_POWER_PERCENTAGE (170U)

/*********************************************************************************/

/*********************************************************************************/
/*MessageID: 0X54C   MessageHandle: IPDU_HND_CLIMATE_ControlData_F   CycTime: 100mS*/
/*SignalName: OutsideTemp_AD
  Endian:Motor  Type:Uint8  StartBit:55  Length:8*/
#define SIG_HND_OutsideTemp_AD (171U)

/*********************************************************************************/

/*********************************************************************************/
/*MessageID: 0X551   MessageHandle: IPDU_HND_ECM_GeneralStatus   CycTime: 100mS*/
/*SignalName: TWN
  Endian:Motor  Type:Uint8  StartBit:7  Length:8*/
#define SIG_HND_TWN (172U)

/*SignalName: CANMASK
  Endian:Motor  Type:Boolean  StartBit:31  Length:1*/
#define SIG_HND_CANMASK (173U)

/*SignalName: LED
  Endian:Motor  Type:Uint8  StartBit:30  Length:2*/
#define SIG_HND_LED (174U)

/*SignalName: TIM
  Endian:Motor  Type:Uint8  StartBit:15  Length:8*/
#define SIG_HND_TIM (175U)

/*SignalName: WTENP
  Endian:Motor  Type:Boolean  StartBit:28  Length:1*/
#define SIG_HND_WTENP (176U)

/*SignalName: SPDREQ
  Endian:Motor  Type:Uint8  StartBit:39  Length:8*/
#define SIG_HND_SPDREQ (177U)

/*SignalName: SPDBLREQ
  Endian:Motor  Type:Boolean  StartBit:47  Length:1*/
#define SIG_HND_SPDBLREQ (178U)

/*SignalName: ASCDON_DISP
  Endian:Motor  Type:Uint8  StartBit:46  Length:3*/
#define SIG_HND_ASCDON_DISP (179U)

/*SignalName: ENG_STA
  Endian:Motor  Type:Uint8  StartBit:41  Length:2*/
#define SIG_HND_ENG_STA (180U)

/*SignalName: ELAMP
  Endian:Motor  Type:Boolean  StartBit:54  Length:1*/
#define SIG_HND_ELAMP (181U)

/*SignalName: S48V_Waring_IND
  Endian:Motor  Type:Boolean  StartBit:53  Length:1*/
#define SIG_HND_S48V_Waring_IND (182U)

/*********************************************************************************/

/*********************************************************************************/
/*MessageID: 0X563   MessageHandle: IPDU_HND_DCM_GeneralStatus_5   CycTime: 100mS*/
/*SignalName: DA_wakeup_Request
  Endian:Motor  Type:Boolean  StartBit:35  Length:1*/
#define SIG_HND_DA_wakeup_Request (183U)

/*SignalName: DVR_CrashVideo_Request
  Endian:Motor  Type:Boolean  StartBit:32  Length:1*/
#define SIG_HND_DVR_CrashVideo_Request (184U)

/*SignalName: DVR_Photo_Request
  Endian:Motor  Type:Boolean  StartBit:47  Length:1*/
#define SIG_HND_DVR_Photo_Request (185U)

/*SignalName: E_CALL_display_request
  Endian:Motor  Type:Uint8  StartBit:59  Length:4*/
#define SIG_HND_E_CALL_display_request (186U)

/*SignalName: DA_Muteout_Request
  Endian:Motor  Type:Boolean  StartBit:37  Length:1*/
#define SIG_HND_DA_Muteout_Request (187U)

/*SignalName: AVM_OutdoorPhoto_Request
  Endian:Motor  Type:Uint8  StartBit:62  Length:2*/
#define SIG_HND_AVM_OutdoorPhoto_Request (188U)

/*********************************************************************************/

/*********************************************************************************/
/*MessageID: 0X57A   MessageHandle: IPDU_HND_SONAR_GeneralStatus_8   CycTime: 100mS*/
/*SignalName: SoundObstacleLevel_Request
  Endian:Motor  Type:Uint8  StartBit:55  Length:3*/
#define SIG_HND_SoundObstacleLevel_Request (189U)

/*SignalName: REQ_DISP_MET
  Endian:Motor  Type:Boolean  StartBit:7  Length:1*/
#define SIG_HND_REQ_DISP_MET (190U)

/*SignalName: STS_SETTING
  Endian:Motor  Type:Boolean  StartBit:3  Length:1*/
#define SIG_HND_STS_SETTING (191U)

/*SignalName: RR_CEN
  Endian:Motor  Type:Uint8  StartBit:15  Length:3*/
#define SIG_HND_RR_CEN (192U)

/*SignalName: A_RR_CEN
  Endian:Motor  Type:Boolean  StartBit:12  Length:1*/
#define SIG_HND_A_RR_CEN (193U)

/*SignalName: RR_L
  Endian:Motor  Type:Uint8  StartBit:23  Length:3*/
#define SIG_HND_RR_L (194U)

/*SignalName: A_RR_L
  Endian:Motor  Type:Boolean  StartBit:20  Length:1*/
#define SIG_HND_A_RR_L (195U)

/*SignalName: RR_R
  Endian:Motor  Type:Uint8  StartBit:19  Length:3*/
#define SIG_HND_RR_R (196U)

/*SignalName: A_RR_R
  Endian:Motor  Type:Boolean  StartBit:16  Length:1*/
#define SIG_HND_A_RR_R (197U)

/*SignalName: STATUS_Dynamic_EAPM
  Endian:Motor  Type:Uint8  StartBit:2  Length:3*/
#define SIG_HND_STATUS_Dynamic_EAPM (198U)

/*SignalName: SETTEING_EAPM
  Endian:Motor  Type:Uint8  StartBit:52  Length:2*/
#define SIG_HND_SETTEING_EAPM (199U)

/*SignalName: STATUS_Warning_EAPM
  Endian:Motor  Type:Uint8  StartBit:35  Length:2*/
#define SIG_HND_STATUS_Warning_EAPM (200U)

/*SignalName: STS_AUTO_DISP
  Endian:Motor  Type:Boolean  StartBit:43  Length:1*/
#define SIG_HND_STS_AUTO_DISP (201U)

/*SignalName: STS_SYS_MODE
  Endian:Motor  Type:Uint8  StartBit:42  Length:3*/
#define SIG_HND_STS_SYS_MODE (202U)

/*SignalName: SOUND_EAPM
  Endian:Motor  Type:Boolean  StartBit:33  Length:1*/
#define SIG_HND_SOUND_EAPM (203U)

/*SignalName: REQ_DISP_CEN
  Endian:Motor  Type:Boolean  StartBit:6  Length:1*/
#define SIG_HND_REQ_DISP_CEN (204U)

/*SignalName: SONAR_S_REQ
  Endian:Motor  Type:Uint8  StartBit:39  Length:3*/
#define SIG_HND_SONAR_S_REQ (205U)

/*SignalName: FR_CEN
  Endian:Motor  Type:Uint8  StartBit:11  Length:3*/
#define SIG_HND_FR_CEN (206U)

/*SignalName: A_FR_CEN
  Endian:Motor  Type:Boolean  StartBit:8  Length:1*/
#define SIG_HND_A_FR_CEN (207U)

/*SignalName: FR_L
  Endian:Motor  Type:Uint8  StartBit:31  Length:3*/
#define SIG_HND_FR_L (208U)

/*SignalName: A_FR_L
  Endian:Motor  Type:Boolean  StartBit:28  Length:1*/
#define SIG_HND_A_FR_L (209U)

/*SignalName: FR_R
  Endian:Motor  Type:Uint8  StartBit:27  Length:3*/
#define SIG_HND_FR_R (210U)

/*SignalName: A_FR_R
  Endian:Motor  Type:Boolean  StartBit:24  Length:1*/
#define SIG_HND_A_FR_R (211U)

/*SignalName: STS_DISTANCE
  Endian:Motor  Type:Uint8  StartBit:62  Length:5*/
#define SIG_HND_STS_DISTANCE (212U)

/*SignalName: SOUND_ZONE
  Endian:Motor  Type:Uint8  StartBit:50  Length:3*/
#define SIG_HND_SOUND_ZONE (213U)

/*SignalName: SOUND_CONT
  Endian:Motor  Type:Boolean  StartBit:63  Length:1*/
#define SIG_HND_SOUND_CONT (214U)

/*********************************************************************************/

/*********************************************************************************/
/*MessageID: 0X580   MessageHandle: IPDU_HND_ECM_to_ITM   CycTime: 100mS*/
/*SignalName: ENG_OIL_WARNING_LAMP
  Endian:Motor  Type:Boolean  StartBit:16  Length:1*/
#define SIG_HND_ENG_OIL_WARNING_LAMP (215U)

/*SignalName: CAP_IND_REQ
  Endian:Motor  Type:Boolean  StartBit:24  Length:1*/
#define SIG_HND_CAP_IND_REQ (216U)

/*SignalName: GPF_IND
  Endian:Motor  Type:Uint8  StartBit:23  Length:2*/
#define SIG_HND_GPF_IND (217U)

/*SignalName: GSINXTGP
  Endian:Motor  Type:Uint8  StartBit:42  Length:3*/
#define SIG_HND_GSINXTGP (218U)

/*********************************************************************************/

/*********************************************************************************/
/*MessageID: 0X58A   MessageHandle: IPDU_HND_EPB_SystemControl   CycTime: 20mS*/
/*SignalName: EPB_CONG_IND
  Endian:Motor  Type:Uint8  StartBit:7  Length:2*/
#define SIG_HND_EPB_CONG_IND (219U)

/*SignalName: EPB_WORKMODE
  Endian:Motor  Type:Uint8  StartBit:5  Length:2*/
#define SIG_HND_EPB_WORKMODE (220U)

/*SignalName: EPB_STAT
  Endian:Motor  Type:Uint8  StartBit:3  Length:3*/
#define SIG_HND_EPB_STAT (221U)

/*SignalName: EPB_FAIL
  Endian:Motor  Type:Boolean  StartBit:0  Length:1*/
#define SIG_HND_EPB_FAIL (222U)

/*SignalName: EPB_WARNMSG_IND
  Endian:Motor  Type:Uint8  StartBit:15  Length:3*/
#define SIG_HND_EPB_WARNMSG_IND (223U)

/*SignalName: EPB_HAZARD_IND
  Endian:Motor  Type:Boolean  StartBit:12  Length:1*/
#define SIG_HND_EPB_HAZARD_IND (224U)

/*SignalName: EPB_BUZZER_REQ
  Endian:Motor  Type:Boolean  StartBit:11  Length:1*/
#define SIG_HND_EPB_BUZZER_REQ (225U)

/*SignalName: CHKSUM
  Endian:Motor  Type:Uint8  StartBit:31  Length:8*/
#define SIG_HND_CHKSUM (226U)

/*SignalName: AVH_ACT
  Endian:Motor  Type:Boolean  StartBit:23  Length:1*/
#define SIG_HND_AVH_ACT (227U)

/*SignalName: AVH_OFFSW
  Endian:Motor  Type:Boolean  StartBit:8  Length:1*/
#define SIG_HND_AVH_OFFSW (228U)

/*SignalName: DPB_STAT
  Endian:Motor  Type:Uint8  StartBit:10  Length:2*/
#define SIG_HND_DPB_STAT (229U)

/*SignalName: AVH_FAIL
  Endian:Motor  Type:Boolean  StartBit:22  Length:1*/
#define SIG_HND_AVH_FAIL (230U)

/*********************************************************************************/

/*********************************************************************************/
/*MessageID: 0X5C8   MessageHandle: IPDU_HND_S_BOX_ControlData_SetPM   CycTime: 100mS*/
/*SignalName: FR_LAMP_LEVEL
  Endian:Motor  Type:Uint8  StartBit:17  Length:2*/
#define SIG_HND_FR_LAMP_LEVEL (231U)

/*SignalName: L_SW_UP
  Endian:Motor  Type:Boolean  StartBit:31  Length:1*/
#define SIG_HND_L_SW_UP (232U)

/*SignalName: L_SW_DOWN
  Endian:Motor  Type:Boolean  StartBit:30  Length:1*/
#define SIG_HND_L_SW_DOWN (233U)

/*SignalName: L_SW_LEFT
  Endian:Motor  Type:Boolean  StartBit:29  Length:1*/
#define SIG_HND_L_SW_LEFT (234U)

/*SignalName: L_SW_RIGHT
  Endian:Motor  Type:Boolean  StartBit:28  Length:1*/
#define SIG_HND_L_SW_RIGHT (235U)

/*SignalName: L_SW_OK
  Endian:Motor  Type:Boolean  StartBit:27  Length:1*/
#define SIG_HND_L_SW_OK (236U)

/*SignalName: L_SW_DISP
  Endian:Motor  Type:Boolean  StartBit:26  Length:1*/
#define SIG_HND_L_SW_DISP (237U)

/*SignalName: L_SW_TEL_ON
  Endian:Motor  Type:Boolean  StartBit:25  Length:1*/
#define SIG_HND_L_SW_TEL_ON (238U)

/*SignalName: PESPONSE_ERRO_LEFT
  Endian:Motor  Type:Boolean  StartBit:24  Length:1*/
#define SIG_HND_PESPONSE_ERRO_LEFT (239U)

/*SignalName: R_SW_DVR
  Endian:Motor  Type:Boolean  StartBit:39  Length:1*/
#define SIG_HND_R_SW_DVR (240U)

/*SignalName: R_SW_LKA
  Endian:Motor  Type:Boolean  StartBit:38  Length:1*/
#define SIG_HND_R_SW_LKA (241U)

/*SignalName: RESPONSE_ERRO_RIGHT
  Endian:Motor  Type:Boolean  StartBit:37  Length:1*/
#define SIG_HND_RESPONSE_ERRO_RIGHT (242U)

/*SignalName: Pinao_FR_DEFOGSW
  Endian:Motor  Type:Boolean  StartBit:36  Length:1*/
#define SIG_HND_Pinao_FR_DEFOGSW (243U)

/*SignalName: Pinao_RR_DEFOGSW
  Endian:Motor  Type:Boolean  StartBit:35  Length:1*/
#define SIG_HND_Pinao_RR_DEFOGSW (244U)

/*SignalName: OUTSIDEMIRROR_MODE_F
  Endian:Motor  Type:Uint8  StartBit:42  Length:2*/
#define SIG_HND_OUTSIDEMIRROR_MODE_F (245U)

/*********************************************************************************/

/*********************************************************************************/
/*MessageID: 0X5CA   MessageHandle: IPDU_HND_S_BOX_ControlData_enjoy   CycTime: 100mS*/
/*SignalName: WPC_Status
  Endian:Motor  Type:Boolean  StartBit:7  Length:1*/
#define SIG_HND_WPC_Status (246U)

/*SignalName: WPC_Error_Feedback
  Endian:Motor  Type:Uint8  StartBit:6  Length:4*/
#define SIG_HND_WPC_Error_Feedback (247U)

/*SignalName: WPC_Percentage
  Endian:Motor  Type:Uint8  StartBit:2  Length:8*/
#define SIG_HND_WPC_Percentage (248U)

/*SignalName: AMB_LGHT_OnOff
  Endian:Motor  Type:Boolean  StartBit:47  Length:1*/
#define SIG_HND_AMB_LGHT_OnOff (249U)

/*SignalName: AMB_LGHT_LinkedSwitch
  Endian:Motor  Type:Boolean  StartBit:46  Length:1*/
#define SIG_HND_AMB_LGHT_LinkedSwitch (250U)

/*SignalName: AMB_LGHT_ThemeColor
  Endian:Motor  Type:Uint8  StartBit:45  Length:3*/
#define SIG_HND_AMB_LGHT_ThemeColor (251U)

/*SignalName: AMB_LGHT_Color
  Endian:Motor  Type:Uint8  StartBit:42  Length:3*/
#define SIG_HND_AMB_LGHT_Color (252U)

/*SignalName: AMB_LGHT_MusicRhythmSignal
  Endian:Motor  Type:Uint8  StartBit:55  Length:4*/
#define SIG_HND_AMB_LGHT_MusicRhythmSignal (253U)

/*SignalName: AMB_COLOR
  Endian:Motor  Type:Uint8  StartBit:51  Length:7*/
#define SIG_HND_AMB_COLOR (254U)

/*SignalName: AMB_MUSIC_SW
  Endian:Motor  Type:Boolean  StartBit:60  Length:1*/
#define SIG_HND_AMB_MUSIC_SW (255U)

/*SignalName: AMB_TEM_SW
  Endian:Motor  Type:Boolean  StartBit:59  Length:1*/
#define SIG_HND_AMB_TEM_SW (256U)

/*SignalName: AMB_SPEEDING_SW
  Endian:Motor  Type:Boolean  StartBit:58  Length:1*/
#define SIG_HND_AMB_SPEEDING_SW (257U)

/*********************************************************************************/

/*********************************************************************************/
/*MessageID: 0X5CB   MessageHandle: IPDU_HND_S_BOX_ControlData_AC   CycTime: 100mS*/
/*SignalName: ac_compressor
  Endian:Motor  Type:Boolean  StartBit:7  Length:1*/
#define SIG_HND_ac_compressor (258U)

/*SignalName: ac_fan_speed_eedback
  Endian:Motor  Type:Uint8  StartBit:6  Length:4*/
#define SIG_HND_ac_fan_speed_eedback (259U)

/*SignalName: ac_mode
  Endian:Motor  Type:Uint8  StartBit:2  Length:3*/
#define SIG_HND_ac_mode (260U)

/*SignalName: ac_temp_d
  Endian:Motor  Type:Uint8  StartBit:15  Length:7*/
#define SIG_HND_ac_temp_d (261U)

/*SignalName: ac_auto
  Endian:Motor  Type:Boolean  StartBit:8  Length:1*/
#define SIG_HND_ac_auto (262U)

/*SignalName: ac_onoff
  Endian:Motor  Type:Boolean  StartBit:23  Length:1*/
#define SIG_HND_ac_onoff (263U)

/*SignalName: ac_dual
  Endian:Motor  Type:Boolean  StartBit:22  Length:1*/
#define SIG_HND_ac_dual (264U)

/*SignalName: ac_temp_p
  Endian:Motor  Type:Uint8  StartBit:21  Length:7*/
#define SIG_HND_ac_temp_p (265U)

/*SignalName: ac_recirc
  Endian:Motor  Type:Uint8  StartBit:30  Length:2*/
#define SIG_HND_ac_recirc (266U)

/*SignalName: ac_rr_defog
  Endian:Motor  Type:Boolean  StartBit:28  Length:1*/
#define SIG_HND_ac_rr_defog (267U)

/*SignalName: Target_Temp_E
  Endian:Motor  Type:Uint8  StartBit:47  Length:4*/
#define SIG_HND_Target_Temp_E (268U)

/*SignalName: MAX_AC
  Endian:Motor  Type:Boolean  StartBit:43  Length:1*/
#define SIG_HND_MAX_AC (269U)

/*SignalName: AUTO_MODE
  Endian:Motor  Type:Uint8  StartBit:42  Length:3*/
#define SIG_HND_AUTO_MODE (270U)

/*SignalName: DEFROST_F
  Endian:Motor  Type:Boolean  StartBit:55  Length:1*/
#define SIG_HND_DEFROST_F (271U)

/*********************************************************************************/

/*********************************************************************************/
/*MessageID: 0X5E4   MessageHandle: IPDU_HND_EPS_GeneralStatus   CycTime: 100mS*/
/*SignalName: EPSFAIL
  Endian:Motor  Type:Uint8  StartBit:2  Length:2*/
#define SIG_HND_EPSFAIL (272U)

/*********************************************************************************/

/*********************************************************************************/
/*MessageID: 0X5E8   MessageHandle: IPDU_HND_TPMS_GeneralStatus2   CycTime: 500mS*/
/*SignalName: SELECT_PRESS_SUPPORT
  Endian:Motor  Type:Boolean  StartBit:39  Length:1*/
#define SIG_HND_SELECT_PRESS_SUPPORT (273U)

/*SignalName: RESET_TPMS
  Endian:Motor  Type:Uint8  StartBit:38  Length:2*/
#define SIG_HND_RESET_TPMS (274U)

/*SignalName: PSI_MES_REQ
  Endian:Motor  Type:Boolean  StartBit:36  Length:1*/
#define SIG_HND_PSI_MES_REQ (275U)

/*SignalName: KPA_MES_REQ
  Endian:Motor  Type:Boolean  StartBit:35  Length:1*/
#define SIG_HND_KPA_MES_REQ (276U)

/*SignalName: KGF_MES_REQ
  Endian:Motor  Type:Boolean  StartBit:34  Length:1*/
#define SIG_HND_KGF_MES_REQ (277U)

/*********************************************************************************/

/*********************************************************************************/
/*MessageID: 0X5E9   MessageHandle: IPDU_HND_APA_HMI_system   CycTime: 100mS*/
/*SignalName: APA_B_PR
  Endian:Motor  Type:Boolean  StartBit:7  Length:1*/
#define SIG_HND_APA_B_PR (278U)

/*SignalName: APA_R_INT_IN
  Endian:Motor  Type:Uint8  StartBit:15  Length:3*/
#define SIG_HND_APA_R_INT_IN (279U)

/*SignalName: APA_QU_INDICATION
  Endian:Motor  Type:Uint8  StartBit:12  Length:5*/
#define SIG_HND_APA_QU_INDICATION (280U)

/*SignalName: APA_PA_STATE
  Endian:Motor  Type:Uint8  StartBit:31  Length:3*/
#define SIG_HND_APA_PA_STATE (281U)

/*SignalName: APA_ST
  Endian:Motor  Type:Uint8  StartBit:28  Length:3*/
#define SIG_HND_APA_ST (282U)

/*SignalName: APA_IN
  Endian:Motor  Type:Uint8  StartBit:39  Length:3*/
#define SIG_HND_APA_IN (283U)

/*SignalName: APA_CPC
  Endian:Motor  Type:Uint8  StartBit:36  Length:2*/
#define SIG_HND_APA_CPC (284U)

/*SignalName: APA_S_SI
  Endian:Motor  Type:Uint8  StartBit:23  Length:3*/
#define SIG_HND_APA_S_SI (285U)

/*SignalName: APA_D_RQ
  Endian:Motor  Type:Uint8  StartBit:20  Length:5*/
#define SIG_HND_APA_D_RQ (286U)

/*SignalName: APA_PR_BAR
  Endian:Motor  Type:Uint8  StartBit:6  Length:7*/
#define SIG_HND_APA_PR_BAR (287U)

/*********************************************************************************/

/*********************************************************************************/
/*MessageID: 0X60D   MessageHandle: IPDU_HND_BCM_GeneralStatus   CycTime: 100mS*/
/*SignalName: DOOR_SW
  Endian:Motor  Type:Uint8  StartBit:7  Length:5*/
#define SIG_HND_DOOR_SW (288U)

/*SignalName: TAIL_L_REQ
  Endian:Motor  Type:Boolean  StartBit:2  Length:1*/
#define SIG_HND_TAIL_L_REQ (289U)

/*SignalName: HL_LOW_REQ
  Endian:Motor  Type:Boolean  StartBit:1  Length:1*/
#define SIG_HND_HL_LOW_REQ (290U)

/*SignalName: TURN_IND
  Endian:Motor  Type:Uint8  StartBit:15  Length:3*/
#define SIG_HND_TURN_IND (291U)

/*SignalName: HL_HIGH_REQ
  Endian:Motor  Type:Boolean  StartBit:11  Length:1*/
#define SIG_HND_HL_HIGH_REQ (292U)

/*SignalName: FR_FOG_L_REQ
  Endian:Motor  Type:Boolean  StartBit:8  Length:1*/
#define SIG_HND_FR_FOG_L_REQ (293U)

/*SignalName: RR_FOG_L
  Endian:Motor  Type:Boolean  StartBit:18  Length:1*/
#define SIG_HND_RR_FOG_L (294U)

/*SignalName: BUZZ_REQ
  Endian:Motor  Type:Uint8  StartBit:29  Length:5*/
#define SIG_HND_BUZZ_REQ (295U)

/*SignalName: DTRL_REQ
  Endian:Motor  Type:Boolean  StartBit:54  Length:1*/
#define SIG_HND_DTRL_REQ (296U)

/*SignalName: IGN_SW
  Endian:Motor  Type:Boolean  StartBit:10  Length:1*/
#define SIG_HND_IGN_SW (297U)

/*SignalName: ACC_SW
  Endian:Motor  Type:Boolean  StartBit:9  Length:1*/
#define SIG_HND_ACC_SW (298U)

/*********************************************************************************/

/*********************************************************************************/
/*MessageID: 0X625   MessageHandle: IPDU_HND_USM_GeneralStatus   CycTime: 100mS*/
/*SignalName: OIL_P_SW_USM
  Endian:Motor  Type:Boolean  StartBit:31  Length:1*/
#define SIG_HND_OIL_P_SW_USM (299U)

/*SignalName: FR_WIP
  Endian:Motor  Type:Uint8  StartBit:3  Length:2*/
#define SIG_HND_FR_WIP (300U)

/*SignalName: HL_LOW
  Endian:Motor  Type:Boolean  StartBit:13  Length:1*/
#define SIG_HND_HL_LOW (301U)

/*SignalName: HL_HIGH
  Endian:Motor  Type:Boolean  StartBit:12  Length:1*/
#define SIG_HND_HL_HIGH (302U)

/*SignalName: FR_FOG
  Endian:Motor  Type:Boolean  StartBit:11  Length:1*/
#define SIG_HND_FR_FOG (303U)

/*********************************************************************************/

/*********************************************************************************/
/*MessageID: 0X628   MessageHandle: IPDU_HND_LowWarningSignal628   CycTime: 100mS*/
/*SignalName: LOW_WNG_628
  Endian:Motor  Type:Boolean  StartBit:16  Length:1*/
#define SIG_HND_LOW_WNG_628 (304U)

/*********************************************************************************/

/*********************************************************************************/
/*MessageID: 0X629   MessageHandle: IPDU_HND_LOW_WNG_STATUS_629   CycTime: 100mS*/
/*SignalName: LOW_WNG_629
  Endian:Motor  Type:Boolean  StartBit:16  Length:1*/
#define SIG_HND_LOW_WNG_629 (305U)

/*********************************************************************************/

/*********************************************************************************/
/*MessageID: 0X6E2   MessageHandle: IPDU_HND_ECCSMSG8_OBD_IS   CycTime: 100mS*/
/*SignalName: ISMSKSW
  Endian:Motor  Type:Boolean  StartBit:49  Length:1*/
#define SIG_HND_ISMSKSW (306U)

/*SignalName: ISINDMD
  Endian:Motor  Type:Uint8  StartBit:51  Length:2*/
#define SIG_HND_ISINDMD (307U)

/*SignalName: ISSAP
  Endian:Motor  Type:Boolean  StartBit:41  Length:1*/
#define SIG_HND_ISSAP (308U)

/*SignalName: CHRGLREQ
  Endian:Motor  Type:Boolean  StartBit:48  Length:1*/
#define SIG_HND_CHRGLREQ (309U)

/*********************************************************************************/

#define COM_RX_SIGNAL_MAX_NUM (310U)

#define COM_TX_SIGNAL_START_INDEX COM_RX_SIGNAL_MAX_NUM

/******************************** Tx Signal Handle *******************************/
/*********************************************************************************/
/*MessageID: 0X280   MessageHandle: IPDU_HND_CLUSTER_BasicInfo_1   CycTime: 20mS*/
/*SignalName: VSP20_MET
  Endian:Motor  Type:Uint16  StartBit:39  Length:16*/
#define SIG_HND_VSP20_MET (310U)

/*SignalName: BAC_SW
  Endian:Motor  Type:Boolean  StartBit:1  Length:1*/
#define SIG_HND_BAC_SW (311U)

/*SignalName: DC_EXISTANCE
  Endian:Motor  Type:Boolean  StartBit:0  Length:1*/
#define SIG_HND_DC_EXISTANCE (312U)

/*SignalName: FGAUGE
  Endian:Motor  Type:Uint16  StartBit:9  Length:10*/
#define SIG_HND_FGAUGE (313U)

/*SignalName: FMad
  Endian:Motor  Type:Uint16  StartBit:55  Length:10*/
#define SIG_HND_FMad (314U)

/*SignalName: ACFRDEFSW
  Endian:Motor  Type:Boolean  StartBit:61  Length:1*/
#define SIG_HND_ACFRDEFSW (315U)

/*SignalName: PBW_WARNING
  Endian:Motor  Type:Boolean  StartBit:60  Length:1*/
#define SIG_HND_PBW_WARNING (316U)

/*SignalName: CAP_IND_RST_STA
  Endian:Motor  Type:Boolean  StartBit:57  Length:1*/
#define SIG_HND_CAP_IND_RST_STA (317U)

/*SignalName: BAC_SW_AS
  Endian:Motor  Type:Boolean  StartBit:59  Length:1*/
#define SIG_HND_BAC_SW_AS (318U)

/*********************************************************************************/

/*********************************************************************************/
/*MessageID: 0X2DE   MessageHandle: IPDU_HND_METMSG1   CycTime: 10mS*/
/*SignalName: AVE_ECO
  Endian:Motor  Type:Uint16  StartBit:31  Length:12*/
#define SIG_HND_AVE_ECO (319U)

/*SignalName: DTE
  Endian:Motor  Type:Uint16  StartBit:55  Length:16*/
#define SIG_HND_DTE (320U)

/*SignalName: RENSWN
  Endian:Motor  Type:Boolean  StartBit:7  Length:1*/
#define SIG_HND_RENSWN (321U)

/*SignalName: RENSWP
  Endian:Motor  Type:Boolean  StartBit:6  Length:1*/
#define SIG_HND_RENSWP (322U)

/*SignalName: STRDWNSW
  Endian:Motor  Type:Boolean  StartBit:5  Length:1*/
#define SIG_HND_STRDWNSW (323U)

/*SignalName: STRUPSW
  Endian:Motor  Type:Boolean  StartBit:4  Length:1*/
#define SIG_HND_STRUPSW (324U)

/*SignalName: DOWNSW
  Endian:Motor  Type:Boolean  StartBit:3  Length:1*/
#define SIG_HND_DOWNSW (325U)

/*SignalName: UPSW
  Endian:Motor  Type:Boolean  StartBit:2  Length:1*/
#define SIG_HND_UPSW (326U)

/*SignalName: NOTMRNG
  Endian:Motor  Type:Boolean  StartBit:1  Length:1*/
#define SIG_HND_NOTMRNG (327U)

/*SignalName: MRNG
  Endian:Motor  Type:Boolean  StartBit:0  Length:1*/
#define SIG_HND_MRNG (328U)

/*SignalName: TOWMODE
  Endian:Motor  Type:Boolean  StartBit:15  Length:1*/
#define SIG_HND_TOWMODE (329U)

/*SignalName: RNGSW1
  Endian:Motor  Type:Boolean  StartBit:14  Length:1*/
#define SIG_HND_RNGSW1 (330U)

/*SignalName: ODOFFSW
  Endian:Motor  Type:Boolean  StartBit:13  Length:1*/
#define SIG_HND_ODOFFSW (331U)

/*SignalName: TPMS_RST
  Endian:Motor  Type:Boolean  StartBit:11  Length:1*/
#define SIG_HND_TPMS_RST (332U)

/*SignalName: POWSW
  Endian:Motor  Type:Boolean  StartBit:10  Length:1*/
#define SIG_HND_POWSW (333U)

/*SignalName: SportMode_SW
  Endian:Motor  Type:Boolean  StartBit:8  Length:1*/
#define SIG_HND_SportMode_SW (334U)

/*SignalName: REQ_TRAILER_CHK
  Endian:Motor  Type:Boolean  StartBit:18  Length:1*/
#define SIG_HND_REQ_TRAILER_CHK (335U)

/*SignalName: B_Circuit_ST
  Endian:Motor  Type:Boolean  StartBit:17  Length:1*/
#define SIG_HND_B_Circuit_ST (336U)

/*SignalName: RENSWR
  Endian:Motor  Type:Boolean  StartBit:19  Length:1*/
#define SIG_HND_RENSWR (337U)

/*SignalName: ECO_MODE_SW
  Endian:Motor  Type:Boolean  StartBit:9  Length:1*/
#define SIG_HND_ECO_MODE_SW (338U)

/*********************************************************************************/

/*********************************************************************************/
/*MessageID: 0X355   MessageHandle: IPDU_HND_CLUSTER_BasicInfo_2   CycTime: 40mS*/
/*SignalName: VSP40_MET
  Endian:Motor  Type:Uint16  StartBit:7  Length:16*/
#define SIG_HND_VSP40_MET (339U)

/*SignalName: VS_DISP
  Endian:Motor  Type:Uint16  StartBit:23  Length:16*/
#define SIG_HND_VS_DISP (340U)

/*SignalName: ICCExistance
  Endian:Motor  Type:Boolean  StartBit:36  Length:1*/
#define SIG_HND_ICCExistance (341U)

/*SignalName: EX_TEMP
  Endian:Motor  Type:Uint8  StartBit:47  Length:8*/
#define SIG_HND_EX_TEMP (342U)

/*SignalName: MARKET
  Endian:Motor  Type:Uint8  StartBit:55  Length:8*/
#define SIG_HND_MARKET (343U)

/*SignalName: TSOC_MET
  Endian:Motor  Type:Boolean  StartBit:63  Length:1*/
#define SIG_HND_TSOC_MET (344U)

/*SignalName: VSP_REV_BUZZER
  Endian:Motor  Type:Boolean  StartBit:62  Length:1*/
#define SIG_HND_VSP_REV_BUZZER (345U)

/*SignalName: STAT_CHG_REQ
  Endian:Motor  Type:Uint8  StartBit:61  Length:6*/
#define SIG_HND_STAT_CHG_REQ (346U)

/*SignalName: Display_Unit_355
  Endian:Motor  Type:Boolean  StartBit:37  Length:1*/
#define SIG_HND_Display_Unit_355 (347U)

/*SignalName: Oil_change_counter_reset
  Endian:Motor  Type:Boolean  StartBit:35  Length:1*/
#define SIG_HND_Oil_change_counter_reset (348U)

/*********************************************************************************/

/*********************************************************************************/
/*MessageID: 0X447   MessageHandle: IPDU_HND_DA_Information   CycTime: 0mS*/
/*SignalName: Sunroof_SW
  Endian:Motor  Type:Uint8  StartBit:7  Length:4*/
#define SIG_HND_Sunroof_SW (349U)

/*SignalName: FL_WindowSW
  Endian:Motor  Type:Uint8  StartBit:15  Length:4*/
#define SIG_HND_FL_WindowSW (350U)

/*SignalName: FR_WindowSW
  Endian:Motor  Type:Uint8  StartBit:11  Length:4*/
#define SIG_HND_FR_WindowSW (351U)

/*SignalName: RL_WindowSW
  Endian:Motor  Type:Uint8  StartBit:23  Length:4*/
#define SIG_HND_RL_WindowSW (352U)

/*SignalName: RR_WindowSW
  Endian:Motor  Type:Uint8  StartBit:19  Length:4*/
#define SIG_HND_RR_WindowSW (353U)

/*SignalName: DA_RearviewMirrorOnOff
  Endian:Motor  Type:Uint8  StartBit:30  Length:2*/
#define SIG_HND_DA_RearviewMirrorOnOff (354U)

/*SignalName: DA_RoomLampOnOff
  Endian:Motor  Type:Uint8  StartBit:28  Length:3*/
#define SIG_HND_DA_RoomLampOnOff (355U)

/*********************************************************************************/

/*********************************************************************************/
/*MessageID: 0X4F8   MessageHandle: IPDU_HND_CLUSTER_BasicInfo_3   CycTime: 100mS*/
/*SignalName: FUEL_Remain
  Endian:Motor  Type:Uint16  StartBit:7  Length:10*/
#define SIG_HND_FUEL_Remain (356U)

/*SignalName: FUEL_FirstW_L
  Endian:Motor  Type:Boolean  StartBit:13  Length:1*/
#define SIG_HND_FUEL_FirstW_L (357U)

/*SignalName: FUEL_SecondW
  Endian:Motor  Type:Boolean  StartBit:12  Length:1*/
#define SIG_HND_FUEL_SecondW (358U)

/*SignalName: AVE_Fuel_Single
  Endian:Motor  Type:Uint16  StartBit:9  Length:10*/
#define SIG_HND_AVE_Fuel_Single (359U)

/*********************************************************************************/

/*********************************************************************************/
/*MessageID: 0X567   MessageHandle: IPDU_HND_SystemTimeInfo   CycTime: 500mS*/
/*SignalName: YEAR
  Endian:Motor  Type:Uint8  StartBit:6  Length:7*/
#define SIG_HND_YEAR (360U)

/*SignalName: MONTH
  Endian:Motor  Type:Uint8  StartBit:15  Length:4*/
#define SIG_HND_MONTH (361U)

/*SignalName: DAY
  Endian:Motor  Type:Uint8  StartBit:11  Length:5*/
#define SIG_HND_DAY (362U)

/*SignalName: HOUR
  Endian:Motor  Type:Uint8  StartBit:22  Length:5*/
#define SIG_HND_HOUR (363U)

/*SignalName: MINUTE
  Endian:Motor  Type:Uint8  StartBit:17  Length:6*/
#define SIG_HND_MINUTE (364U)

/*SignalName: SECOND
  Endian:Motor  Type:Uint8  StartBit:27  Length:6*/
#define SIG_HND_SECOND (365U)

/*SignalName: GPS_Signal
  Endian:Motor  Type:Boolean  StartBit:35  Length:1*/
#define SIG_HND_GPS_Signal (366U)

/*********************************************************************************/

/*********************************************************************************/
/*MessageID: 0X5A8   MessageHandle: IPDU_HND_DA_ControlData   CycTime: 100mS*/
/*SignalName: Lamp_headlampAngle
  Endian:Motor  Type:Uint8  StartBit:7  Length:3*/
#define SIG_HND_Lamp_headlampAngle (367U)

/*SignalName: Lamp_atmosphere_OnOff
  Endian:Motor  Type:Boolean  StartBit:4  Length:1*/
#define SIG_HND_Lamp_atmosphere_OnOff (368U)

/*SignalName: RhythmSignal
  Endian:Motor  Type:Uint8  StartBit:12  Length:4*/
#define SIG_HND_RhythmSignal (369U)

/*SignalName: Lamp_atmosphereColor
  Endian:Motor  Type:Uint8  StartBit:23  Length:3*/
#define SIG_HND_Lamp_atmosphereColor (370U)

/*SignalName: Wireless_charge_Switch
  Endian:Motor  Type:Boolean  StartBit:20  Length:1*/
#define SIG_HND_Wireless_charge_Switch (371U)

/*SignalName: DA_Source_Signal_5A8
  Endian:Motor  Type:Uint8  StartBit:19  Length:3*/
#define SIG_HND_DA_Source_Signal_5A8 (372U)

/*SignalName: PANEL_SW
  Endian:Motor  Type:Boolean  StartBit:16  Length:1*/
#define SIG_HND_PANEL_SW (373U)

/*SignalName: Amb_Color_Adjustment_DA
  Endian:Motor  Type:Uint8  StartBit:38  Length:7*/
#define SIG_HND_Amb_Color_Adjustment_DA (374U)

/*SignalName: Amb_Music_Rhythm_Switch_DA
  Endian:Motor  Type:Boolean  StartBit:39  Length:1*/
#define SIG_HND_Amb_Music_Rhythm_Switch_DA (375U)

/*SignalName: Amb_Tem_Switch_DA
  Endian:Motor  Type:Boolean  StartBit:47  Length:1*/
#define SIG_HND_Amb_Tem_Switch_DA (376U)

/*SignalName: Amb_Speeding_Switch_DA
  Endian:Motor  Type:Boolean  StartBit:46  Length:1*/
#define SIG_HND_Amb_Speeding_Switch_DA (377U)

/*SignalName: Amb_Speeding_info
  Endian:Motor  Type:Boolean  StartBit:45  Length:1*/
#define SIG_HND_Amb_Speeding_info (378U)

/*SignalName: Amb_Birthday
  Endian:Motor  Type:Boolean  StartBit:44  Length:1*/
#define SIG_HND_Amb_Birthday (379U)

/*SignalName: Amb_Holiday
  Endian:Motor  Type:Uint8  StartBit:27  Length:3*/
#define SIG_HND_Amb_Holiday (380U)

/*SignalName: Rearview_mirror_adjustment
  Endian:Motor  Type:Uint8  StartBit:31  Length:2*/
#define SIG_HND_Rearview_mirror_adjustment (381U)

/*********************************************************************************/

/*********************************************************************************/
/*MessageID: 0X5B7   MessageHandle: IPDU_HND_CLIMATE_ControlData   CycTime: 100mS*/
/*SignalName: AC_TempUp_D
  Endian:Motor  Type:Boolean  StartBit:7  Length:1*/
#define SIG_HND_AC_TempUp_D (382U)

/*SignalName: AC_TempDn_D
  Endian:Motor  Type:Boolean  StartBit:6  Length:1*/
#define SIG_HND_AC_TempDn_D (383U)

/*SignalName: AC_Mode
  Endian:Motor  Type:Boolean  StartBit:5  Length:1*/
#define SIG_HND_AC_Mode (384U)

/*SignalName: AC_Defronst
  Endian:Motor  Type:Boolean  StartBit:4  Length:1*/
#define SIG_HND_AC_Defronst (385U)

/*SignalName: AC_AirMAX_SW
  Endian:Motor  Type:Boolean  StartBit:2  Length:1*/
#define SIG_HND_AC_AirMAX_SW (386U)

/*SignalName: AC_Recirc_SW
  Endian:Motor  Type:Boolean  StartBit:3  Length:1*/
#define SIG_HND_AC_Recirc_SW (387U)

/*SignalName: AC_A_C
  Endian:Motor  Type:Boolean  StartBit:1  Length:1*/
#define SIG_HND_AC_A_C (388U)

/*SignalName: AC_SYNC
  Endian:Motor  Type:Boolean  StartBit:0  Length:1*/
#define SIG_HND_AC_SYNC (389U)

/*SignalName: AC_Fan_speed_setting
  Endian:Motor  Type:Uint8  StartBit:15  Length:4*/
#define SIG_HND_AC_Fan_speed_setting (390U)

/*SignalName: AC_Reserve
  Endian:Motor  Type:Boolean  StartBit:11  Length:1*/
#define SIG_HND_AC_Reserve (391U)

/*SignalName: AC_AUTO
  Endian:Motor  Type:Boolean  StartBit:10  Length:1*/
#define SIG_HND_AC_AUTO (392U)

/*SignalName: AC_BlowerPlus
  Endian:Motor  Type:Boolean  StartBit:9  Length:1*/
#define SIG_HND_AC_BlowerPlus (393U)

/*SignalName: AC_BlowerMinus
  Endian:Motor  Type:Boolean  StartBit:8  Length:1*/
#define SIG_HND_AC_BlowerMinus (394U)

/*SignalName: AC_AirVentDirectSetting
  Endian:Motor  Type:Uint8  StartBit:23  Length:3*/
#define SIG_HND_AC_AirVentDirectSetting (395U)

/*SignalName: AC_TempUp_P
  Endian:Motor  Type:Boolean  StartBit:20  Length:1*/
#define SIG_HND_AC_TempUp_P (396U)

/*SignalName: AC_TempDn_P
  Endian:Motor  Type:Boolean  StartBit:19  Length:1*/
#define SIG_HND_AC_TempDn_P (397U)

/*SignalName: AC_Redefronst
  Endian:Motor  Type:Boolean  StartBit:18  Length:1*/
#define SIG_HND_AC_Redefronst (398U)

/*SignalName: AC_ONOFF
  Endian:Motor  Type:Boolean  StartBit:17  Length:1*/
#define SIG_HND_AC_ONOFF (399U)

/*SignalName: AC_Target_Temp_TS_D
  Endian:Motor  Type:Uint8  StartBit:29  Length:6*/
#define SIG_HND_AC_Target_Temp_TS_D (400U)

/*SignalName: AC_DeforstVR
  Endian:Motor  Type:Uint8  StartBit:47  Length:2*/
#define SIG_HND_AC_DeforstVR (401U)

/*SignalName: AC_Recirc_VR
  Endian:Motor  Type:Uint8  StartBit:45  Length:2*/
#define SIG_HND_AC_Recirc_VR (402U)

/*SignalName: AC_AC_VR
  Endian:Motor  Type:Uint8  StartBit:43  Length:2*/
#define SIG_HND_AC_AC_VR (403U)

/*SignalName: AC_SYNC_VR
  Endian:Motor  Type:Uint8  StartBit:41  Length:2*/
#define SIG_HND_AC_SYNC_VR (404U)

/*SignalName: AC_Redeforst_VR
  Endian:Motor  Type:Uint8  StartBit:55  Length:2*/
#define SIG_HND_AC_Redeforst_VR (405U)

/*SignalName: AC_ONOFF_VR
  Endian:Motor  Type:Uint8  StartBit:53  Length:2*/
#define SIG_HND_AC_ONOFF_VR (406U)

/*SignalName: AC_AirMAX_VR
  Endian:Motor  Type:Uint8  StartBit:51  Length:2*/
#define SIG_HND_AC_AirMAX_VR (407U)

/*SignalName: AC_Reserve3
  Endian:Motor  Type:Boolean  StartBit:39  Length:1*/
#define SIG_HND_AC_Reserve3 (408U)

/*SignalName: AC_Target_Temp_TS_P
  Endian:Motor  Type:Uint8  StartBit:38  Length:7*/
#define SIG_HND_AC_Target_Temp_TS_P (409U)

/*SignalName: TempUp_E
  Endian:Motor  Type:Boolean  StartBit:63  Length:1*/
#define SIG_HND_TempUp_E (410U)

/*SignalName: TempDn_E
  Endian:Motor  Type:Boolean  StartBit:62  Length:1*/
#define SIG_HND_TempDn_E (411U)

/*SignalName: Target_E_Temp_TS_VR
  Endian:Motor  Type:Uint8  StartBit:61  Length:4*/
#define SIG_HND_Target_E_Temp_TS_VR (412U)

/*SignalName: Auto_condition_mode_gear
  Endian:Motor  Type:Uint8  StartBit:16  Length:3*/
#define SIG_HND_Auto_condition_mode_gear (413U)

/*********************************************************************************/

/*********************************************************************************/
/*MessageID: 0X5C5   MessageHandle: IPDU_HND_CLUSTER_GeneralStatus   CycTime: 100mS*/
/*SignalName: DIS_TOTAL
  Endian:Motor  Type:Uint32  StartBit:15  Length:24*/
#define SIG_HND_DIS_TOTAL (414U)

/*SignalName: CLUSTER_REFUSE
  Endian:Motor  Type:Uint8  StartBit:7  Length:2*/
#define SIG_HND_CLUSTER_REFUSE (415U)

/*SignalName: FUEL_LOW
  Endian:Motor  Type:Boolean  StartBit:5  Length:1*/
#define SIG_HND_FUEL_LOW (416U)

/*SignalName: BRAKE_SYSTEM
  Endian:Motor  Type:Boolean  StartBit:3  Length:1*/
#define SIG_HND_BRAKE_SYSTEM (417U)

/*SignalName: MTSRC_SW
  Endian:Motor  Type:Boolean  StartBit:32  Length:1*/
#define SIG_HND_MTSRC_SW (418U)

/*SignalName: CLUSTER_WAKE_SLEEP_REQ
  Endian:Motor  Type:Uint8  StartBit:43  Length:2*/
#define SIG_HND_CLUSTER_WAKE_SLEEP_REQ (419U)

/*SignalName: SNOW_SW
  Endian:Motor  Type:Boolean  StartBit:55  Length:1*/
#define SIG_HND_SNOW_SW (420U)

/*SignalName: HandBreakSwitch
  Endian:Motor  Type:Boolean  StartBit:2  Length:1*/
#define SIG_HND_HandBreakSwitch (421U)

/*********************************************************************************/

/*********************************************************************************/
/*MessageID: 0X5E5   MessageHandle: IPDU_HND_IKEY_Display_SwitchStatus   CycTime: 100mS*/
/*SignalName: APUcfg
  Endian:Motor  Type:Uint8  StartBit:7  Length:2*/
#define SIG_HND_APUcfg (422U)

/*SignalName: WALcfg
  Endian:Motor  Type:Uint8  StartBit:5  Length:2*/
#define SIG_HND_WALcfg (423U)

/*SignalName: VDC_ONOFF
  Endian:Motor  Type:Uint8  StartBit:13  Length:2*/
#define SIG_HND_VDC_ONOFF (424U)

/*SignalName: check_sum
  Endian:Motor  Type:Uint8  StartBit:63  Length:4*/
#define SIG_HND_check_sum (425U)

/*SignalName: Message_counter
  Endian:Motor  Type:Uint8  StartBit:59  Length:4*/
#define SIG_HND_Message_counter (426U)

/*SignalName: DA_RefusetoSleep
  Endian:Motor  Type:Uint8  StartBit:3  Length:2*/
#define SIG_HND_DA_RefusetoSleep (427U)

/*SignalName: AutoHoldSW
  Endian:Motor  Type:Uint8  StartBit:11  Length:2*/
#define SIG_HND_AutoHoldSW (428U)

/*********************************************************************************/

/*********************************************************************************/
/*MessageID: 0X5FE   MessageHandle: IPDU_HND_TCU_DA_information   CycTime: 100mS*/
/*SignalName: TCU_SpeakerReady
  Endian:Motor  Type:Uint8  StartBit:23  Length:2*/
#define SIG_HND_TCU_SpeakerReady (429U)

/*SignalName: TCU_SpeakerOff
  Endian:Motor  Type:Uint8  StartBit:21  Length:2*/
#define SIG_HND_TCU_SpeakerOff (430U)

/*SignalName: TCU_VedioPushResult
  Endian:Motor  Type:Uint8  StartBit:31  Length:2*/
#define SIG_HND_TCU_VedioPushResult (431U)

/*SignalName: TCU_VedioPushFail
  Endian:Motor  Type:Uint8  StartBit:29  Length:6*/
#define SIG_HND_TCU_VedioPushFail (432U)

/*SignalName: TCU_PicturePushResult
  Endian:Motor  Type:Uint8  StartBit:39  Length:2*/
#define SIG_HND_TCU_PicturePushResult (433U)

/*SignalName: TCU_PictureFail
  Endian:Motor  Type:Uint8  StartBit:37  Length:6*/
#define SIG_HND_TCU_PictureFail (434U)

/*SignalName: TCU_AutoOnOff
  Endian:Motor  Type:Uint8  StartBit:47  Length:2*/
#define SIG_HND_TCU_AutoOnOff (435U)

/*********************************************************************************/

/*********************************************************************************/
/*MessageID: 0X602   MessageHandle: IPDU_HND_CLUSTER_WakeUpFrame   CycTime: 0mS*/
/*SignalName: CLUSTER_WAKEUP_SIGNAL
  Endian:Motor  Type:Uint8  StartBit:7  Length:8*/
#define SIG_HND_CLUSTER_WAKEUP_SIGNAL (436U)

/*********************************************************************************/

/*********************************************************************************/
/*MessageID: 0X635   MessageHandle: IPDU_HND_DA_WakeUpFrame   CycTime: 0mS*/
/*SignalName: DA_WakeUp_Signal
  Endian:Motor  Type:Uint8  StartBit:7  Length:8*/
#define SIG_HND_DA_WakeUp_Signal (437U)

/*********************************************************************************/

#define COM_TX_SIGNAL_MAX_NUM (128U)

#define COM_SIGNAL_MAX_NUM (438U)

/*===============================================================================*/
/*============================== END: SIGNAL HANDLE =============================*/
/*===============================================================================*/
#ifdef __cplusplus
}
#endif // __cplusplus

#endif

/*============================= END OF FILE: Com_Cfg.h ==========================*/
