/*!Warning!:Please don't modify this file,this is generated by tools!*/
/********************************************************************
File name: VirtualSig_Cfg.h
Author: Stephen Du
Version: V1.0
Timestamp: 2018-09-06 10:57:27
Description:
Others:
Function List:
1. ....
History: /
1. Date:
Author:
Modification:
2. ...
********************************************************************/
#ifndef _VIRTUALSIG_CFG_H_
#define _VIRTUALSIG_CFG_H_

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

#include "Std_Types.h"

#define VIRTUALSIG_DEBUG_TRACE STD_OFF

#define VIRTUALSIG_ID_DIAGCMD (0U)
#define VIRTUALSIG_ID_NM_WAKEUP (1U)
#define VIRTUALSIG_ID_BUS_SLEEP (2U)
#define VIRTUALSIG_ID_VOLTSTATE (3U)
#define VIRTUALSIG_ID_RESTART (4U)
#define VIRTUALSIG_ID_UDS_REQ (5U)
#define VIRTUALSIG_ID_TEMPAMP_STATUS (6U)
#define VIRTUALSIG_ID_TEMPBOARD_STATUS (7U)
#define VIRTUALSIG_ID_BATTVOLT_STATUS (8U)
#define VIRTUALSIG_ID_IGN (9U)
#define VIRTUALSIG_ID_SWC_PRESS (10U)
#define VIRTUALSIG_ID_SWC_REL (11U)
#define VIRTUALSIG_ID_SWC_HOLD (12U)
#define VIRTUALSIG_ID_SWC_HOLD_REL (13U)
#define VIRTUALSIG_ID_LCD (14U)
#define VIRTUALSIG_ID_LVI_SLEEP (15U)
#define VIRTUALSIG_ID_CAN_SEND_ENABLE (16U)
#define VIRTUALSIG_ID_MAX (17U)


#ifdef __cplusplus
}
#endif // __cplusplus

#endif
/*=========================== END OF FILE: VirtualSig_Cfg.h ===========================*/
