/*!Warning!:Please don't modify this file,this is generated by tools!*/
/********************************************************************
File name: Task_GyroAcc_Cfg.h
Author: Stephen Du
Version: V1.0
Timestamp: 2018-11-15 15:27:38
Description:
Others:
Function List:
1. ....
History: /
1. Date:
Author:
Modification:
2. ...
********************************************************************/
#ifndef _TASK_GYROACC_CFG_H_
#define _TASK_GYROACC_CFG_H_

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

#include "Std_Types.h"

#define TASK_GYROACC_DEBUG_TRACE STD_ON
#define TASK_GYROACC_STACK_MONITOR STD_OFF

#ifdef __cplusplus
}
#endif // __cplusplus

#endif
/*=========================== END OF FILE: Task_GyroAcc_Cfg.h ===========================*/
