/*!Warning!:Please don't modify this file,this is generated by tools!*/
/********************************************************************
File name: Task_GyroAcc.c
Author: Stephen Du
Version: V1.0
Timestamp: 2018-11-15 15:27:38
Description:
Others:
Function List:
1. ....
History: /
1. Date:
Author:
Modification:
2. ...
********************************************************************/
#include "System_Task.h"
#include "System_Signal.h"
#include "Task_GyroAcc_Cfg.h"
#if (STD_ON == TASK_GYROACC_DEBUG_TRACE)
#include "trace.h"
#endif
/*********** START: INCLUDE FILES ************/
#include "gyroacc_service.h"
#include "ExternRTC.h"
#include "AC_CTL.h"
#include "SecondPanel.h"
//#include "radio_app.h"
#include"update_sys.h"

#define SENCONDPANEL_CYCLE_TIME  200
#define SENCONDPANEL_CYCLE_TIME_MIUNTES  6000

/************ END: INCLUDE FILES *************/
void Task_GyroAcc(void * pvParameters)
{
	boolean l_returnValue = E_NOT_OK;
	SystemTaskMsgInfoType l_msgInfo = {0XFFFF, 0U, NULL};
#if (STD_ON == TASK_GYROACC_STACK_MONITOR)
	uint16 l_stackSize = 0U;
#endif
	/*===============================================================================*/
	/*=============================== START: USER CODE ==============================*/
	/*===============================================================================*/
	/***************************** START: VARIABLE DEFINE ****************************/
	/*Warning: Change the following array size according to your real length.*/
	uint8 l_msgDataBuf[4] = {0U, 0U, 0U, 0U};
#if 0
	static uint32 sGYROTickcounter = 1;
	static uint32 sGYROTickValu[2] = {0,0} ;
#endif
	/****************************** END: VARIABLE DEFINE *****************************/
	
	/********************* START: SOMETHING ONLY NEED EXEC ONCE **********************/
	l_msgInfo.parBufPtr = &l_msgDataBuf[0];

	static uint16 sSecondCount = 0;
	static uint16 sMiuntesCount = 0;

	/********************** END: SOMETHING ONLY NEED EXEC ONCE ***********************/
	
	/**************************** START: SIGNAL SUBSCRIBE ****************************/
	/*
	System_Signal_Subscribe(SYSTEM_SIG_ID_XXX, SYSTEM_TASK_ID_GYROACC);
	System_Signal_SubSpecValue(SYSTEM_SIG_ID_XXX, SYSTEM_TASK_ID_GYROACC, X);
	*/
	System_Signal_Subscribe(SYSTEM_SIG_ID_10MS, SYSTEM_TASK_ID_GYROACC);

#if UPDATE_BOOTLOADER_FEATURE
	updateSys_Init();  //Update bootloader in app;hyl add
#endif

	/***************************** END: SIGNAL SUBSCRIBE *****************************/
	/*===============================================================================*/
	/*================================ END: USER CODE ===============================*/
	/*===============================================================================*/
	while (1)
	{
		l_returnValue = System_Task_ReceiveMessage(SYSTEM_TASK_ID_GYROACC, &l_msgInfo, FALSE, OS_WAITFOREVER);
		if (E_OK == l_returnValue)
		{
			/*
			You can use: "l_msgInfo.msgId" to get the message id.
			You can use: "l_msgInfo.size" to get the message size.
			You can use: "l_msgInfo.parBufPtr[]" or "l_msgDataBuf[]"
			             to get the message content if the message size not equal 0.
			 */
			/*===============================================================================*/
			/*=============================== START: USER CODE ==============================*/
			/*===============================================================================*/
			if (SYSTEM_SIG_ID_10MS == l_msgInfo.msgId)
			{
				//GyroAcc_MainFunction();
#if 0
				//AcCtl_MainFunction();
#endif

#if 1
				ExtrRtc_MainFunction();
#endif

#if 0
				#if (STD_ON == TASK_GYROACC_DEBUG_TRACE)
					sGYROTickcounter++;
					sGYROTickValu[0] = System_GetTickValue();
					if(( sGYROTickValu[0] - sGYROTickValu[1])>=20)
					{
						//TracePrintf(NM_TRACE, TRACE_WARNING, "[GYRO-CYCLE-ERR]:%d %d\r\n",sGYROTickcounter/100,( sGYROTickValu[0] - sGYROTickValu[1]));
					}
					sGYROTickValu[1] = sGYROTickValu[0];
				#endif
#endif

//				sMiuntesCount++;
//				if(sMiuntesCount >= SENCONDPANEL_CYCLE_TIME_MIUNTES)  //1minutes
//				{
//					sMiuntesCount = 0;
//					GetSecondPanelRtcTimeValue();
//				}
//
//				sSecondCount++;
//				if(sSecondCount >= SENCONDPANEL_CYCLE_TIME)
//				{
//					sSecondCount = 0;
//					SendDataToSecondPanel();
//				}

#if UPDATE_BOOTLOADER_FEATURE
				updateSys_Loop();   //bootloader update handle;hyl add
#endif

			}

			/*===============================================================================*/
			/*================================ END: USER CODE ===============================*/
			/*===============================================================================*/
#if (STD_ON == TASK_GYROACC_STACK_MONITOR)
			l_stackSize = uxTaskGetStackHighWaterMark(NULL);
#if (STD_ON == TASK_GYROACC_DEBUG_TRACE)
			TracePrintf(GYROACC_TRACE, TRACE_WARNING, "[Task_GyroAcc-W]:Stack Size:%d\r\n",l_stackSize);
#endif
#endif
		}
	}
}
/*=========================== END OF FILE: Task_GyroAcc.c ===========================*/
