/*!Warning!:Please don't modify this file,this is generated by tools!*/
/********************************************************************
File name: TempBoard.h
Author: Stephen Du
Version: V1.0
Timestamp: 2017-01-16 15:55:25
Description:
Others:
Function List:
1. ....
History: /
1. Date:
Author:
Modification:
2. ...
********************************************************************/
#ifndef _TEMPBOARD_H_
#define _TEMPBOARD_H_

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

#include "Std_Types.h"
#include "TempBoard_Cfg.h"

#define TEMPBOARD_STATE_ULTRALOW (0U)
#define TEMPBOARD_STATE_LOW (1U)
#define TEMPBOARD_STATE_NORMAL (2U)
#define TEMPBOARD_STATE_HIGH (3U)
#define TEMPBOARD_STATE_ULTRAHIGH (4U)
#define TEMPBOARD_STATE_MAX (5U)

/*
*@par Service ID[hex]
*0X0
*@par Sync/Async
*Synchronous
*@par Reentrancy
*Reentrant
*@param[in] None
*
*@param[inout] None
*
*@param[out] None
*
*@retval None
*
*Service to initialize the module;
*You must call this function first before you call the others.
*/
void TempBoard_Init(void);

/*
*@par Service ID[hex]
*0X1
*@par Sync/Async
*Synchronous
*@par Reentrancy
*Reentrant
*@param[in] None
*
*@param[inout] None
*
*@param[out] None
*
*@retval None
*
*Scanf the signal periodically and do the debouncer.
*/
void TempBoard_Scan(void);

/*
*@par Service ID[hex]
*0X2
*@par Sync/Async
*Synchronous
*@par Reentrancy
*Reentrant
*@param[in] None
*
*@param[inout] None
*
*@param[out] None
*
*@retval TEMPBOARD_STATE_ULTRALOW: Mainboard voltage is ultra low.
*@retval TEMPBOARD_STATE_LOW: Mainboard voltage is low.
*@retval TEMPBOARD_STATE_NORMAL: Mainboard voltage is normal.
*@retval TEMPBOARD_STATE_HIGH: Mainboard voltage is high.
*@retval TEMPBOARD_STATE_ULTRAHIGH: Mainboard voltage is ultra high.
*
*Call this function to register user callback.
*/
uint8 TempBoard_GetStatus(void);

/*
*@par Service ID[hex]
*0X3
*@par Sync/Async
*Synchronous
*@par Reentrancy
*Reentrant
*@param[in] None
*
*@param[inout] None
*
*@param[out] TempValue
*
*@retval E_OK/E_NOT_OK
*
*Service to get the temperature value;
*/
uint8 TempBoard_GetValue(sint16 *TempValue);

/*
*@par Service ID[hex]
*0X4
*@par Sync/Async
*Synchronous
*@par Reentrancy
*Reentrant
*@param[in] None
*
*@param[inout] None
*
*@param[out] None
*
*@retval None
*
*Service to deinitialize the module;
*/
void TempBoard_Deinit(void);

#ifdef __cplusplus
}
#endif // __cplusplus

#endif