/*!Warning!:Please don't modify this file,this is generated by tools!*/
/********************************************************************
File name: System_Task_Cfg.h
Author: Stephen Du
Version: V1.0
Timestamp: 2018-11-19 11:21:09
Description:
Others:
Function List:
1. ....
History: /
1. Date:
Author:
Modification:
2. ...
********************************************************************/
#ifndef _SYSTEM_TASK_CFG_H_
#define _SYSTEM_TASK_CFG_H_

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

#include "Std_Types.h"

#define SYSTEM_TASK_DEBUG_TRACE STD_OFF

#define SYSTEM_TASK_ID_SYSMONITOR (0U)
#define SYSTEM_TASK_ID_ALARM (1U)
#define SYSTEM_TASK_ID_GENERAL (2U)
#define SYSTEM_TASK_ID_SWDL (3U)
#define SYSTEM_TASK_ID_SPICOREREAD_M (4U)
#define SYSTEM_TASK_ID_SPICORERX0_M (5U)
#define SYSTEM_TASK_ID_MAX (6U)

#ifdef __cplusplus
}
#endif // __cplusplus

#endif
/*=========================== END OF FILE: System_Task_Cfg.h ===========================*/
