




#include "NvM_Types.h"
#include "NvM.h"  
#include "MemMap.h"
#include "NvM_Cfg.h" 
#include "dtcApp_cfg.h"


#define NVM_WRITE_BLOCK_ONCE 		1
#define NVM_BLOCK_USE_CRC    		2
#define NVM_BLOCK_WRITE_PROT   		4
#define NVM_CALC_RAM_BLOCK_CRC 		8
#define NVM_RESISTANT2CHANGEDSW 	16
#define NVM_SELCT_BLOCK_4READALL	32
#define NVM_SELCT_BLOCK_4WRITEALL	64

NVM_SEC_VAR_UNSPECIFIED uint8 TestID = 0X55u;
NVM_SEC_VAR_UNSPECIFIED uint16 NvM_ConfigureId = NVM_COMPILED_CONFIG_ID;





#include  "odo.h"
#include  "odo.h"
#include  "odo.h"
#include  "Vel_cfg.h"  
#include  "VEL_LT_cfg.h"
#include  "MaintainServiceCfg.h"
#include  "unit.h"
#include  "sys_setting.h"
#include  "odo.h"
#include  "dtcApp_cfg.h"
#include  "dtcCore_cfg.h"
#include  "diagAppWllr_cfg.h"
#include "main.h"
#include "gyroacc_service.h"
#include "sid0x22_cfg.h"
#include "main.h"

const uint8 NVM_BLOCK_NUM_ALL = 144;
uint8 NvM_NvDataBuffer[NVM_MAX_LENGTH_NV_BLOCK + NVM_NV_CRC_MAX_LENGTH];
NvM_AdminBlockType NvM_AdminBlock[NVM_BLOCK_NUM_ALL_DF + 1]={{0}};

const NvM_BlockDescriptorType NvM_BlockDescriptor[NVM_BLOCK_NUM_ALL_DF + 1] =
{
    {0,
        NVM_BLOCK_NATIVE,
    #if ((NVM_API_CONFIG_CLASS_1!=NVM_API_CONFIG_CLASS)&&(STD_ON==NVM_JOB_PRIORITIZATION))
        255,
    #endif
        0,NVM_CRC16,0,0,0,0,NULL_PTR,NULL_PTR,NULL_PTR 
    },
    {
        0, 
        NVM_BLOCK_NATIVE,    
        #if ((NVM_API_CONFIG_CLASS_1!=NVM_API_CONFIG_CLASS)&&(STD_ON==NVM_JOB_PRIORITIZATION))
        0,
        #endif
        NVM_SELCT_BLOCK_4READALL|NVM_SELCT_BLOCK_4WRITEALL|NVM_CALC_RAM_BLOCK_CRC|NVM_BLOCK_USE_CRC|0,
        NVM_CRC16,
        1,
        2,
        1,
        0,
        (uint8*)&NvM_ConfigureId,   
        NULL_PTR, 
        NULL_PTR
    },
    {
        0, 
        NVM_BLOCK_REDUNDANT,    
        #if ((NVM_API_CONFIG_CLASS_1!=NVM_API_CONFIG_CLASS)&&(STD_ON==NVM_JOB_PRIORITIZATION))
        0,
        #endif
        NVM_SELCT_BLOCK_4READALL|NVM_SELCT_BLOCK_4WRITEALL|NVM_CALC_RAM_BLOCK_CRC|NVM_BLOCK_USE_CRC|0,
        NVM_CRC16,
        2,
        2,
        2,
        0,
        (uint8*)&TestID,   
        NULL_PTR, 
        NULL_PTR
    },
    {
        0, 
        NVM_BLOCK_NATIVE,    
        #if ((NVM_API_CONFIG_CLASS_1!=NVM_API_CONFIG_CLASS)&&(STD_ON==NVM_JOB_PRIORITIZATION))
        0,
        #endif
        NVM_SELCT_BLOCK_4READALL|NVM_CALC_RAM_BLOCK_CRC|NVM_BLOCK_USE_CRC|0,
        NVM_CRC16,
        4,
        4,
        1,
        0,
        (uint8*)&(g_odo_Odo),   
        NULL_PTR, 
        NULL_PTR
    },
    {
        0, 
        NVM_BLOCK_NATIVE,    
        #if ((NVM_API_CONFIG_CLASS_1!=NVM_API_CONFIG_CLASS)&&(STD_ON==NVM_JOB_PRIORITIZATION))
        0,
        #endif
        NVM_SELCT_BLOCK_4READALL|NVM_CALC_RAM_BLOCK_CRC|NVM_BLOCK_USE_CRC|0,
        NVM_CRC16,
        5,
        4,
        1,
        0,
        (uint8*)&(g_odo_back),   
        NULL_PTR, 
        NULL_PTR
    },
    {
        0, 
        NVM_BLOCK_NATIVE,    
        #if ((NVM_API_CONFIG_CLASS_1!=NVM_API_CONFIG_CLASS)&&(STD_ON==NVM_JOB_PRIORITIZATION))
        0,
        #endif
        NVM_SELCT_BLOCK_4READALL|NVM_CALC_RAM_BLOCK_CRC|NVM_BLOCK_USE_CRC|0,
        NVM_CRC16,
        6,
        4,
        1,
        0,
        (uint8*)&g_odo_para,   
        NULL_PTR, 
        NULL_PTR
    },
    {
        0, 
        NVM_BLOCK_NATIVE,    
        #if ((NVM_API_CONFIG_CLASS_1!=NVM_API_CONFIG_CLASS)&&(STD_ON==NVM_JOB_PRIORITIZATION))
        0,
        #endif
        NVM_SELCT_BLOCK_4READALL|NVM_CALC_RAM_BLOCK_CRC|NVM_BLOCK_USE_CRC|0,
        NVM_CRC16,
        7,
        10,
        1,
        0,
        (uint8*)&g_VEL_Coding,   
        NULL_PTR, 
        NULL_PTR
    },
    {
        0, 
        NVM_BLOCK_NATIVE,    
        #if ((NVM_API_CONFIG_CLASS_1!=NVM_API_CONFIG_CLASS)&&(STD_ON==NVM_JOB_PRIORITIZATION))
        0,
        #endif
        NVM_SELCT_BLOCK_4READALL|NVM_CALC_RAM_BLOCK_CRC|NVM_BLOCK_USE_CRC|0,
        NVM_CRC16,
        8,
        4,
        1,
        0,
        (uint8*)&g_VEL_LT_Config,   
        NULL_PTR, 
        NULL_PTR
    },
    {
        0, 
        NVM_BLOCK_NATIVE,    
        #if ((NVM_API_CONFIG_CLASS_1!=NVM_API_CONFIG_CLASS)&&(STD_ON==NVM_JOB_PRIORITIZATION))
        0,
        #endif
        NVM_SELCT_BLOCK_4READALL|NVM_CALC_RAM_BLOCK_CRC|NVM_BLOCK_USE_CRC|0,
        NVM_CRC16,
        9,
        8,
        1,
        0,
        (uint8*)&g_SERV_Coding,   
        NULL_PTR, 
        NULL_PTR
    },
    {
        0, 
        NVM_BLOCK_NATIVE,    
        #if ((NVM_API_CONFIG_CLASS_1!=NVM_API_CONFIG_CLASS)&&(STD_ON==NVM_JOB_PRIORITIZATION))
        0,
        #endif
        NVM_SELCT_BLOCK_4READALL|NVM_CALC_RAM_BLOCK_CRC|NVM_BLOCK_USE_CRC|0,
        NVM_CRC16,
        10,
        2,
        1,
        0,
        (uint8*)&g_Unit_Coding,   
        NULL_PTR, 
        NULL_PTR
    },
    {
        0, 
        NVM_BLOCK_NATIVE,    
        #if ((NVM_API_CONFIG_CLASS_1!=NVM_API_CONFIG_CLASS)&&(STD_ON==NVM_JOB_PRIORITIZATION))
        0,
        #endif
        NVM_SELCT_BLOCK_4READALL|NVM_SELCT_BLOCK_4WRITEALL|NVM_CALC_RAM_BLOCK_CRC|NVM_BLOCK_USE_CRC|0,
        NVM_CRC16,
        11,
        30,
        1,
        0,
        (uint8*)&g_sys_setting,   
        NULL_PTR, 
        NULL_PTR
    },
    {
        0, 
        NVM_BLOCK_NATIVE,    
        #if ((NVM_API_CONFIG_CLASS_1!=NVM_API_CONFIG_CLASS)&&(STD_ON==NVM_JOB_PRIORITIZATION))
        0,
        #endif
        NVM_SELCT_BLOCK_4READALL|NVM_SELCT_BLOCK_4WRITEALL|NVM_CALC_RAM_BLOCK_CRC|NVM_BLOCK_USE_CRC|0,
        NVM_CRC16,
        12,
        1,
        1,
        0,
        (uint8*)&gEnableTpTraceByCanFlag,   
        NULL_PTR, 
        NULL_PTR
    },
    {
        0, 
        NVM_BLOCK_NATIVE,    
        #if ((NVM_API_CONFIG_CLASS_1!=NVM_API_CONFIG_CLASS)&&(STD_ON==NVM_JOB_PRIORITIZATION))
        0,
        #endif
        NVM_SELCT_BLOCK_4READALL|NVM_SELCT_BLOCK_4WRITEALL|NVM_CALC_RAM_BLOCK_CRC|NVM_BLOCK_USE_CRC|0,
        NVM_CRC16,
        13,
        20,
        1,
        0,
        (uint8*)&socSerialNum[0],   
        NULL_PTR, 
        NULL_PTR
    },
    {
        0, 
        NVM_BLOCK_NATIVE,    
        #if ((NVM_API_CONFIG_CLASS_1!=NVM_API_CONFIG_CLASS)&&(STD_ON==NVM_JOB_PRIORITIZATION))
        0,
        #endif
        NVM_SELCT_BLOCK_4READALL|NVM_SELCT_BLOCK_4WRITEALL|NVM_CALC_RAM_BLOCK_CRC|NVM_BLOCK_USE_CRC|0,
        NVM_CRC16,
        14,
        17,
        1,
        0,
        (uint8*)&g_IVI_VIN[0],   
        NULL_PTR, 
        NULL_PTR
    },
    {
        0, 
        NVM_BLOCK_NATIVE,    
        #if ((NVM_API_CONFIG_CLASS_1!=NVM_API_CONFIG_CLASS)&&(STD_ON==NVM_JOB_PRIORITIZATION))
        0,
        #endif
        NVM_SELCT_BLOCK_4READALL|NVM_SELCT_BLOCK_4WRITEALL|NVM_CALC_RAM_BLOCK_CRC|NVM_BLOCK_USE_CRC|0,
        NVM_CRC16,
        15,
        1,
        1,
        0,
        (uint8*)&gIVI_PKI_CERTIFICATE[0],   
        NULL_PTR, 
        NULL_PTR
    },
    {
        0, 
        NVM_BLOCK_NATIVE,    
        #if ((NVM_API_CONFIG_CLASS_1!=NVM_API_CONFIG_CLASS)&&(STD_ON==NVM_JOB_PRIORITIZATION))
        0,
        #endif
        NVM_SELCT_BLOCK_4READALL|NVM_CALC_RAM_BLOCK_CRC|NVM_BLOCK_USE_CRC|0,
        NVM_CRC16,
        16,
        4,
        1,
        0,
        (uint8*)&(g_odo_back1),   
        NULL_PTR, 
        NULL_PTR
    },
    {
        0, 
        NVM_BLOCK_NATIVE,    
        #if ((NVM_API_CONFIG_CLASS_1!=NVM_API_CONFIG_CLASS)&&(STD_ON==NVM_JOB_PRIORITIZATION))
        0,
        #endif
        NVM_SELCT_BLOCK_4READALL|NVM_SELCT_BLOCK_4WRITEALL|NVM_CALC_RAM_BLOCK_CRC|NVM_BLOCK_USE_CRC|0,
        NVM_CRC16,
        17,
        30,
        1,
        0,
        (uint8*)&gIVICanFaultBitFlagArray[0],   
        NULL_PTR, 
        NULL_PTR
    },
    {
        0, 
        NVM_BLOCK_NATIVE,    
        #if ((NVM_API_CONFIG_CLASS_1!=NVM_API_CONFIG_CLASS)&&(STD_ON==NVM_JOB_PRIORITIZATION))
        0,
        #endif
        NVM_SELCT_BLOCK_4READALL|NVM_SELCT_BLOCK_4WRITEALL|NVM_CALC_RAM_BLOCK_CRC|NVM_BLOCK_USE_CRC|0,
        NVM_CRC16,
        18,
        32,
        1,
        0,
        (uint8*)&gIcCanFaultBitFlagArray[0],   
        NULL_PTR, 
        NULL_PTR
    },
    {
        0, 
        NVM_BLOCK_NATIVE,    
        #if ((NVM_API_CONFIG_CLASS_1!=NVM_API_CONFIG_CLASS)&&(STD_ON==NVM_JOB_PRIORITIZATION))
        0,
        #endif
        NVM_SELCT_BLOCK_4READALL|NVM_SELCT_BLOCK_4WRITEALL|NVM_CALC_RAM_BLOCK_CRC|NVM_BLOCK_USE_CRC|0,
        NVM_CRC16,
        19,
        4,
        1,
        0,
        (uint8*)&gRuntimeSnapshot_IVI[0],   
        NULL_PTR
    },
    {
        0, 
        NVM_BLOCK_NATIVE,    
        #if ((NVM_API_CONFIG_CLASS_1!=NVM_API_CONFIG_CLASS)&&(STD_ON==NVM_JOB_PRIORITIZATION))
        0,
        #endif
        NVM_SELCT_BLOCK_4READALL|NVM_SELCT_BLOCK_4WRITEALL|NVM_CALC_RAM_BLOCK_CRC|NVM_BLOCK_USE_CRC|0,
        NVM_CRC16,
        20,
        4,
        1,
        0,
        (uint8*)&gRuntimeSnapshot_IVI[1],   
        NULL_PTR, 
        NULL_PTR
    },
    {
        0, 
        NVM_BLOCK_NATIVE,    
        #if ((NVM_API_CONFIG_CLASS_1!=NVM_API_CONFIG_CLASS)&&(STD_ON==NVM_JOB_PRIORITIZATION))
        0,
        #endif
        NVM_SELCT_BLOCK_4READALL|NVM_SELCT_BLOCK_4WRITEALL|NVM_CALC_RAM_BLOCK_CRC|NVM_BLOCK_USE_CRC|0,
        NVM_CRC16,
        21,
        4,
        1,
        0,
        (uint8*)&gRuntimeSnapshot_IVI[2],   
        NULL_PTR, 
        NULL_PTR
    },
    {
        0, 
        NVM_BLOCK_NATIVE,    
        #if ((NVM_API_CONFIG_CLASS_1!=NVM_API_CONFIG_CLASS)&&(STD_ON==NVM_JOB_PRIORITIZATION))
        0,
        #endif
        NVM_SELCT_BLOCK_4READALL|NVM_SELCT_BLOCK_4WRITEALL|NVM_CALC_RAM_BLOCK_CRC|NVM_BLOCK_USE_CRC|0,
        NVM_CRC16,
        22,
        4,
        1,
        0,
        (uint8*)&gRuntimeSnapshot_IVI[3],   
        NULL_PTR, 
        NULL_PTR
    },
    {
        0, 
        NVM_BLOCK_NATIVE,    
        #if ((NVM_API_CONFIG_CLASS_1!=NVM_API_CONFIG_CLASS)&&(STD_ON==NVM_JOB_PRIORITIZATION))
        0,
        #endif
        NVM_SELCT_BLOCK_4READALL|NVM_SELCT_BLOCK_4WRITEALL|NVM_CALC_RAM_BLOCK_CRC|NVM_BLOCK_USE_CRC|0,
        NVM_CRC16,
        23,
        4,
        1,
        0,
        (uint8*)&gRuntimeSnapshot_IVI[4],   
        NULL_PTR, 
        NULL_PTR
    },
    {
        0, 
        NVM_BLOCK_NATIVE,    
        #if ((NVM_API_CONFIG_CLASS_1!=NVM_API_CONFIG_CLASS)&&(STD_ON==NVM_JOB_PRIORITIZATION))
        0,
        #endif
        NVM_SELCT_BLOCK_4READALL|NVM_SELCT_BLOCK_4WRITEALL|NVM_CALC_RAM_BLOCK_CRC|NVM_BLOCK_USE_CRC|0,
        NVM_CRC16,
        24,
        4,
        1,
        0,
        (uint8*)&gRuntimeSnapshot_IVI[5],   
        NULL_PTR, 
        NULL_PTR
    },
    {
        0, 
        NVM_BLOCK_NATIVE,    
        #if ((NVM_API_CONFIG_CLASS_1!=NVM_API_CONFIG_CLASS)&&(STD_ON==NVM_JOB_PRIORITIZATION))
        0,
        #endif
        NVM_SELCT_BLOCK_4READALL|NVM_SELCT_BLOCK_4WRITEALL|NVM_CALC_RAM_BLOCK_CRC|NVM_BLOCK_USE_CRC|0,
        NVM_CRC16,
        25,
        4,
        1,
        0,
        (uint8*)&gRuntimeSnapshot_IVI[6],   
        NULL_PTR, 
        NULL_PTR
    },
    {
        0, 
        NVM_BLOCK_NATIVE,    
        #if ((NVM_API_CONFIG_CLASS_1!=NVM_API_CONFIG_CLASS)&&(STD_ON==NVM_JOB_PRIORITIZATION))
        0,
        #endif
        NVM_SELCT_BLOCK_4READALL|NVM_SELCT_BLOCK_4WRITEALL|NVM_CALC_RAM_BLOCK_CRC|NVM_BLOCK_USE_CRC|0,
        NVM_CRC16,
        26,
        4,
        1,
        0,
        (uint8*)&gRuntimeSnapshot_IVI[7],   
        NULL_PTR, 
        NULL_PTR
    },
    {
        0, 
        NVM_BLOCK_NATIVE,    
        #if ((NVM_API_CONFIG_CLASS_1!=NVM_API_CONFIG_CLASS)&&(STD_ON==NVM_JOB_PRIORITIZATION))
        0,
        #endif
        NVM_SELCT_BLOCK_4READALL|NVM_SELCT_BLOCK_4WRITEALL|NVM_CALC_RAM_BLOCK_CRC|NVM_BLOCK_USE_CRC|0,
        NVM_CRC16,
        27,
        4,
        1,
        0,
        (uint8*)&gRuntimeSnapshot_IVI[8],   
        NULL_PTR, 
        NULL_PTR
    },
    {
        0, 
        NVM_BLOCK_NATIVE,    
        #if ((NVM_API_CONFIG_CLASS_1!=NVM_API_CONFIG_CLASS)&&(STD_ON==NVM_JOB_PRIORITIZATION))
        0,
        #endif
        NVM_SELCT_BLOCK_4READALL|NVM_SELCT_BLOCK_4WRITEALL|NVM_CALC_RAM_BLOCK_CRC|NVM_BLOCK_USE_CRC|0,
        NVM_CRC16,
        28,
        4,
        1,
        0,
        (uint8*)&gRuntimeSnapshot_IVI[9],   
        NULL_PTR, 
        NULL_PTR
    },
    {
        0, 
        NVM_BLOCK_NATIVE,    
        #if ((NVM_API_CONFIG_CLASS_1!=NVM_API_CONFIG_CLASS)&&(STD_ON==NVM_JOB_PRIORITIZATION))
        0,
        #endif
        NVM_SELCT_BLOCK_4READALL|NVM_SELCT_BLOCK_4WRITEALL|NVM_CALC_RAM_BLOCK_CRC|NVM_BLOCK_USE_CRC|0,
        NVM_CRC16,
        29,
        4,
        1,
        0,
        (uint8*)&gRuntimeSnapshot_IVI[10],   
        NULL_PTR, 
        NULL_PTR
    },
    {
        0, 
        NVM_BLOCK_NATIVE,    
        #if ((NVM_API_CONFIG_CLASS_1!=NVM_API_CONFIG_CLASS)&&(STD_ON==NVM_JOB_PRIORITIZATION))
        0,
        #endif
        NVM_SELCT_BLOCK_4READALL|NVM_SELCT_BLOCK_4WRITEALL|NVM_CALC_RAM_BLOCK_CRC|NVM_BLOCK_USE_CRC|0,
        NVM_CRC16,
        30,
        4,
        1,
        0,
        (uint8*)&gRuntimeSnapshot_IVI[11],   
        NULL_PTR, 
        NULL_PTR
    },
    {
        0, 
        NVM_BLOCK_NATIVE,    
        #if ((NVM_API_CONFIG_CLASS_1!=NVM_API_CONFIG_CLASS)&&(STD_ON==NVM_JOB_PRIORITIZATION))
        0,
        #endif
        NVM_SELCT_BLOCK_4READALL|NVM_SELCT_BLOCK_4WRITEALL|NVM_CALC_RAM_BLOCK_CRC|NVM_BLOCK_USE_CRC|0,
        NVM_CRC16,
        31,
        4,
        1,
        0,
        (uint8*)&gRuntimeSnapshot_IVI[12],   
        NULL_PTR, 
        NULL_PTR
    },
    {
        0, 
        NVM_BLOCK_NATIVE,    
        #if ((NVM_API_CONFIG_CLASS_1!=NVM_API_CONFIG_CLASS)&&(STD_ON==NVM_JOB_PRIORITIZATION))
        0,
        #endif
        NVM_SELCT_BLOCK_4READALL|NVM_SELCT_BLOCK_4WRITEALL|NVM_CALC_RAM_BLOCK_CRC|NVM_BLOCK_USE_CRC|0,
        NVM_CRC16,
        32,
        4,
        1,
        0,
        (uint8*)&gRuntimeSnapshot_IVI[13],   
        NULL_PTR, 
        NULL_PTR
    },
    {
        0, 
        NVM_BLOCK_NATIVE,    
        #if ((NVM_API_CONFIG_CLASS_1!=NVM_API_CONFIG_CLASS)&&(STD_ON==NVM_JOB_PRIORITIZATION))
        0,
        #endif
        NVM_SELCT_BLOCK_4READALL|NVM_SELCT_BLOCK_4WRITEALL|NVM_CALC_RAM_BLOCK_CRC|NVM_BLOCK_USE_CRC|0,
        NVM_CRC16,
        33,
        4,
        1,
        0,
        (uint8*)&gRuntimeSnapshot_IVI[14],   
        NULL_PTR, 
        NULL_PTR
    },
    {
        0, 
        NVM_BLOCK_NATIVE,    
        #if ((NVM_API_CONFIG_CLASS_1!=NVM_API_CONFIG_CLASS)&&(STD_ON==NVM_JOB_PRIORITIZATION))
        0,
        #endif
        NVM_SELCT_BLOCK_4READALL|NVM_SELCT_BLOCK_4WRITEALL|NVM_CALC_RAM_BLOCK_CRC|NVM_BLOCK_USE_CRC|0,
        NVM_CRC16,
        34,
        4,
        1,
        0,
        (uint8*)&gRuntimeSnapshot_IVI[15],   
        NULL_PTR, 
        NULL_PTR
    },
    {
        0, 
        NVM_BLOCK_NATIVE,    
        #if ((NVM_API_CONFIG_CLASS_1!=NVM_API_CONFIG_CLASS)&&(STD_ON==NVM_JOB_PRIORITIZATION))
        0,
        #endif
        NVM_SELCT_BLOCK_4READALL|NVM_SELCT_BLOCK_4WRITEALL|NVM_CALC_RAM_BLOCK_CRC|NVM_BLOCK_USE_CRC|0,
        NVM_CRC16,
        35,
        6,
        1,
        0,
        (uint8*)&gDtcStatusAndExtInfor_IVI[0],   
        NULL_PTR
    },
    {
        0, 
        NVM_BLOCK_NATIVE,    
        #if ((NVM_API_CONFIG_CLASS_1!=NVM_API_CONFIG_CLASS)&&(STD_ON==NVM_JOB_PRIORITIZATION))
        0,
        #endif
        NVM_SELCT_BLOCK_4READALL|NVM_SELCT_BLOCK_4WRITEALL|NVM_CALC_RAM_BLOCK_CRC|NVM_BLOCK_USE_CRC|0,
        NVM_CRC16,
        36,
        6,
        1,
        0,
        (uint8*)&gDtcStatusAndExtInfor_IVI[1],   
        NULL_PTR, 
        NULL_PTR
    },
    {
        0, 
        NVM_BLOCK_NATIVE,    
        #if ((NVM_API_CONFIG_CLASS_1!=NVM_API_CONFIG_CLASS)&&(STD_ON==NVM_JOB_PRIORITIZATION))
        0,
        #endif
        NVM_SELCT_BLOCK_4READALL|NVM_SELCT_BLOCK_4WRITEALL|NVM_CALC_RAM_BLOCK_CRC|NVM_BLOCK_USE_CRC|0,
        NVM_CRC16,
        37,
        6,
        1,
        0,
        (uint8*)&gDtcStatusAndExtInfor_IVI[2],   
        NULL_PTR, 
        NULL_PTR
    },
    {
        0, 
        NVM_BLOCK_NATIVE,    
        #if ((NVM_API_CONFIG_CLASS_1!=NVM_API_CONFIG_CLASS)&&(STD_ON==NVM_JOB_PRIORITIZATION))
        0,
        #endif
        NVM_SELCT_BLOCK_4READALL|NVM_SELCT_BLOCK_4WRITEALL|NVM_CALC_RAM_BLOCK_CRC|NVM_BLOCK_USE_CRC|0,
        NVM_CRC16,
        38,
        6,
        1,
        0,
        (uint8*)&gDtcStatusAndExtInfor_IVI[3],   
        NULL_PTR, 
        NULL_PTR
    },
    {
        0, 
        NVM_BLOCK_NATIVE,    
        #if ((NVM_API_CONFIG_CLASS_1!=NVM_API_CONFIG_CLASS)&&(STD_ON==NVM_JOB_PRIORITIZATION))
        0,
        #endif
        NVM_SELCT_BLOCK_4READALL|NVM_SELCT_BLOCK_4WRITEALL|NVM_CALC_RAM_BLOCK_CRC|NVM_BLOCK_USE_CRC|0,
        NVM_CRC16,
        39,
        6,
        1,
        0,
        (uint8*)&gDtcStatusAndExtInfor_IVI[4],   
        NULL_PTR, 
        NULL_PTR
    },
    {
        0, 
        NVM_BLOCK_NATIVE,    
        #if ((NVM_API_CONFIG_CLASS_1!=NVM_API_CONFIG_CLASS)&&(STD_ON==NVM_JOB_PRIORITIZATION))
        0,
        #endif
        NVM_SELCT_BLOCK_4READALL|NVM_SELCT_BLOCK_4WRITEALL|NVM_CALC_RAM_BLOCK_CRC|NVM_BLOCK_USE_CRC|0,
        NVM_CRC16,
        40,
        6,
        1,
        0,
        (uint8*)&gDtcStatusAndExtInfor_IVI[5],   
        NULL_PTR, 
        NULL_PTR
    },
    {
        0, 
        NVM_BLOCK_NATIVE,    
        #if ((NVM_API_CONFIG_CLASS_1!=NVM_API_CONFIG_CLASS)&&(STD_ON==NVM_JOB_PRIORITIZATION))
        0,
        #endif
        NVM_SELCT_BLOCK_4READALL|NVM_SELCT_BLOCK_4WRITEALL|NVM_CALC_RAM_BLOCK_CRC|NVM_BLOCK_USE_CRC|0,
        NVM_CRC16,
        41,
        6,
        1,
        0,
        (uint8*)&gDtcStatusAndExtInfor_IVI[6],   
        NULL_PTR, 
        NULL_PTR
    },
    {
        0, 
        NVM_BLOCK_NATIVE,    
        #if ((NVM_API_CONFIG_CLASS_1!=NVM_API_CONFIG_CLASS)&&(STD_ON==NVM_JOB_PRIORITIZATION))
        0,
        #endif
        NVM_SELCT_BLOCK_4READALL|NVM_SELCT_BLOCK_4WRITEALL|NVM_CALC_RAM_BLOCK_CRC|NVM_BLOCK_USE_CRC|0,
        NVM_CRC16,
        42,
        6,
        1,
        0,
        (uint8*)&gDtcStatusAndExtInfor_IVI[7],   
        NULL_PTR, 
        NULL_PTR
    },
    {
        0, 
        NVM_BLOCK_NATIVE,    
        #if ((NVM_API_CONFIG_CLASS_1!=NVM_API_CONFIG_CLASS)&&(STD_ON==NVM_JOB_PRIORITIZATION))
        0,
        #endif
        NVM_SELCT_BLOCK_4READALL|NVM_SELCT_BLOCK_4WRITEALL|NVM_CALC_RAM_BLOCK_CRC|NVM_BLOCK_USE_CRC|0,
        NVM_CRC16,
        43,
        6,
        1,
        0,
        (uint8*)&gDtcStatusAndExtInfor_IVI[8],   
        NULL_PTR, 
        NULL_PTR
    },
    {
        0, 
        NVM_BLOCK_NATIVE,    
        #if ((NVM_API_CONFIG_CLASS_1!=NVM_API_CONFIG_CLASS)&&(STD_ON==NVM_JOB_PRIORITIZATION))
        0,
        #endif
        NVM_SELCT_BLOCK_4READALL|NVM_SELCT_BLOCK_4WRITEALL|NVM_CALC_RAM_BLOCK_CRC|NVM_BLOCK_USE_CRC|0,
        NVM_CRC16,
        44,
        6,
        1,
        0,
        (uint8*)&gDtcStatusAndExtInfor_IVI[9],   
        NULL_PTR, 
        NULL_PTR
    },
    {
        0, 
        NVM_BLOCK_NATIVE,    
        #if ((NVM_API_CONFIG_CLASS_1!=NVM_API_CONFIG_CLASS)&&(STD_ON==NVM_JOB_PRIORITIZATION))
        0,
        #endif
        NVM_SELCT_BLOCK_4READALL|NVM_SELCT_BLOCK_4WRITEALL|NVM_CALC_RAM_BLOCK_CRC|NVM_BLOCK_USE_CRC|0,
        NVM_CRC16,
        45,
        6,
        1,
        0,
        (uint8*)&gDtcStatusAndExtInfor_IVI[10],   
        NULL_PTR, 
        NULL_PTR
    },
    {
        0, 
        NVM_BLOCK_NATIVE,    
        #if ((NVM_API_CONFIG_CLASS_1!=NVM_API_CONFIG_CLASS)&&(STD_ON==NVM_JOB_PRIORITIZATION))
        0,
        #endif
        NVM_SELCT_BLOCK_4READALL|NVM_SELCT_BLOCK_4WRITEALL|NVM_CALC_RAM_BLOCK_CRC|NVM_BLOCK_USE_CRC|0,
        NVM_CRC16,
        46,
        6,
        1,
        0,
        (uint8*)&gDtcStatusAndExtInfor_IVI[11],   
        NULL_PTR, 
        NULL_PTR
    },
    {
        0, 
        NVM_BLOCK_NATIVE,    
        #if ((NVM_API_CONFIG_CLASS_1!=NVM_API_CONFIG_CLASS)&&(STD_ON==NVM_JOB_PRIORITIZATION))
        0,
        #endif
        NVM_SELCT_BLOCK_4READALL|NVM_SELCT_BLOCK_4WRITEALL|NVM_CALC_RAM_BLOCK_CRC|NVM_BLOCK_USE_CRC|0,
        NVM_CRC16,
        47,
        6,
        1,
        0,
        (uint8*)&gDtcStatusAndExtInfor_IVI[12],   
        NULL_PTR, 
        NULL_PTR
    },
    {
        0, 
        NVM_BLOCK_NATIVE,    
        #if ((NVM_API_CONFIG_CLASS_1!=NVM_API_CONFIG_CLASS)&&(STD_ON==NVM_JOB_PRIORITIZATION))
        0,
        #endif
        NVM_SELCT_BLOCK_4READALL|NVM_SELCT_BLOCK_4WRITEALL|NVM_CALC_RAM_BLOCK_CRC|NVM_BLOCK_USE_CRC|0,
        NVM_CRC16,
        48,
        6,
        1,
        0,
        (uint8*)&gDtcStatusAndExtInfor_IVI[13],   
        NULL_PTR, 
        NULL_PTR
    },
    {
        0, 
        NVM_BLOCK_NATIVE,    
        #if ((NVM_API_CONFIG_CLASS_1!=NVM_API_CONFIG_CLASS)&&(STD_ON==NVM_JOB_PRIORITIZATION))
        0,
        #endif
        NVM_SELCT_BLOCK_4READALL|NVM_SELCT_BLOCK_4WRITEALL|NVM_CALC_RAM_BLOCK_CRC|NVM_BLOCK_USE_CRC|0,
        NVM_CRC16,
        49,
        6,
        1,
        0,
        (uint8*)&gDtcStatusAndExtInfor_IVI[14],   
        NULL_PTR, 
        NULL_PTR
    },
    {
        0, 
        NVM_BLOCK_NATIVE,    
        #if ((NVM_API_CONFIG_CLASS_1!=NVM_API_CONFIG_CLASS)&&(STD_ON==NVM_JOB_PRIORITIZATION))
        0,
        #endif
        NVM_SELCT_BLOCK_4READALL|NVM_SELCT_BLOCK_4WRITEALL|NVM_CALC_RAM_BLOCK_CRC|NVM_BLOCK_USE_CRC|0,
        NVM_CRC16,
        50,
        6,
        1,
        0,
        (uint8*)&gDtcStatusAndExtInfor_IVI[15],   
        NULL_PTR, 
        NULL_PTR
    },
    {
        0, 
        NVM_BLOCK_NATIVE,    
        #if ((NVM_API_CONFIG_CLASS_1!=NVM_API_CONFIG_CLASS)&&(STD_ON==NVM_JOB_PRIORITIZATION))
        0,
        #endif
        NVM_SELCT_BLOCK_4READALL|NVM_SELCT_BLOCK_4WRITEALL|NVM_CALC_RAM_BLOCK_CRC|NVM_BLOCK_USE_CRC|0,
        NVM_CRC16,
        51,
        7,
        1,
        0,
        (uint8*)&gRuntimeSnapshot_IC[0],   
        NULL_PTR
    },
    {
        0, 
        NVM_BLOCK_NATIVE,    
        #if ((NVM_API_CONFIG_CLASS_1!=NVM_API_CONFIG_CLASS)&&(STD_ON==NVM_JOB_PRIORITIZATION))
        0,
        #endif
        NVM_SELCT_BLOCK_4READALL|NVM_SELCT_BLOCK_4WRITEALL|NVM_CALC_RAM_BLOCK_CRC|NVM_BLOCK_USE_CRC|0,
        NVM_CRC16,
        52,
        7,
        1,
        0,
        (uint8*)&gRuntimeSnapshot_IC[1],   
        NULL_PTR, 
        NULL_PTR
    },
    {
        0, 
        NVM_BLOCK_NATIVE,    
        #if ((NVM_API_CONFIG_CLASS_1!=NVM_API_CONFIG_CLASS)&&(STD_ON==NVM_JOB_PRIORITIZATION))
        0,
        #endif
        NVM_SELCT_BLOCK_4READALL|NVM_SELCT_BLOCK_4WRITEALL|NVM_CALC_RAM_BLOCK_CRC|NVM_BLOCK_USE_CRC|0,
        NVM_CRC16,
        53,
        7,
        1,
        0,
        (uint8*)&gRuntimeSnapshot_IC[2],   
        NULL_PTR, 
        NULL_PTR
    },
    {
        0, 
        NVM_BLOCK_NATIVE,    
        #if ((NVM_API_CONFIG_CLASS_1!=NVM_API_CONFIG_CLASS)&&(STD_ON==NVM_JOB_PRIORITIZATION))
        0,
        #endif
        NVM_SELCT_BLOCK_4READALL|NVM_SELCT_BLOCK_4WRITEALL|NVM_CALC_RAM_BLOCK_CRC|NVM_BLOCK_USE_CRC|0,
        NVM_CRC16,
        54,
        7,
        1,
        0,
        (uint8*)&gRuntimeSnapshot_IC[3],   
        NULL_PTR, 
        NULL_PTR
    },
    {
        0, 
        NVM_BLOCK_NATIVE,    
        #if ((NVM_API_CONFIG_CLASS_1!=NVM_API_CONFIG_CLASS)&&(STD_ON==NVM_JOB_PRIORITIZATION))
        0,
        #endif
        NVM_SELCT_BLOCK_4READALL|NVM_SELCT_BLOCK_4WRITEALL|NVM_CALC_RAM_BLOCK_CRC|NVM_BLOCK_USE_CRC|0,
        NVM_CRC16,
        55,
        7,
        1,
        0,
        (uint8*)&gRuntimeSnapshot_IC[4],   
        NULL_PTR, 
        NULL_PTR
    },
    {
        0, 
        NVM_BLOCK_NATIVE,    
        #if ((NVM_API_CONFIG_CLASS_1!=NVM_API_CONFIG_CLASS)&&(STD_ON==NVM_JOB_PRIORITIZATION))
        0,
        #endif
        NVM_SELCT_BLOCK_4READALL|NVM_SELCT_BLOCK_4WRITEALL|NVM_CALC_RAM_BLOCK_CRC|NVM_BLOCK_USE_CRC|0,
        NVM_CRC16,
        56,
        7,
        1,
        0,
        (uint8*)&gRuntimeSnapshot_IC[5],   
        NULL_PTR, 
        NULL_PTR
    },
    {
        0, 
        NVM_BLOCK_NATIVE,    
        #if ((NVM_API_CONFIG_CLASS_1!=NVM_API_CONFIG_CLASS)&&(STD_ON==NVM_JOB_PRIORITIZATION))
        0,
        #endif
        NVM_SELCT_BLOCK_4READALL|NVM_SELCT_BLOCK_4WRITEALL|NVM_CALC_RAM_BLOCK_CRC|NVM_BLOCK_USE_CRC|0,
        NVM_CRC16,
        57,
        7,
        1,
        0,
        (uint8*)&gRuntimeSnapshot_IC[6],   
        NULL_PTR, 
        NULL_PTR
    },
    {
        0, 
        NVM_BLOCK_NATIVE,    
        #if ((NVM_API_CONFIG_CLASS_1!=NVM_API_CONFIG_CLASS)&&(STD_ON==NVM_JOB_PRIORITIZATION))
        0,
        #endif
        NVM_SELCT_BLOCK_4READALL|NVM_SELCT_BLOCK_4WRITEALL|NVM_CALC_RAM_BLOCK_CRC|NVM_BLOCK_USE_CRC|0,
        NVM_CRC16,
        58,
        7,
        1,
        0,
        (uint8*)&gRuntimeSnapshot_IC[7],   
        NULL_PTR, 
        NULL_PTR
    },
    {
        0, 
        NVM_BLOCK_NATIVE,    
        #if ((NVM_API_CONFIG_CLASS_1!=NVM_API_CONFIG_CLASS)&&(STD_ON==NVM_JOB_PRIORITIZATION))
        0,
        #endif
        NVM_SELCT_BLOCK_4READALL|NVM_SELCT_BLOCK_4WRITEALL|NVM_CALC_RAM_BLOCK_CRC|NVM_BLOCK_USE_CRC|0,
        NVM_CRC16,
        59,
        7,
        1,
        0,
        (uint8*)&gRuntimeSnapshot_IC[8],   
        NULL_PTR, 
        NULL_PTR
    },
    {
        0, 
        NVM_BLOCK_NATIVE,    
        #if ((NVM_API_CONFIG_CLASS_1!=NVM_API_CONFIG_CLASS)&&(STD_ON==NVM_JOB_PRIORITIZATION))
        0,
        #endif
        NVM_SELCT_BLOCK_4READALL|NVM_SELCT_BLOCK_4WRITEALL|NVM_CALC_RAM_BLOCK_CRC|NVM_BLOCK_USE_CRC|0,
        NVM_CRC16,
        60,
        7,
        1,
        0,
        (uint8*)&gRuntimeSnapshot_IC[9],   
        NULL_PTR, 
        NULL_PTR
    },
    {
        0, 
        NVM_BLOCK_NATIVE,    
        #if ((NVM_API_CONFIG_CLASS_1!=NVM_API_CONFIG_CLASS)&&(STD_ON==NVM_JOB_PRIORITIZATION))
        0,
        #endif
        NVM_SELCT_BLOCK_4READALL|NVM_SELCT_BLOCK_4WRITEALL|NVM_CALC_RAM_BLOCK_CRC|NVM_BLOCK_USE_CRC|0,
        NVM_CRC16,
        61,
        7,
        1,
        0,
        (uint8*)&gRuntimeSnapshot_IC[10],   
        NULL_PTR, 
        NULL_PTR
    },
    {
        0, 
        NVM_BLOCK_NATIVE,    
        #if ((NVM_API_CONFIG_CLASS_1!=NVM_API_CONFIG_CLASS)&&(STD_ON==NVM_JOB_PRIORITIZATION))
        0,
        #endif
        NVM_SELCT_BLOCK_4READALL|NVM_SELCT_BLOCK_4WRITEALL|NVM_CALC_RAM_BLOCK_CRC|NVM_BLOCK_USE_CRC|0,
        NVM_CRC16,
        62,
        7,
        1,
        0,
        (uint8*)&gRuntimeSnapshot_IC[11],   
        NULL_PTR, 
        NULL_PTR
    },
    {
        0, 
        NVM_BLOCK_NATIVE,    
        #if ((NVM_API_CONFIG_CLASS_1!=NVM_API_CONFIG_CLASS)&&(STD_ON==NVM_JOB_PRIORITIZATION))
        0,
        #endif
        NVM_SELCT_BLOCK_4READALL|NVM_SELCT_BLOCK_4WRITEALL|NVM_CALC_RAM_BLOCK_CRC|NVM_BLOCK_USE_CRC|0,
        NVM_CRC16,
        63,
        7,
        1,
        0,
        (uint8*)&gRuntimeSnapshot_IC[12],   
        NULL_PTR, 
        NULL_PTR
    },
    {
        0, 
        NVM_BLOCK_NATIVE,    
        #if ((NVM_API_CONFIG_CLASS_1!=NVM_API_CONFIG_CLASS)&&(STD_ON==NVM_JOB_PRIORITIZATION))
        0,
        #endif
        NVM_SELCT_BLOCK_4READALL|NVM_SELCT_BLOCK_4WRITEALL|NVM_CALC_RAM_BLOCK_CRC|NVM_BLOCK_USE_CRC|0,
        NVM_CRC16,
        64,
        7,
        1,
        0,
        (uint8*)&gRuntimeSnapshot_IC[13],   
        NULL_PTR, 
        NULL_PTR
    },
    {
        0, 
        NVM_BLOCK_NATIVE,    
        #if ((NVM_API_CONFIG_CLASS_1!=NVM_API_CONFIG_CLASS)&&(STD_ON==NVM_JOB_PRIORITIZATION))
        0,
        #endif
        0,
        NVM_CRC16,
        65,
        7,
        1,
        0,
        (uint8*)&gRuntimeSnapshot_IC[14],   
        NULL_PTR, 
        
    },
    {
        0, 
        NVM_BLOCK_NATIVE,    
        #if ((NVM_API_CONFIG_CLASS_1!=NVM_API_CONFIG_CLASS)&&(STD_ON==NVM_JOB_PRIORITIZATION))
        0,
        #endif
        NVM_SELCT_BLOCK_4READALL|NVM_SELCT_BLOCK_4WRITEALL|NVM_CALC_RAM_BLOCK_CRC|NVM_BLOCK_USE_CRC|0,
        NVM_CRC16,
        66,
        6,
        1,
        0,
        (uint8*)&gDtcStatusAndExtInfor_IC[0],   
        NULL_PTR
    },
    {
        0, 
        NVM_BLOCK_NATIVE,    
        #if ((NVM_API_CONFIG_CLASS_1!=NVM_API_CONFIG_CLASS)&&(STD_ON==NVM_JOB_PRIORITIZATION))
        0,
        #endif
        NVM_SELCT_BLOCK_4READALL|NVM_SELCT_BLOCK_4WRITEALL|NVM_CALC_RAM_BLOCK_CRC|NVM_BLOCK_USE_CRC|0,
        NVM_CRC16,
        67,
        6,
        1,
        0,
        (uint8*)&gDtcStatusAndExtInfor_IC[1],   
        NULL_PTR, 
        NULL_PTR
    },
    {
        0, 
        NVM_BLOCK_NATIVE,    
        #if ((NVM_API_CONFIG_CLASS_1!=NVM_API_CONFIG_CLASS)&&(STD_ON==NVM_JOB_PRIORITIZATION))
        0,
        #endif
        NVM_SELCT_BLOCK_4READALL|NVM_SELCT_BLOCK_4WRITEALL|NVM_CALC_RAM_BLOCK_CRC|NVM_BLOCK_USE_CRC|0,
        NVM_CRC16,
        68,
        6,
        1,
        0,
        (uint8*)&gDtcStatusAndExtInfor_IC[2],   
        NULL_PTR, 
        NULL_PTR
    },
    {
        0, 
        NVM_BLOCK_NATIVE,    
        #if ((NVM_API_CONFIG_CLASS_1!=NVM_API_CONFIG_CLASS)&&(STD_ON==NVM_JOB_PRIORITIZATION))
        0,
        #endif
        NVM_SELCT_BLOCK_4READALL|NVM_SELCT_BLOCK_4WRITEALL|NVM_CALC_RAM_BLOCK_CRC|NVM_BLOCK_USE_CRC|0,
        NVM_CRC16,
        69,
        6,
        1,
        0,
        (uint8*)&gDtcStatusAndExtInfor_IC[3],   
        NULL_PTR, 
        NULL_PTR
    },
    {
        0, 
        NVM_BLOCK_NATIVE,    
        #if ((NVM_API_CONFIG_CLASS_1!=NVM_API_CONFIG_CLASS)&&(STD_ON==NVM_JOB_PRIORITIZATION))
        0,
        #endif
        NVM_SELCT_BLOCK_4READALL|NVM_SELCT_BLOCK_4WRITEALL|NVM_CALC_RAM_BLOCK_CRC|NVM_BLOCK_USE_CRC|0,
        NVM_CRC16,
        70,
        6,
        1,
        0,
        (uint8*)&gDtcStatusAndExtInfor_IC[4],   
        NULL_PTR, 
        NULL_PTR
    },
    {
        0, 
        NVM_BLOCK_NATIVE,    
        #if ((NVM_API_CONFIG_CLASS_1!=NVM_API_CONFIG_CLASS)&&(STD_ON==NVM_JOB_PRIORITIZATION))
        0,
        #endif
        NVM_SELCT_BLOCK_4READALL|NVM_SELCT_BLOCK_4WRITEALL|NVM_CALC_RAM_BLOCK_CRC|NVM_BLOCK_USE_CRC|0,
        NVM_CRC16,
        71,
        6,
        1,
        0,
        (uint8*)&gDtcStatusAndExtInfor_IC[5],   
        NULL_PTR, 
        NULL_PTR
    },
    {
        0, 
        NVM_BLOCK_NATIVE,    
        #if ((NVM_API_CONFIG_CLASS_1!=NVM_API_CONFIG_CLASS)&&(STD_ON==NVM_JOB_PRIORITIZATION))
        0,
        #endif
        NVM_SELCT_BLOCK_4READALL|NVM_SELCT_BLOCK_4WRITEALL|NVM_CALC_RAM_BLOCK_CRC|NVM_BLOCK_USE_CRC|0,
        NVM_CRC16,
        72,
        6,
        1,
        0,
        (uint8*)&gDtcStatusAndExtInfor_IC[6],   
        NULL_PTR, 
        NULL_PTR
    },
    {
        0, 
        NVM_BLOCK_NATIVE,    
        #if ((NVM_API_CONFIG_CLASS_1!=NVM_API_CONFIG_CLASS)&&(STD_ON==NVM_JOB_PRIORITIZATION))
        0,
        #endif
        NVM_SELCT_BLOCK_4READALL|NVM_SELCT_BLOCK_4WRITEALL|NVM_CALC_RAM_BLOCK_CRC|NVM_BLOCK_USE_CRC|0,
        NVM_CRC16,
        73,
        6,
        1,
        0,
        (uint8*)&gDtcStatusAndExtInfor_IC[7],   
        NULL_PTR, 
        NULL_PTR
    },
    {
        0, 
        NVM_BLOCK_NATIVE,    
        #if ((NVM_API_CONFIG_CLASS_1!=NVM_API_CONFIG_CLASS)&&(STD_ON==NVM_JOB_PRIORITIZATION))
        0,
        #endif
        NVM_SELCT_BLOCK_4READALL|NVM_SELCT_BLOCK_4WRITEALL|NVM_CALC_RAM_BLOCK_CRC|NVM_BLOCK_USE_CRC|0,
        NVM_CRC16,
        74,
        6,
        1,
        0,
        (uint8*)&gDtcStatusAndExtInfor_IC[8],   
        NULL_PTR, 
        NULL_PTR
    },
    {
        0, 
        NVM_BLOCK_NATIVE,    
        #if ((NVM_API_CONFIG_CLASS_1!=NVM_API_CONFIG_CLASS)&&(STD_ON==NVM_JOB_PRIORITIZATION))
        0,
        #endif
        NVM_SELCT_BLOCK_4READALL|NVM_SELCT_BLOCK_4WRITEALL|NVM_CALC_RAM_BLOCK_CRC|NVM_BLOCK_USE_CRC|0,
        NVM_CRC16,
        75,
        6,
        1,
        0,
        (uint8*)&gDtcStatusAndExtInfor_IC[9],   
        NULL_PTR, 
        NULL_PTR
    },
    {
        0, 
        NVM_BLOCK_NATIVE,    
        #if ((NVM_API_CONFIG_CLASS_1!=NVM_API_CONFIG_CLASS)&&(STD_ON==NVM_JOB_PRIORITIZATION))
        0,
        #endif
        NVM_SELCT_BLOCK_4READALL|NVM_SELCT_BLOCK_4WRITEALL|NVM_CALC_RAM_BLOCK_CRC|NVM_BLOCK_USE_CRC|0,
        NVM_CRC16,
        76,
        6,
        1,
        0,
        (uint8*)&gDtcStatusAndExtInfor_IC[10],   
        NULL_PTR, 
        NULL_PTR
    },
    {
        0, 
        NVM_BLOCK_NATIVE,    
        #if ((NVM_API_CONFIG_CLASS_1!=NVM_API_CONFIG_CLASS)&&(STD_ON==NVM_JOB_PRIORITIZATION))
        0,
        #endif
        NVM_SELCT_BLOCK_4READALL|NVM_SELCT_BLOCK_4WRITEALL|NVM_CALC_RAM_BLOCK_CRC|NVM_BLOCK_USE_CRC|0,
        NVM_CRC16,
        77,
        6,
        1,
        0,
        (uint8*)&gDtcStatusAndExtInfor_IC[11],   
        NULL_PTR, 
        NULL_PTR
    },
    {
        0, 
        NVM_BLOCK_NATIVE,    
        #if ((NVM_API_CONFIG_CLASS_1!=NVM_API_CONFIG_CLASS)&&(STD_ON==NVM_JOB_PRIORITIZATION))
        0,
        #endif
        NVM_SELCT_BLOCK_4READALL|NVM_SELCT_BLOCK_4WRITEALL|NVM_CALC_RAM_BLOCK_CRC|NVM_BLOCK_USE_CRC|0,
        NVM_CRC16,
        78,
        6,
        1,
        0,
        (uint8*)&gDtcStatusAndExtInfor_IC[12],   
        NULL_PTR, 
        NULL_PTR
    },
    {
        0, 
        NVM_BLOCK_NATIVE,    
        #if ((NVM_API_CONFIG_CLASS_1!=NVM_API_CONFIG_CLASS)&&(STD_ON==NVM_JOB_PRIORITIZATION))
        0,
        #endif
        NVM_SELCT_BLOCK_4READALL|NVM_SELCT_BLOCK_4WRITEALL|NVM_CALC_RAM_BLOCK_CRC|NVM_BLOCK_USE_CRC|0,
        NVM_CRC16,
        79,
        6,
        1,
        0,
        (uint8*)&gDtcStatusAndExtInfor_IC[13],   
        NULL_PTR, 
        NULL_PTR
    },
    {
        0, 
        NVM_BLOCK_NATIVE,    
        #if ((NVM_API_CONFIG_CLASS_1!=NVM_API_CONFIG_CLASS)&&(STD_ON==NVM_JOB_PRIORITIZATION))
        0,
        #endif
        0,
        NVM_CRC16,
        80,
        6,
        1,
        0,
        (uint8*)&gDtcStatusAndExtInfor_IC[14],   
        NULL_PTR, 
        
    },
    {
        0, 
        NVM_BLOCK_NATIVE,    
        #if ((NVM_API_CONFIG_CLASS_1!=NVM_API_CONFIG_CLASS)&&(STD_ON==NVM_JOB_PRIORITIZATION))
        0,
        #endif
        NVM_SELCT_BLOCK_4READALL|NVM_SELCT_BLOCK_4WRITEALL|NVM_CALC_RAM_BLOCK_CRC|NVM_BLOCK_USE_CRC|0,
        NVM_CRC16,
        81,
        3,
        1,
        0,
        (uint8*)&gRuntimeSnapshot_AVM[0],   
        NULL_PTR
    },
    {
        0, 
        NVM_BLOCK_NATIVE,    
        #if ((NVM_API_CONFIG_CLASS_1!=NVM_API_CONFIG_CLASS)&&(STD_ON==NVM_JOB_PRIORITIZATION))
        0,
        #endif
        NVM_SELCT_BLOCK_4READALL|NVM_SELCT_BLOCK_4WRITEALL|NVM_CALC_RAM_BLOCK_CRC|NVM_BLOCK_USE_CRC|0,
        NVM_CRC16,
        82,
        3,
        1,
        0,
        (uint8*)&gRuntimeSnapshot_AVM[1],   
        NULL_PTR, 
        NULL_PTR
    },
    {
        0, 
        NVM_BLOCK_NATIVE,    
        #if ((NVM_API_CONFIG_CLASS_1!=NVM_API_CONFIG_CLASS)&&(STD_ON==NVM_JOB_PRIORITIZATION))
        0,
        #endif
        NVM_SELCT_BLOCK_4READALL|NVM_SELCT_BLOCK_4WRITEALL|NVM_CALC_RAM_BLOCK_CRC|NVM_BLOCK_USE_CRC|0,
        NVM_CRC16,
        83,
        3,
        1,
        0,
        (uint8*)&gRuntimeSnapshot_AVM[2],   
        NULL_PTR, 
        NULL_PTR
    },
    {
        0, 
        NVM_BLOCK_NATIVE,    
        #if ((NVM_API_CONFIG_CLASS_1!=NVM_API_CONFIG_CLASS)&&(STD_ON==NVM_JOB_PRIORITIZATION))
        0,
        #endif
        NVM_SELCT_BLOCK_4READALL|NVM_SELCT_BLOCK_4WRITEALL|NVM_CALC_RAM_BLOCK_CRC|NVM_BLOCK_USE_CRC|0,
        NVM_CRC16,
        84,
        3,
        1,
        0,
        (uint8*)&gRuntimeSnapshot_AVM[3],   
        NULL_PTR, 
        NULL_PTR
    },
    {
        0, 
        NVM_BLOCK_NATIVE,    
        #if ((NVM_API_CONFIG_CLASS_1!=NVM_API_CONFIG_CLASS)&&(STD_ON==NVM_JOB_PRIORITIZATION))
        0,
        #endif
        NVM_SELCT_BLOCK_4READALL|NVM_SELCT_BLOCK_4WRITEALL|NVM_CALC_RAM_BLOCK_CRC|NVM_BLOCK_USE_CRC|0,
        NVM_CRC16,
        85,
        3,
        1,
        0,
        (uint8*)&gRuntimeSnapshot_AVM[4],   
        NULL_PTR, 
        NULL_PTR
    },
    {
        0, 
        NVM_BLOCK_NATIVE,    
        #if ((NVM_API_CONFIG_CLASS_1!=NVM_API_CONFIG_CLASS)&&(STD_ON==NVM_JOB_PRIORITIZATION))
        0,
        #endif
        NVM_SELCT_BLOCK_4READALL|NVM_SELCT_BLOCK_4WRITEALL|NVM_CALC_RAM_BLOCK_CRC|NVM_BLOCK_USE_CRC|0,
        NVM_CRC16,
        86,
        3,
        1,
        0,
        (uint8*)&gRuntimeSnapshot_AVM[5],   
        NULL_PTR, 
        NULL_PTR
    },
    {
        0, 
        NVM_BLOCK_NATIVE,    
        #if ((NVM_API_CONFIG_CLASS_1!=NVM_API_CONFIG_CLASS)&&(STD_ON==NVM_JOB_PRIORITIZATION))
        0,
        #endif
        NVM_SELCT_BLOCK_4READALL|NVM_SELCT_BLOCK_4WRITEALL|NVM_CALC_RAM_BLOCK_CRC|NVM_BLOCK_USE_CRC|0,
        NVM_CRC16,
        87,
        3,
        1,
        0,
        (uint8*)&gRuntimeSnapshot_AVM[6],   
        NULL_PTR, 
        NULL_PTR
    },
    {
        0, 
        NVM_BLOCK_NATIVE,    
        #if ((NVM_API_CONFIG_CLASS_1!=NVM_API_CONFIG_CLASS)&&(STD_ON==NVM_JOB_PRIORITIZATION))
        0,
        #endif
        NVM_SELCT_BLOCK_4READALL|NVM_SELCT_BLOCK_4WRITEALL|NVM_CALC_RAM_BLOCK_CRC|NVM_BLOCK_USE_CRC|0,
        NVM_CRC16,
        88,
        3,
        1,
        0,
        (uint8*)&gRuntimeSnapshot_AVM[7],   
        NULL_PTR, 
        NULL_PTR
    },
    {
        0, 
        NVM_BLOCK_NATIVE,    
        #if ((NVM_API_CONFIG_CLASS_1!=NVM_API_CONFIG_CLASS)&&(STD_ON==NVM_JOB_PRIORITIZATION))
        0,
        #endif
        NVM_SELCT_BLOCK_4READALL|NVM_SELCT_BLOCK_4WRITEALL|NVM_CALC_RAM_BLOCK_CRC|NVM_BLOCK_USE_CRC|0,
        NVM_CRC16,
        89,
        3,
        1,
        0,
        (uint8*)&gRuntimeSnapshot_AVM[8],   
        NULL_PTR, 
        NULL_PTR
    },
    {
        0, 
        NVM_BLOCK_NATIVE,    
        #if ((NVM_API_CONFIG_CLASS_1!=NVM_API_CONFIG_CLASS)&&(STD_ON==NVM_JOB_PRIORITIZATION))
        0,
        #endif
        NVM_SELCT_BLOCK_4READALL|NVM_SELCT_BLOCK_4WRITEALL|NVM_CALC_RAM_BLOCK_CRC|NVM_BLOCK_USE_CRC|0,
        NVM_CRC16,
        90,
        3,
        1,
        0,
        (uint8*)&gRuntimeSnapshot_AVM[9],   
        NULL_PTR, 
        NULL_PTR
    },
    {
        0, 
        NVM_BLOCK_NATIVE,    
        #if ((NVM_API_CONFIG_CLASS_1!=NVM_API_CONFIG_CLASS)&&(STD_ON==NVM_JOB_PRIORITIZATION))
        0,
        #endif
        NVM_SELCT_BLOCK_4READALL|NVM_SELCT_BLOCK_4WRITEALL|NVM_CALC_RAM_BLOCK_CRC|NVM_BLOCK_USE_CRC|0,
        NVM_CRC16,
        91,
        6,
        1,
        0,
        (uint8*)&gDtcStatusAndExtInfor_AVM[0],   
        NULL_PTR
    },
    {
        0, 
        NVM_BLOCK_NATIVE,    
        #if ((NVM_API_CONFIG_CLASS_1!=NVM_API_CONFIG_CLASS)&&(STD_ON==NVM_JOB_PRIORITIZATION))
        0,
        #endif
        NVM_SELCT_BLOCK_4READALL|NVM_SELCT_BLOCK_4WRITEALL|NVM_CALC_RAM_BLOCK_CRC|NVM_BLOCK_USE_CRC|0,
        NVM_CRC16,
        92,
        6,
        1,
        0,
        (uint8*)&gDtcStatusAndExtInfor_AVM[1],   
        NULL_PTR, 
        NULL_PTR
    },
    {
        0, 
        NVM_BLOCK_NATIVE,    
        #if ((NVM_API_CONFIG_CLASS_1!=NVM_API_CONFIG_CLASS)&&(STD_ON==NVM_JOB_PRIORITIZATION))
        0,
        #endif
        NVM_SELCT_BLOCK_4READALL|NVM_SELCT_BLOCK_4WRITEALL|NVM_CALC_RAM_BLOCK_CRC|NVM_BLOCK_USE_CRC|0,
        NVM_CRC16,
        93,
        6,
        1,
        0,
        (uint8*)&gDtcStatusAndExtInfor_AVM[2],   
        NULL_PTR, 
        NULL_PTR
    },
    {
        0, 
        NVM_BLOCK_NATIVE,    
        #if ((NVM_API_CONFIG_CLASS_1!=NVM_API_CONFIG_CLASS)&&(STD_ON==NVM_JOB_PRIORITIZATION))
        0,
        #endif
        NVM_SELCT_BLOCK_4READALL|NVM_SELCT_BLOCK_4WRITEALL|NVM_CALC_RAM_BLOCK_CRC|NVM_BLOCK_USE_CRC|0,
        NVM_CRC16,
        94,
        6,
        1,
        0,
        (uint8*)&gDtcStatusAndExtInfor_AVM[3],   
        NULL_PTR, 
        NULL_PTR
    },
    {
        0, 
        NVM_BLOCK_NATIVE,    
        #if ((NVM_API_CONFIG_CLASS_1!=NVM_API_CONFIG_CLASS)&&(STD_ON==NVM_JOB_PRIORITIZATION))
        0,
        #endif
        NVM_SELCT_BLOCK_4READALL|NVM_SELCT_BLOCK_4WRITEALL|NVM_CALC_RAM_BLOCK_CRC|NVM_BLOCK_USE_CRC|0,
        NVM_CRC16,
        95,
        6,
        1,
        0,
        (uint8*)&gDtcStatusAndExtInfor_AVM[4],   
        NULL_PTR, 
        NULL_PTR
    },
    {
        0, 
        NVM_BLOCK_NATIVE,    
        #if ((NVM_API_CONFIG_CLASS_1!=NVM_API_CONFIG_CLASS)&&(STD_ON==NVM_JOB_PRIORITIZATION))
        0,
        #endif
        NVM_SELCT_BLOCK_4READALL|NVM_SELCT_BLOCK_4WRITEALL|NVM_CALC_RAM_BLOCK_CRC|NVM_BLOCK_USE_CRC|0,
        NVM_CRC16,
        96,
        6,
        1,
        0,
        (uint8*)&gDtcStatusAndExtInfor_AVM[5],   
        NULL_PTR, 
        NULL_PTR
    },
    {
        0, 
        NVM_BLOCK_NATIVE,    
        #if ((NVM_API_CONFIG_CLASS_1!=NVM_API_CONFIG_CLASS)&&(STD_ON==NVM_JOB_PRIORITIZATION))
        0,
        #endif
        NVM_SELCT_BLOCK_4READALL|NVM_SELCT_BLOCK_4WRITEALL|NVM_CALC_RAM_BLOCK_CRC|NVM_BLOCK_USE_CRC|0,
        NVM_CRC16,
        97,
        6,
        1,
        0,
        (uint8*)&gDtcStatusAndExtInfor_AVM[6],   
        NULL_PTR, 
        NULL_PTR
    },
    {
        0, 
        NVM_BLOCK_NATIVE,    
        #if ((NVM_API_CONFIG_CLASS_1!=NVM_API_CONFIG_CLASS)&&(STD_ON==NVM_JOB_PRIORITIZATION))
        0,
        #endif
        NVM_SELCT_BLOCK_4READALL|NVM_SELCT_BLOCK_4WRITEALL|NVM_CALC_RAM_BLOCK_CRC|NVM_BLOCK_USE_CRC|0,
        NVM_CRC16,
        98,
        6,
        1,
        0,
        (uint8*)&gDtcStatusAndExtInfor_AVM[7],   
        NULL_PTR, 
        NULL_PTR
    },
    {
        0, 
        NVM_BLOCK_NATIVE,    
        #if ((NVM_API_CONFIG_CLASS_1!=NVM_API_CONFIG_CLASS)&&(STD_ON==NVM_JOB_PRIORITIZATION))
        0,
        #endif
        NVM_SELCT_BLOCK_4READALL|NVM_SELCT_BLOCK_4WRITEALL|NVM_CALC_RAM_BLOCK_CRC|NVM_BLOCK_USE_CRC|0,
        NVM_CRC16,
        99,
        6,
        1,
        0,
        (uint8*)&gDtcStatusAndExtInfor_AVM[8],   
        NULL_PTR, 
        NULL_PTR
    },
    {
        0, 
        NVM_BLOCK_NATIVE,    
        #if ((NVM_API_CONFIG_CLASS_1!=NVM_API_CONFIG_CLASS)&&(STD_ON==NVM_JOB_PRIORITIZATION))
        0,
        #endif
        NVM_SELCT_BLOCK_4READALL|NVM_SELCT_BLOCK_4WRITEALL|NVM_CALC_RAM_BLOCK_CRC|NVM_BLOCK_USE_CRC|0,
        NVM_CRC16,
        100,
        6,
        1,
        0,
        (uint8*)&gDtcStatusAndExtInfor_AVM[9],   
        NULL_PTR, 
        NULL_PTR
    },
    {
        0, 
        NVM_BLOCK_NATIVE,    
        #if ((NVM_API_CONFIG_CLASS_1!=NVM_API_CONFIG_CLASS)&&(STD_ON==NVM_JOB_PRIORITIZATION))
        0,
        #endif
        NVM_SELCT_BLOCK_4READALL|NVM_SELCT_BLOCK_4WRITEALL|NVM_CALC_RAM_BLOCK_CRC|NVM_BLOCK_USE_CRC|0,
        NVM_CRC16,
        101,
        16,
        1,
        0,
        (uint8*)&gAvmCanFaultBitFlagArray[0],   
        NULL_PTR, 
        NULL_PTR
    },
    {
        0, 
        NVM_BLOCK_NATIVE,    
        #if ((NVM_API_CONFIG_CLASS_1!=NVM_API_CONFIG_CLASS)&&(STD_ON==NVM_JOB_PRIORITIZATION))
        0,
        #endif
        NVM_SELCT_BLOCK_4READALL|NVM_CALC_RAM_BLOCK_CRC|NVM_BLOCK_USE_CRC|0,
        NVM_CRC16,
        102,
        8,
        1,
        0,
        (uint8*)&gpsInfoFromSoc[0],   
        NULL_PTR, 
        NULL_PTR
    },
    {
        0, 
        NVM_BLOCK_NATIVE,    
        #if ((NVM_API_CONFIG_CLASS_1!=NVM_API_CONFIG_CLASS)&&(STD_ON==NVM_JOB_PRIORITIZATION))
        0,
        #endif
        NVM_SELCT_BLOCK_4READALL|NVM_CALC_RAM_BLOCK_CRC|NVM_BLOCK_USE_CRC|0,
        NVM_CRC16,
        103,
        7,
        1,
        0,
        (uint8*)&rtcStoredData[0],   
        NULL_PTR, 
        NULL_PTR
    },
    {
        0, 
        NVM_BLOCK_NATIVE,    
        #if ((NVM_API_CONFIG_CLASS_1!=NVM_API_CONFIG_CLASS)&&(STD_ON==NVM_JOB_PRIORITIZATION))
        0,
        #endif
        NVM_SELCT_BLOCK_4READALL|NVM_SELCT_BLOCK_4WRITEALL|NVM_CALC_RAM_BLOCK_CRC|NVM_BLOCK_USE_CRC|0,
        NVM_CRC16,
        104,
        40,
        1,
        0,
        (uint8*)&gWarningLampLightingRecords[0],   
        NULL_PTR
    },
    {
        0, 
        NVM_BLOCK_NATIVE,    
        #if ((NVM_API_CONFIG_CLASS_1!=NVM_API_CONFIG_CLASS)&&(STD_ON==NVM_JOB_PRIORITIZATION))
        0,
        #endif
        NVM_SELCT_BLOCK_4READALL|NVM_SELCT_BLOCK_4WRITEALL|NVM_CALC_RAM_BLOCK_CRC|NVM_BLOCK_USE_CRC|0,
        NVM_CRC16,
        105,
        40,
        1,
        0,
        (uint8*)&gWarningLampLightingRecords[5],   
        NULL_PTR, 
        NULL_PTR
    },
    {
        0, 
        NVM_BLOCK_NATIVE,    
        #if ((NVM_API_CONFIG_CLASS_1!=NVM_API_CONFIG_CLASS)&&(STD_ON==NVM_JOB_PRIORITIZATION))
        0,
        #endif
        NVM_SELCT_BLOCK_4READALL|NVM_SELCT_BLOCK_4WRITEALL|NVM_CALC_RAM_BLOCK_CRC|NVM_BLOCK_USE_CRC|0,
        NVM_CRC16,
        106,
        40,
        1,
        0,
        (uint8*)&gWarningLampLightingRecords[10],   
        NULL_PTR, 
        NULL_PTR
    },
    {
        0, 
        NVM_BLOCK_NATIVE,    
        #if ((NVM_API_CONFIG_CLASS_1!=NVM_API_CONFIG_CLASS)&&(STD_ON==NVM_JOB_PRIORITIZATION))
        0,
        #endif
        NVM_SELCT_BLOCK_4READALL|NVM_SELCT_BLOCK_4WRITEALL|NVM_CALC_RAM_BLOCK_CRC|NVM_BLOCK_USE_CRC|0,
        NVM_CRC16,
        107,
        40,
        1,
        0,
        (uint8*)&gWarningLampLightingRecords[15],   
        NULL_PTR, 
        NULL_PTR
    },
    {
        0, 
        NVM_BLOCK_NATIVE,    
        #if ((NVM_API_CONFIG_CLASS_1!=NVM_API_CONFIG_CLASS)&&(STD_ON==NVM_JOB_PRIORITIZATION))
        0,
        #endif
        NVM_SELCT_BLOCK_4READALL|NVM_SELCT_BLOCK_4WRITEALL|NVM_CALC_RAM_BLOCK_CRC|NVM_BLOCK_USE_CRC|0,
        NVM_CRC16,
        108,
        40,
        1,
        0,
        (uint8*)&gWarningLampLightingRecords[20],   
        NULL_PTR, 
        NULL_PTR
    },
    {
        0, 
        NVM_BLOCK_NATIVE,    
        #if ((NVM_API_CONFIG_CLASS_1!=NVM_API_CONFIG_CLASS)&&(STD_ON==NVM_JOB_PRIORITIZATION))
        0,
        #endif
        NVM_SELCT_BLOCK_4READALL|NVM_SELCT_BLOCK_4WRITEALL|NVM_CALC_RAM_BLOCK_CRC|NVM_BLOCK_USE_CRC|0,
        NVM_CRC16,
        109,
        40,
        1,
        0,
        (uint8*)&gWarningLampLightingRecords[25],   
        NULL_PTR, 
        NULL_PTR
    },
    {
        0, 
        NVM_BLOCK_NATIVE,    
        #if ((NVM_API_CONFIG_CLASS_1!=NVM_API_CONFIG_CLASS)&&(STD_ON==NVM_JOB_PRIORITIZATION))
        0,
        #endif
        NVM_SELCT_BLOCK_4READALL|NVM_SELCT_BLOCK_4WRITEALL|NVM_CALC_RAM_BLOCK_CRC|NVM_BLOCK_USE_CRC|0,
        NVM_CRC16,
        110,
        40,
        1,
        0,
        (uint8*)&gWarningLampLightingRecords[30],   
        NULL_PTR, 
        NULL_PTR
    },
    {
        0, 
        NVM_BLOCK_NATIVE,    
        #if ((NVM_API_CONFIG_CLASS_1!=NVM_API_CONFIG_CLASS)&&(STD_ON==NVM_JOB_PRIORITIZATION))
        0,
        #endif
        NVM_SELCT_BLOCK_4READALL|NVM_SELCT_BLOCK_4WRITEALL|NVM_CALC_RAM_BLOCK_CRC|NVM_BLOCK_USE_CRC|0,
        NVM_CRC16,
        111,
        40,
        1,
        0,
        (uint8*)&gWarningLampLightingRecords[35],   
        NULL_PTR, 
        NULL_PTR
    },
    {
        0, 
        NVM_BLOCK_NATIVE,    
        #if ((NVM_API_CONFIG_CLASS_1!=NVM_API_CONFIG_CLASS)&&(STD_ON==NVM_JOB_PRIORITIZATION))
        0,
        #endif
        NVM_SELCT_BLOCK_4READALL|NVM_SELCT_BLOCK_4WRITEALL|NVM_CALC_RAM_BLOCK_CRC|NVM_BLOCK_USE_CRC|0,
        NVM_CRC16,
        112,
        40,
        1,
        0,
        (uint8*)&gWarningLampLightingRecords[40],   
        NULL_PTR, 
        NULL_PTR
    },
    {
        0, 
        NVM_BLOCK_NATIVE,    
        #if ((NVM_API_CONFIG_CLASS_1!=NVM_API_CONFIG_CLASS)&&(STD_ON==NVM_JOB_PRIORITIZATION))
        0,
        #endif
        NVM_SELCT_BLOCK_4READALL|NVM_SELCT_BLOCK_4WRITEALL|NVM_CALC_RAM_BLOCK_CRC|NVM_BLOCK_USE_CRC|0,
        NVM_CRC16,
        113,
        40,
        1,
        0,
        (uint8*)&gWarningLampLightingRecords[45],   
        NULL_PTR, 
        NULL_PTR
    },
    {
        0, 
        NVM_BLOCK_NATIVE,    
        #if ((NVM_API_CONFIG_CLASS_1!=NVM_API_CONFIG_CLASS)&&(STD_ON==NVM_JOB_PRIORITIZATION))
        0,
        #endif
        NVM_SELCT_BLOCK_4READALL|NVM_SELCT_BLOCK_4WRITEALL|NVM_CALC_RAM_BLOCK_CRC|NVM_BLOCK_USE_CRC|0,
        NVM_CRC16,
        114,
        40,
        1,
        0,
        (uint8*)&gWarningLampLightingRecords[50],   
        NULL_PTR, 
        NULL_PTR
    },
    {
        0, 
        NVM_BLOCK_NATIVE,    
        #if ((NVM_API_CONFIG_CLASS_1!=NVM_API_CONFIG_CLASS)&&(STD_ON==NVM_JOB_PRIORITIZATION))
        0,
        #endif
        NVM_SELCT_BLOCK_4READALL|NVM_SELCT_BLOCK_4WRITEALL|NVM_CALC_RAM_BLOCK_CRC|NVM_BLOCK_USE_CRC|0,
        NVM_CRC16,
        115,
        32,
        1,
        0,
        (uint8*)&gWarningLampLightingRecords[55],   
        NULL_PTR, 
        NULL_PTR
    },
    {
        0, 
        NVM_BLOCK_NATIVE,    
        #if ((NVM_API_CONFIG_CLASS_1!=NVM_API_CONFIG_CLASS)&&(STD_ON==NVM_JOB_PRIORITIZATION))
        0,
        #endif
        NVM_SELCT_BLOCK_4READALL|NVM_SELCT_BLOCK_4WRITEALL|NVM_CALC_RAM_BLOCK_CRC|NVM_BLOCK_USE_CRC|0,
        NVM_CRC16,
        116,
        1,
        1,
        0,
        (uint8*)&g_AVM_ProductionLine[0],   
        NULL_PTR, 
        NULL_PTR
    },
    {
        0, 
        NVM_BLOCK_NATIVE,    
        #if ((NVM_API_CONFIG_CLASS_1!=NVM_API_CONFIG_CLASS)&&(STD_ON==NVM_JOB_PRIORITIZATION))
        0,
        #endif
        NVM_SELCT_BLOCK_4READALL|NVM_SELCT_BLOCK_4WRITEALL|NVM_CALC_RAM_BLOCK_CRC|NVM_BLOCK_USE_CRC|0,
        NVM_CRC16,
        117,
        32,
        1,
        0,
        (uint8*)&gCrashRegisterRecord[0],   
        NULL_PTR, 
        NULL_PTR
    },
    {
        0, 
        NVM_BLOCK_NATIVE,    
        #if ((NVM_API_CONFIG_CLASS_1!=NVM_API_CONFIG_CLASS)&&(STD_ON==NVM_JOB_PRIORITIZATION))
        0,
        #endif
        NVM_SELCT_BLOCK_4READALL|NVM_SELCT_BLOCK_4WRITEALL|NVM_CALC_RAM_BLOCK_CRC|NVM_BLOCK_USE_CRC|0,
        NVM_CRC16,
        118,
        3,
        1,
        0,
        (uint8*)&gRuntimeSnapshot_HUD[0],   
        NULL_PTR
    },
    {
        0, 
        NVM_BLOCK_NATIVE,    
        #if ((NVM_API_CONFIG_CLASS_1!=NVM_API_CONFIG_CLASS)&&(STD_ON==NVM_JOB_PRIORITIZATION))
        0,
        #endif
        NVM_SELCT_BLOCK_4READALL|NVM_SELCT_BLOCK_4WRITEALL|NVM_CALC_RAM_BLOCK_CRC|NVM_BLOCK_USE_CRC|0,
        NVM_CRC16,
        119,
        3,
        1,
        0,
        (uint8*)&gRuntimeSnapshot_HUD[1],   
        NULL_PTR, 
        NULL_PTR
    },
    {
        0, 
        NVM_BLOCK_NATIVE,    
        #if ((NVM_API_CONFIG_CLASS_1!=NVM_API_CONFIG_CLASS)&&(STD_ON==NVM_JOB_PRIORITIZATION))
        0,
        #endif
        NVM_SELCT_BLOCK_4READALL|NVM_SELCT_BLOCK_4WRITEALL|NVM_CALC_RAM_BLOCK_CRC|NVM_BLOCK_USE_CRC|0,
        NVM_CRC16,
        120,
        3,
        1,
        0,
        (uint8*)&gRuntimeSnapshot_HUD[2],   
        NULL_PTR, 
        NULL_PTR
    },
    {
        0, 
        NVM_BLOCK_NATIVE,    
        #if ((NVM_API_CONFIG_CLASS_1!=NVM_API_CONFIG_CLASS)&&(STD_ON==NVM_JOB_PRIORITIZATION))
        0,
        #endif
        NVM_SELCT_BLOCK_4READALL|NVM_SELCT_BLOCK_4WRITEALL|NVM_CALC_RAM_BLOCK_CRC|NVM_BLOCK_USE_CRC|0,
        NVM_CRC16,
        121,
        3,
        1,
        0,
        (uint8*)&gRuntimeSnapshot_HUD[3],   
        NULL_PTR, 
        NULL_PTR
    },
    {
        0, 
        NVM_BLOCK_NATIVE,    
        #if ((NVM_API_CONFIG_CLASS_1!=NVM_API_CONFIG_CLASS)&&(STD_ON==NVM_JOB_PRIORITIZATION))
        0,
        #endif
        NVM_SELCT_BLOCK_4READALL|NVM_SELCT_BLOCK_4WRITEALL|NVM_CALC_RAM_BLOCK_CRC|NVM_BLOCK_USE_CRC|0,
        NVM_CRC16,
        122,
        3,
        1,
        0,
        (uint8*)&gRuntimeSnapshot_HUD[4],   
        NULL_PTR, 
        NULL_PTR
    },
    {
        0, 
        NVM_BLOCK_NATIVE,    
        #if ((NVM_API_CONFIG_CLASS_1!=NVM_API_CONFIG_CLASS)&&(STD_ON==NVM_JOB_PRIORITIZATION))
        0,
        #endif
        NVM_SELCT_BLOCK_4READALL|NVM_SELCT_BLOCK_4WRITEALL|NVM_CALC_RAM_BLOCK_CRC|NVM_BLOCK_USE_CRC|0,
        NVM_CRC16,
        123,
        3,
        1,
        0,
        (uint8*)&gRuntimeSnapshot_HUD[5],   
        NULL_PTR, 
        NULL_PTR
    },
    {
        0, 
        NVM_BLOCK_NATIVE,    
        #if ((NVM_API_CONFIG_CLASS_1!=NVM_API_CONFIG_CLASS)&&(STD_ON==NVM_JOB_PRIORITIZATION))
        0,
        #endif
        NVM_SELCT_BLOCK_4READALL|NVM_SELCT_BLOCK_4WRITEALL|NVM_CALC_RAM_BLOCK_CRC|NVM_BLOCK_USE_CRC|0,
        NVM_CRC16,
        124,
        3,
        1,
        0,
        (uint8*)&gRuntimeSnapshot_HUD[6],   
        NULL_PTR, 
        NULL_PTR
    },
    {
        0, 
        NVM_BLOCK_NATIVE,    
        #if ((NVM_API_CONFIG_CLASS_1!=NVM_API_CONFIG_CLASS)&&(STD_ON==NVM_JOB_PRIORITIZATION))
        0,
        #endif
        NVM_SELCT_BLOCK_4READALL|NVM_SELCT_BLOCK_4WRITEALL|NVM_CALC_RAM_BLOCK_CRC|NVM_BLOCK_USE_CRC|0,
        NVM_CRC16,
        125,
        3,
        1,
        0,
        (uint8*)&gRuntimeSnapshot_HUD[7],   
        NULL_PTR, 
        NULL_PTR
    },
    {
        0, 
        NVM_BLOCK_NATIVE,    
        #if ((NVM_API_CONFIG_CLASS_1!=NVM_API_CONFIG_CLASS)&&(STD_ON==NVM_JOB_PRIORITIZATION))
        0,
        #endif
        NVM_SELCT_BLOCK_4READALL|NVM_SELCT_BLOCK_4WRITEALL|NVM_CALC_RAM_BLOCK_CRC|NVM_BLOCK_USE_CRC|0,
        NVM_CRC16,
        126,
        3,
        1,
        0,
        (uint8*)&gRuntimeSnapshot_HUD[8],   
        NULL_PTR, 
        NULL_PTR
    },
    {
        0, 
        NVM_BLOCK_NATIVE,    
        #if ((NVM_API_CONFIG_CLASS_1!=NVM_API_CONFIG_CLASS)&&(STD_ON==NVM_JOB_PRIORITIZATION))
        0,
        #endif
        NVM_SELCT_BLOCK_4READALL|NVM_SELCT_BLOCK_4WRITEALL|NVM_CALC_RAM_BLOCK_CRC|NVM_BLOCK_USE_CRC|0,
        NVM_CRC16,
        127,
        3,
        1,
        0,
        (uint8*)&gRuntimeSnapshot_HUD[9],   
        NULL_PTR, 
        NULL_PTR
    },
    {
        0, 
        NVM_BLOCK_NATIVE,    
        #if ((NVM_API_CONFIG_CLASS_1!=NVM_API_CONFIG_CLASS)&&(STD_ON==NVM_JOB_PRIORITIZATION))
        0,
        #endif
        NVM_SELCT_BLOCK_4READALL|NVM_SELCT_BLOCK_4WRITEALL|NVM_CALC_RAM_BLOCK_CRC|NVM_BLOCK_USE_CRC|0,
        NVM_CRC16,
        128,
        3,
        1,
        0,
        (uint8*)&gRuntimeSnapshot_HUD[10],   
        NULL_PTR, 
        NULL_PTR
    },
    {
        0, 
        NVM_BLOCK_NATIVE,    
        #if ((NVM_API_CONFIG_CLASS_1!=NVM_API_CONFIG_CLASS)&&(STD_ON==NVM_JOB_PRIORITIZATION))
        0,
        #endif
        NVM_SELCT_BLOCK_4READALL|NVM_SELCT_BLOCK_4WRITEALL|NVM_CALC_RAM_BLOCK_CRC|NVM_BLOCK_USE_CRC|0,
        NVM_CRC16,
        129,
        3,
        1,
        0,
        (uint8*)&gRuntimeSnapshot_HUD[11],   
        NULL_PTR, 
        NULL_PTR
    },
    {
        0, 
        NVM_BLOCK_NATIVE,    
        #if ((NVM_API_CONFIG_CLASS_1!=NVM_API_CONFIG_CLASS)&&(STD_ON==NVM_JOB_PRIORITIZATION))
        0,
        #endif
        NVM_SELCT_BLOCK_4READALL|NVM_SELCT_BLOCK_4WRITEALL|NVM_CALC_RAM_BLOCK_CRC|NVM_BLOCK_USE_CRC|0,
        NVM_CRC16,
        130,
        3,
        1,
        0,
        (uint8*)&gRuntimeSnapshot_HUD[12],   
        NULL_PTR, 
        NULL_PTR
    },
    {
        0, 
        NVM_BLOCK_NATIVE,    
        #if ((NVM_API_CONFIG_CLASS_1!=NVM_API_CONFIG_CLASS)&&(STD_ON==NVM_JOB_PRIORITIZATION))
        0,
        #endif
        NVM_SELCT_BLOCK_4READALL|NVM_SELCT_BLOCK_4WRITEALL|NVM_CALC_RAM_BLOCK_CRC|NVM_BLOCK_USE_CRC|0,
        NVM_CRC16,
        131,
        3,
        1,
        0,
        (uint8*)&gRuntimeSnapshot_HUD[13],   
        NULL_PTR, 
        NULL_PTR
    },
    {
        0, 
        NVM_BLOCK_NATIVE,    
        #if ((NVM_API_CONFIG_CLASS_1!=NVM_API_CONFIG_CLASS)&&(STD_ON==NVM_JOB_PRIORITIZATION))
        0,
        #endif
        NVM_SELCT_BLOCK_4READALL|NVM_SELCT_BLOCK_4WRITEALL|NVM_CALC_RAM_BLOCK_CRC|NVM_BLOCK_USE_CRC|0,
        NVM_CRC16,
        132,
        6,
        1,
        0,
        (uint8*)&gDtcStatusAndExtInfor_HUD[0],   
        NULL_PTR
    },
    {
        0, 
        NVM_BLOCK_NATIVE,    
        #if ((NVM_API_CONFIG_CLASS_1!=NVM_API_CONFIG_CLASS)&&(STD_ON==NVM_JOB_PRIORITIZATION))
        0,
        #endif
        NVM_SELCT_BLOCK_4READALL|NVM_SELCT_BLOCK_4WRITEALL|NVM_CALC_RAM_BLOCK_CRC|NVM_BLOCK_USE_CRC|0,
        NVM_CRC16,
        133,
        6,
        1,
        0,
        (uint8*)&gDtcStatusAndExtInfor_HUD[1],   
        NULL_PTR, 
        NULL_PTR
    },
    {
        0, 
        NVM_BLOCK_NATIVE,    
        #if ((NVM_API_CONFIG_CLASS_1!=NVM_API_CONFIG_CLASS)&&(STD_ON==NVM_JOB_PRIORITIZATION))
        0,
        #endif
        NVM_SELCT_BLOCK_4READALL|NVM_SELCT_BLOCK_4WRITEALL|NVM_CALC_RAM_BLOCK_CRC|NVM_BLOCK_USE_CRC|0,
        NVM_CRC16,
        134,
        6,
        1,
        0,
        (uint8*)&gDtcStatusAndExtInfor_HUD[2],   
        NULL_PTR, 
        NULL_PTR
    },
    {
        0, 
        NVM_BLOCK_NATIVE,    
        #if ((NVM_API_CONFIG_CLASS_1!=NVM_API_CONFIG_CLASS)&&(STD_ON==NVM_JOB_PRIORITIZATION))
        0,
        #endif
        NVM_SELCT_BLOCK_4READALL|NVM_SELCT_BLOCK_4WRITEALL|NVM_CALC_RAM_BLOCK_CRC|NVM_BLOCK_USE_CRC|0,
        NVM_CRC16,
        135,
        6,
        1,
        0,
        (uint8*)&gDtcStatusAndExtInfor_HUD[3],   
        NULL_PTR, 
        NULL_PTR
    },
    {
        0, 
        NVM_BLOCK_NATIVE,    
        #if ((NVM_API_CONFIG_CLASS_1!=NVM_API_CONFIG_CLASS)&&(STD_ON==NVM_JOB_PRIORITIZATION))
        0,
        #endif
        NVM_SELCT_BLOCK_4READALL|NVM_SELCT_BLOCK_4WRITEALL|NVM_CALC_RAM_BLOCK_CRC|NVM_BLOCK_USE_CRC|0,
        NVM_CRC16,
        136,
        6,
        1,
        0,
        (uint8*)&gDtcStatusAndExtInfor_HUD[4],   
        NULL_PTR, 
        NULL_PTR
    },
    {
        0, 
        NVM_BLOCK_NATIVE,    
        #if ((NVM_API_CONFIG_CLASS_1!=NVM_API_CONFIG_CLASS)&&(STD_ON==NVM_JOB_PRIORITIZATION))
        0,
        #endif
        NVM_SELCT_BLOCK_4READALL|NVM_SELCT_BLOCK_4WRITEALL|NVM_CALC_RAM_BLOCK_CRC|NVM_BLOCK_USE_CRC|0,
        NVM_CRC16,
        137,
        6,
        1,
        0,
        (uint8*)&gDtcStatusAndExtInfor_HUD[5],   
        NULL_PTR, 
        NULL_PTR
    },
    {
        0, 
        NVM_BLOCK_NATIVE,    
        #if ((NVM_API_CONFIG_CLASS_1!=NVM_API_CONFIG_CLASS)&&(STD_ON==NVM_JOB_PRIORITIZATION))
        0,
        #endif
        NVM_SELCT_BLOCK_4READALL|NVM_SELCT_BLOCK_4WRITEALL|NVM_CALC_RAM_BLOCK_CRC|NVM_BLOCK_USE_CRC|0,
        NVM_CRC16,
        138,
        6,
        1,
        0,
        (uint8*)&gDtcStatusAndExtInfor_HUD[6],   
        NULL_PTR, 
        NULL_PTR
    },
    {
        0, 
        NVM_BLOCK_NATIVE,    
        #if ((NVM_API_CONFIG_CLASS_1!=NVM_API_CONFIG_CLASS)&&(STD_ON==NVM_JOB_PRIORITIZATION))
        0,
        #endif
        NVM_SELCT_BLOCK_4READALL|NVM_SELCT_BLOCK_4WRITEALL|NVM_CALC_RAM_BLOCK_CRC|NVM_BLOCK_USE_CRC|0,
        NVM_CRC16,
        139,
        6,
        1,
        0,
        (uint8*)&gDtcStatusAndExtInfor_HUD[7],   
        NULL_PTR, 
        NULL_PTR
    },
    {
        0, 
        NVM_BLOCK_NATIVE,    
        #if ((NVM_API_CONFIG_CLASS_1!=NVM_API_CONFIG_CLASS)&&(STD_ON==NVM_JOB_PRIORITIZATION))
        0,
        #endif
        NVM_SELCT_BLOCK_4READALL|NVM_SELCT_BLOCK_4WRITEALL|NVM_CALC_RAM_BLOCK_CRC|NVM_BLOCK_USE_CRC|0,
        NVM_CRC16,
        140,
        6,
        1,
        0,
        (uint8*)&gDtcStatusAndExtInfor_HUD[8],   
        NULL_PTR, 
        NULL_PTR
    },
    {
        0, 
        NVM_BLOCK_NATIVE,    
        #if ((NVM_API_CONFIG_CLASS_1!=NVM_API_CONFIG_CLASS)&&(STD_ON==NVM_JOB_PRIORITIZATION))
        0,
        #endif
        NVM_SELCT_BLOCK_4READALL|NVM_SELCT_BLOCK_4WRITEALL|NVM_CALC_RAM_BLOCK_CRC|NVM_BLOCK_USE_CRC|0,
        NVM_CRC16,
        141,
        6,
        1,
        0,
        (uint8*)&gDtcStatusAndExtInfor_HUD[9],   
        NULL_PTR, 
        NULL_PTR
    },
    {
        0, 
        NVM_BLOCK_NATIVE,    
        #if ((NVM_API_CONFIG_CLASS_1!=NVM_API_CONFIG_CLASS)&&(STD_ON==NVM_JOB_PRIORITIZATION))
        0,
        #endif
        NVM_SELCT_BLOCK_4READALL|NVM_SELCT_BLOCK_4WRITEALL|NVM_CALC_RAM_BLOCK_CRC|NVM_BLOCK_USE_CRC|0,
        NVM_CRC16,
        142,
        6,
        1,
        0,
        (uint8*)&gDtcStatusAndExtInfor_HUD[10],   
        NULL_PTR, 
        NULL_PTR
    },
    {
        0, 
        NVM_BLOCK_NATIVE,    
        #if ((NVM_API_CONFIG_CLASS_1!=NVM_API_CONFIG_CLASS)&&(STD_ON==NVM_JOB_PRIORITIZATION))
        0,
        #endif
        NVM_SELCT_BLOCK_4READALL|NVM_SELCT_BLOCK_4WRITEALL|NVM_CALC_RAM_BLOCK_CRC|NVM_BLOCK_USE_CRC|0,
        NVM_CRC16,
        143,
        6,
        1,
        0,
        (uint8*)&gDtcStatusAndExtInfor_HUD[11],   
        NULL_PTR, 
        NULL_PTR
    },
    {
        0, 
        NVM_BLOCK_NATIVE,    
        #if ((NVM_API_CONFIG_CLASS_1!=NVM_API_CONFIG_CLASS)&&(STD_ON==NVM_JOB_PRIORITIZATION))
        0,
        #endif
        NVM_SELCT_BLOCK_4READALL|NVM_SELCT_BLOCK_4WRITEALL|NVM_CALC_RAM_BLOCK_CRC|NVM_BLOCK_USE_CRC|0,
        NVM_CRC16,
        144,
        6,
        1,
        0,
        (uint8*)&gDtcStatusAndExtInfor_HUD[12],   
        NULL_PTR, 
        NULL_PTR
    },
    {
        0, 
        NVM_BLOCK_NATIVE,    
        #if ((NVM_API_CONFIG_CLASS_1!=NVM_API_CONFIG_CLASS)&&(STD_ON==NVM_JOB_PRIORITIZATION))
        0,
        #endif
        NVM_SELCT_BLOCK_4READALL|NVM_SELCT_BLOCK_4WRITEALL|NVM_CALC_RAM_BLOCK_CRC|NVM_BLOCK_USE_CRC|0,
        NVM_CRC16,
        145,
        6,
        1,
        0,
        (uint8*)&gDtcStatusAndExtInfor_HUD[13],   
        NULL_PTR, 
        NULL_PTR
    },

};




